### ISSUE TITLE
Feature request: multi node support

### ISSUE THREAD

**Issue by bluepuma77** [Dokploy/dokploy#1]
It would be create to manage multiple nodes (servers) to scale services and create high availability.

**Comment by hcaz** [comment]
When you install this it does create a docker swarm cluster and give you the command to add another node. I dont know if it takes advantage of this by default but it seems the underlying core is there

**Comment by Siumauricio** [comment]
Let's leave it open for now. Currently we will be focusing on fixing bugs.

But in advance

- How the multi node should work?
- What happen when we have images builded in the manager node, how we can share accross the workers?
- We need to suport self hosted registry and cloud registries?

Any feedback/information about how it should work would be appreciate!

**Comment by hcaz** [comment]
I think it would be good if you could add new nodes to the swarm (Using the docker swarm command).

And in the panel it showed a list of all nodes and their status - This could come from the `docker node ls` and [node inspect command](https://docs.docker.com/engine/swarm/manage-nodes/).

Then when creating a new service you can set the number of replicas which docker swarm should handle automatically across nodes. You could maybe implement labels too to help direct replicas and services

**Comment by Siumauricio** [comment]
For images that are already in the cloud they will work, but for applications builded locally they will not work read here

https://docs.docker.com/engine/swarm/stack-deploy/#set-up-a-docker-registry

**Comment by Chev187** [comment]
would be great if with creating a new project you could attach a separate node via an agent, api or a socket.

**Comment by cpatrickalves** [comment]
Is possible to add Dokploy in an existing Docker Swarm (with multiple nodes)?

**Comment by Siumauricio** [comment]
> would be great if with creating a new project you could attach a separate node via an agent, api or a socket.

Can you be more specific on this? you mean run application on a specific node?

**Comment by Siumauricio** [comment]
> Is possible to add Dokploy in an existing Docker Swarm (with multiple nodes)?

Yes, Is possible but i need to make some docs about that

**Comment by Siumauricio** [comment]
Multi node support is already working, if you would like to test the functionality go to this #96  and try it right now, I am collecting feedback about what you think about it.
