### ISSUE TITLE
Connecting Github is returning 404

### ISSUE THREAD

**Issue by Soben** [Dokploy/dokploy#10]
I went through the first step to register a github 'application' and then clicked the link to connect that application with my account, but github sends me to a `404` page.

![Screenshot 2024-04-30 at 12 14 53 PM](https://github.com/Dokploy/dokploy/assets/194854/e06bada0-353d-447a-998b-ebd5f732639d)

While double checking the settings in Github, I tried to install the app directly from Github, but I got an 'Internal Server Error' after approving the access.

Example url ```https://github.com/apps/Dokploy%20on%20Ordos/installations/new?state=gh_setup:keyhere```

At this point, how can I delete the application and/or resolve?

**Comment by Siumauricio** [comment]
Hmm weird issue, can you please go settings -> server and then scroll down and check the server logs? you probably can see the error.

There is a button to remove the github app, but you can remove only after you setup sucesfully, so I need to add the button before you install the github app

**Comment by coderkhalide** [comment]
Found the solution

- do not use space while creating app on github.
- Follow: https://github.com/Dokploy/dokploy/issues/12

**Comment by Soben** [comment]
Thanks @coderkhalide 

As a whole, this project still seems a little too early in development for my purposes. I'm super excited to use it, but (GitHub completely aside) the interface isn't quite sufficient for my needs at this time.

Going to flag this as closed, as I've already deleted the DO droplet I was experimenting with this on, assuming @coderkhalide's notes as correct.

**Comment by coderkhalide** [comment]
@Soben yes it worked actually. I was able to deploy my portfolio on https://me.khaliddev.com
Looks like working fine. But i agree, it needs more development.

<img width="1220" alt="image" src="https://github.com/Dokploy/dokploy/assets/72712376/e949e792-fe1e-4f1e-837c-f2b665ab5475">

**Comment by Siumauricio** [comment]
I did the process from scratch and i dont see any issues 

https://github.com/Dokploy/dokploy/assets/47042324/5ca84289-13b5-4c32-a86c-c6d0660aa433

**Comment by coderkhalide** [comment]
@Siumauricio looks like you did not got the 404 bcz your app name had no space. if app name contains space then it throw 404 error on Github.

**Comment by Siumauricio** [comment]
The issue is already fixed it will be published in the next version thanks!
