### ISSUE TITLE
Can't close an orphan container

### ISSUE THREAD

**Issue by Pi-Bouf** [Dokploy/dokploy#1013]
### To Reproduce

1. Created an application (custom, with Git)
2. I think I changed the build system (from nix to dockerfile)
3. Impossible to delete this container

### Current vs. Expected behavior

<img width="1373" alt="image" src="https://github.com/user-attachments/assets/46ffc82d-92fa-45a9-8f83-2923c0f6bee9" />
I'm expecting NOTHING in this list, not an strange outdated orphan container

### Provide environment information

```bash
Operating System:
- Ubuntu 22

VPS Hostinger KVM 2
```

### Which area(s) are affected? (Select all that apply)

Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
This is the expected behavior, when you craete deployments it doesnt cleanup the exited containers, you can cleanup manually in settings -> space -> clean stopped containers

**Comment by Pi-Bouf** [comment]
I just tried this method. And sadly, this fu**** container is always here !
This button is only for the "stopped" containers, mine is running and I don't know why

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/071d1ad0-e6aa-444d-a22a-b659ab3b8514" />


This is the last one, running since 2d. And as you can see, two *server containers with same name are running. One is from an older revision. The is the one I can't stop.


Do I need to delete an entry in the postgre or whatever to destroy it ?
