### ISSUE TITLE
Auto deploy webhook FILTER

### ISSUE THREAD

**Issue by hikinine** [Dokploy/dokploy#107]
Greetings, Great project!

# Summary 
On webhook autodeploy, consider only specified image tags to trigger deploy action

# Description

I'm using dokploy in production for some personal projects.

In /services/application -> deployments there is the option to use the webhook url to integrate with dockerhub.

I have an github actions that, when starting a release, builds the application and pushes it to dockerhub.
On my dockerhub repo, i  register that webhook url and everything works fine except...

My actions pushs actually 3 images (that was my call):
```
frontend:production
frontend:github_sha
frontend:v2.1.329    (lets say)
```

Is it feasible to implement a filter option? 

# Problem 

Same image, with 3 different tags (for documentation, history, security purposes) are triggering 3 different deploy actions

# Suggested Solution
1 - Perhaps we should automatically consider only the  `<tag>` that is provided in the docker setup  provider?
2 - On webhook register, allow user to decide which image tags would listener to.

### .
![image](https://github.com/Dokploy/dokploy/assets/30875229/15cb51a5-9821-4bee-a4e0-5c5a04c1bc29)

**Comment by Siumauricio** [comment]
I understand the problem, definitely the easiest solution would be to filter by the tag chosen in the docker setup provider, this would make it easier

**Comment by hikinine** [comment]
> I understand the problem, definitely the easiest solution would be to filter by the tag chosen in the docker setup provider, this would make it easier

You are right, problem is that dockerhub does not offer any  support to filter / condition webhook triggers. 
Maybe with github webhook i can  achieve that behaviour. 

Thanks for the reply!

**Comment by Siumauricio** [comment]
Yeah, what i mean is we can change the behavior in the endpoint where we recieve the webhook, and filter by the tag you specified in the docker provider, I think this will have more sense, because if tou specified a specific tag, you expect to be deployed only on that specific tag

**Comment by hikinine** [comment]
With github integration worked as expected. 
Kinda different workflow since now its listening to "push" on specified branch and then building that source code and deploying.

I'm still a little worried about build the application in the same machine that I use for production apps (maybe its just over thinking since my apps are lightweight). 


Anyway, 
I'm studying the dokploy architecture a little bit. As I understood, 

1 - Dokploy listens to http request on `/api/deploy/<refreshToken>` (which do we pass to providers dockerhub, etc..)
2 - Find application by using provided token
3 - If application deploy sourceType is git / github: 
   -> Ensure that webhook payload matchs with provided branch (if not, ends with 301 status)
4 - Push `deployments` to queue.
https://github.com/Dokploy/dokploy/blob/874d1f9fe43f591a08ee64c82b23c9cb34248bf3/pages/api/deploy/%5BrefreshToken%5D.ts#L36-L50

5 - `deployments` worker start job execution.
6 - Processor execute `deployApplication` which will execute deploy action based on sourceType
Lets say our sourceType is "docker".

7 - Execute `dockerBuild` which will docker pull the image with provided setup (including tag).

Looks like dokploy is not deploying the other tags, which is great... I mean, we dont read the webhook payload. It is used only to trigger the deploy (which i think is the right choice). 


## Its a fake data (`titleLog` naming event payload)
dokploy took from webhook payload the name from tags (production, staging, etc) but it never deployed every image... It only repeat the same deploy for the initial provided tag image
![image](https://github.com/Dokploy/dokploy/assets/30875229/1032f5f3-03ee-423f-8f3a-a5f30ae83cd0)

So... there is no problem (only multiple deploy of the same image) 

## Solution
```ts
if (sourceType === 'docker') {
    const currentTagName = getTagFromDockerImage(application.dockerImage) ?? 'latest'


   if (currentTagName) {
      const requestBody =  request.body // i dont know how to access it
     // https://docs.docker.com/docker-hub/webhooks/?_gl=1*1ksgu74*_ga*NjA2MjQ5NTU3LjE3MTY1NTI4ODc.*_ga_XJWPQMJYHQ*MTcxNjU5Mjc5OS4zLjEuMTcxNjU5MzI2NS41Ny4wLjA.
      const payloadTagName = requestBody.push_data.tag
      if (payloadTagName  !== currentTagName) {
           res.status(301).json({ message: "Branch Not Match" });
	   return;
      }
   }

}
if (sourceType === "github") {
			const branchName = extractBranchName(req.headers, req.body);
			if (!branchName || branchName !== application.branch) {
				res.status(301).json({ message: "Branch Not Match" });
				return;
			}
		} else if (sourceType === "git") {
			const branchName = extractBranchName(req.headers, req.body);
			if (!branchName || branchName !== application.customGitBranch) {
				res.status(301).json({ message: "Branch Not Match" });
				return;
			}
		}
```

**Comment by hikinine** [comment]
Here is the titleLog.
Appears like it is deploying the image described. But its only log purpose (deployed tag is always the provided on initial config)


https://github.com/Dokploy/dokploy/blob/874d1f9fe43f591a08ee64c82b23c9cb34248bf3/pages/api/deploy/%5BrefreshToken%5D.ts#L109-L113

**Comment by Siumauricio** [comment]
Thank you, and good analysis that's how really works dokploy under the hood in deployments terms.

You are right, it will deploy only the tag you selected, but in your case you pushed 3 images at the same time it will create 3 deployments obviously with the same tag, but is not ideal to redeploy 3 times the same tag, We need to apply a filter there to prevent  the deployments when you push another tag, the same as we do in github when the branch doesnt match it will return 301, We can do the same, altought is not a big problem for now but would be ideal to do make this little detail.

Would you ve up to make a PR?

**Comment by hikinine** [comment]
> Would you ve up to make a PR?
I'll be happy to work on it
