### ISSUE TITLE
Error State Redis Database

### ISSUE THREAD

**Issue by simbrams** [Dokploy/dokploy#115]
[dokploy v0.0.3]

Hey,

I created a redis database a few weeks ago and I noticed now the DB is in error state on the dashboard, because it does not find the container in the logs tab.

However the redis instance is still reachable.

In the /dashboard/docker, the Redis instance is not visible.

In the Dokploy Logs, I see this error multiple times:
`Execution error: Error: Command failed: docker ps -a --format 'CONTAINER ID : {{.ID}} | Name: {{.Names}} | State: {{.State}}' | grep redis-calculate-online-alarm-awnft9`

But when I ssh to my machine as root and do the command `docker ps -a --format 'CONTAINER ID : {{.ID}} | Name: {{.Names}} | State: {{.State}}'` I can see the instance with the following informations:

`CONTAINER ID : 4f3a742b259d | Name: dokploy-redis.1.ugedw3gzvlc8fkpl124v7ww5k | State: running` 

So it seems the name has changed and Dokploy does not find the original name. Do you have an Idea how to fix this without re-creating a Redis DB ? And it seems related to your 0.0.4 update, right ?

Thanks

**Comment by Siumauricio** [comment]
Hi, Yes this issue is already fixed in v0.0.4, #100 In the release notes I added steps to fix the issue, all your applications will be up so you are safe to apply the changes
