### ISSUE TITLE
Permision 0777 are too open

### ISSUE THREAD

**Issue by munajaf** [Dokploy/dokploy#120]
Hi. previously my dokploy have an issue where the redis down. but fixed that by getting the latest update. after that my deployment for current project i received this kind of issue.

<img width="837" alt="image" src="https://github.com/Dokploy/dokploy/assets/4621701/bbcb19d3-61fd-48be-be65-4756823d9a6c">

**Comment by Siumauricio** [comment]
Can you try to run this?

`chmod -R 600/etc/dokploy/ssh/`

**Comment by manardev** [comment]
i fixed this by updating to latest docker image by running the installation command again. after that i had to remove my ssh-key and regenerate new. works fine after that

**Comment by munajaf** [comment]
i had to update dokploy docker image by running back the installation command. after that i regenerate back the ssh-key. works fine after that. thanks
