### ISSUE TITLE
Support for folder deployment, and Drag n Drop

### ISSUE THREAD

**Issue by simbrams** [Dokploy/dokploy#131]
Hey, do you plan to offer a solution to quickly deploy an application by just uploading a folder like Netlify does ? 

It would be very handy for small projects or testing uses-cases.

Currently the synchronization with Github is limitating because we can only synchronise 1 organization (or doing it using SSH for full github access). So it would be nice to have this fast alternative where we juste drag n drop the app folder and it deploys automatically :)  

Thank you for your amazing work!

**Comment by Siumauricio** [comment]
Sounds good idea, in fact someone had also commented something related to have a Dockerfile editor in the discord, but it would be a great idea to add the Dockerfile + Drag n Drop.

**Comment by simbrams** [comment]
Yes, deploying a single Dockerfile or the full project folder and letting Nixpacks do the rest would be dope.
