### ISSUE TITLE
Unable to connect to server - Operation timed out error

### ISSUE THREAD

**Issue by jeblister** [Dokploy/dokploy#132]
I am experiencing an issue when trying to connect to my google cloud server at `your-ip-from-your-vps:3000`. When I run the command `curl http://your-ip-from-your-vps:3000`, I receive the following error:

```
Trying your-ip-from-your-vps:3000...
* connect to {{my-ip-from-gc}} port 3000 from .... port 52289 failed: Operation timed out
* Failed to connect to {{my-ip-from-gc}} port 3000 after 75002 ms: Couldn't connect to server
* Closing connection
curl: (28) Failed to connect to {{my-ip-from-gc}} port 3000 after 75002 ms: Couldn't connect to server
```

**Steps to reproduce:**

1. Run the command `curl -v http://your-ip-from-your-vps:3000` on a google cloud VS
2. Observe the error message indicating that the connection timed out

**Expected behavior:**

I expect to be able to connect to the server at `my-ip-from-gc:3000` without any issues.

**Additional context:**

I have checked my firewall settings and ensured that port 3000 is open. I am not using any proxy servers or VPNs.

**Any help would be appreciated!**

**Comment by Siumauricio** [comment]
Hi, Could you give me more details about what instance did you choose to create the machine? what specs and configuration did you use?

From what I see it seems to be either a problem of some internal configuration of your computer or something at the IP level from google cloud, I remember someone used google cloud instances and it worked fine.


In the meantime can you do `docker ps` and pass me the log?

**Comment by Siumauricio** [comment]
@jeblister Feel free to re-open the issue if you still have a issue!

**Comment by kawpii** [comment]
@Siumauricio Experiencing the same on Fedora 42, `docker ps` output

```
CONTAINER ID   IMAGE                    COMMAND                  CREATED          STATUS          PORTS                                                                                                                   NAMES
b7ac80d5665c   traefik:v3.1.2           "/entrypoint.sh trae…"   7 minutes ago    Up 7 minutes    0.0.0.0:80->80/tcp, [::]:80->80/tcp, 0.0.0.0:443->443/tcp, [::]:443->443/tcp, 0.0.0.0:443->443/udp, [::]:443->443/udp   dokploy-traefik
aefa37ac8057   dokploy/dokploy:latest   "docker-entrypoint.s…"   7 minutes ago    Up 7 minutes    0.0.0.0:3000->3000/tcp, [::]:3000->3000/tcp                                                                             dokploy.1.3jcr4ijcptizv71xxup3v09u5
7cb7816ff34f   redis:7                  "docker-entrypoint.s…"   14 minutes ago   Up 14 minutes   6379/tcp                                                                                                                dokploy-redis.1.gikppodiv7b38tn71fyuqmaop
660cca196556   postgres:16              "docker-entrypoint.s…"   15 minutes ago   Up 15 minutes   5432/tcp                                                                                                                dokploy-postgres.1.i5u4nmthjxex3dzmdf6ufsezi
```
