### ISSUE TITLE
License Agreement - Restrictions on Features

### ISSUE THREAD

**Issue by 1CoolUsername** [Dokploy/dokploy#138]
Need clarification on these Additional License Terms: 

> The following additional terms apply to the multi-node support and Docker Compose file support features of Dokploy. In the event of a conflict, these provisions shall take precedence over those in the Apache License:
> 
> Self-Hosted Version Free: All features of Dokploy, including multi-node support and Docker Compose file support, will always be free to use in the self-hosted version.
> 
> Restriction on Resale: The multi-node support and Docker Compose file support features cannot be sold or offered as a service by any party other than the copyright holder without prior written consent.
> 
> Modification Distribution: Any modifications to the multi-node support and Docker Compose file support features must be distributed freely and cannot be sold or offered as a service. 

It sounds like what is trying to be done is limit a brain dead use case that someone would leverage for deployments and commercial use.

Why should these terms be applicable to Open Source? If you expect to sell this product but limit the use case for others it has no value to community.

**Comment by Siumauricio** [comment]
I think you are misunderstanding the license, the Core remains open and can be used to sell, resell and create any SaaS business or whatever you want to do, there is no restriction in that sense, what is only closed is in the sense of selling dokploy with the multi node and docker compose functionalities and sell them as a service, the rest of the features can be sold without problem

**Comment by Siumauricio** [comment]
Since there are no response I guess the statement is clear and concise

**Comment by janbiasi** [comment]
There was an [opened discussion](https://github.com/Dokploy/dokploy/discussions/3) which asked even more question regarding the license (which unfortunately got closed without a comment).

**Comment by ahangarha** [comment]
The license is problematic to me too.

One solution is to separate non-free/opensource code from the rest. There are many projects using directories like `ee` and put their non-free/opensource code there. In the license, they emphasize that the content of that directory is under x license and the rest of the code, unless specified, are under y open source license.
