### ISSUE TITLE
Cant monitor containers deployed with docker-compose. 

### ISSUE THREAD

**Issue by drdDavi** [Dokploy/dokploy#144]
Containers deployed via docker-compose cant be selected in the ui. 

<img width="1320" alt="Screenshot 2024-06-14 at 9 46 09 AM" src="https://github.com/Dokploy/dokploy/assets/47359470/50bfce94-5249-4e37-9075-f926bbd4448f">

**Comment by Siumauricio** [comment]
Can you share your docker-compose file?

**Comment by Mr1Blaze** [comment]
Delete container name because it will be created automatically and will apear in containers and in containers logs

**Comment by drdDavi** [comment]
@Siumauricio and @Mr1Blaze you are correct i was using container_name property. It working now as expected.
