### ISSUE TITLE
Support cloudflare origin certificate

### ISSUE THREAD

**Issue by miguelvictor** [Dokploy/dokploy#145]
Hello! Thanks for the great work!
Is it possible to add support for cloudflare origin certificates in addition to Letsencrypt? All of the web apps in our vps are behind cloudflare and it is mandatory that we use origin certificates instead of Letsencrypt.

**Comment by Mr1Blaze** [comment]
Can you describe more detailed ?

**Comment by miguelvictor** [comment]
Hello! In the sample image below, I deployed a nextjs app and the only certificate source that i could select is letsencrypt even though i added my [origin certificate](https://developers.cloudflare.com/ssl/origin-configuration/origin-ca/) from cloudflare in `/dashboard/settings/certificates`. It would be nice if i could use that certificate so that the connection between cloudflare and the vps is secure.

<img width="996" alt="image" src="https://github.com/Dokploy/dokploy/assets/6831138/f0be4e72-f483-4ea3-b81b-f20dce337095">

**Comment by Siumauricio** [comment]
We just create the certificate in the traefik folder, so that traefik can recognize it, however it is not as easy as just selecting the certificate and it works, you have to do something else at the traefik configuration level, that is why it does not appear to select the certificate.

**Comment by Vanja-S** [comment]
Maybe we can simplify the process of “bring your own certificate”? So that there needs to be less fiddling with the traefik configuration layer.

**Comment by miguelvictor** [comment]
For whoever who might need this feature in the future, here are the steps i did to do it:

1. Add your origin certificate in `/dashboard/settings/certificates`
2. Then your certificate will be added in the `Traefik File System` in `/etc/dokploy/traefik/dynamic/certificates/`
3. When deploy your app, do not choose Letsencrypt. Keep the certificate option to `None`
4. Go to advanced tab and modify the traefik config. Change `entryPoints=web` to `websecure`.
5. Done! ✅

**Comment by Siumauricio** [comment]
Thank you @miguelvictor ❤️

**Comment by mpcref** [comment]
> 2. Your certificate will then be added to the Traefik File System in `/etc/dokploy/traefik/dynamic/certificates/`

This doesn't work for me.
After adding a certificate it doesn't show up in the Traefik File System.
Even if it would show up, I suspect it'll still not work because I need the certificate for a service that's being deployed to a connected remote server.

**Comment by miguelvictor** [comment]
You don’t need steps one and two now. You just need to add your cloudflare origin certificate in `/dashboard/settings/certificates`

**Comment by mpcref** [comment]
@miguelvictor that's step 1, I did that (add the certificate) but that has no further effect. But that's probably because my service is hosted on a server that was added via `/dashboard/settings/servers` and I don't think the certificate is known on that server.

**Comment by Siumauricio** [comment]
No @mpcref, we don't have a way to sync certificates, I'll probably need to add some field to make a certificate to create in the remote server

**Comment by mpcref** [comment]
Yes I agree that would be the best solution. So for now I'll just wait patiently. 😄 
Thanks again!

**Comment by Siumauricio** [comment]
@mpcref In the next version we will include the creation of certs in external servers

**Comment by Sparo** [comment]
> For anyone who might need this feature in the future, here are the steps I took to implement it:
> 
> 1. Add your origin certificate in `/dashboard/settings/certificates`
> 2. Your certificate will then be added to the `Traefik File System` in `/etc/dokploy/traefik/dynamic/certificates/`
> 3. When deploying your app, do not choose Letsencrypt. Keep the certificate option set to `None`
> 4. Go to the advanced tab of your app and modify the Traefik config. Change `entryPoints=web` to `websecure`.
> 5. Done! ✅

Hi,

found this issue since I also have need for origin certificates. I have followed the instructions from here, but in the advanced tab there is not any traefik config options so failed on step 4 :)
<img width="1341" alt="Screenshot 2024-10-26 at 23 14 27" src="https://github.com/user-attachments/assets/602d6193-76f7-4663-9f66-71237891117b">

so not sure how to update traefik config.

any hint?

tnx

**Comment by Siumauricio** [comment]
@Sparo You are using compose, when you use compose you need to write traefik labels by yourself

**Comment by Sparo** [comment]
> @Sparo You are using compose, when you use compose you need to write traefik labels by yourself

Hi, 

Tnx for the reply. 

A have a question about that. Do you maybe have some example how to integrate custom (cloudflare) certificate. I am new to traefik. First time started to learn about it with Dokploy.

If that is not a big problem. 

In any case I will try to find solution by myself, but it could be to save me a lot of time.

Thank you anyway.

**Comment by Binibini10** [comment]
> Maybe we can simplify the process of “bring your own certificate”? So that there needs to be less fiddling with the traefik configuration layer.

Hi Miguel! I can't seem to add certificates. Have you already solved this problem? Thanks.

**Comment by CoderStartup** [comment]
> For anyone who might need this feature in the future, here are the steps I took to implement it:
> 
> 1. Add your origin certificate in `/dashboard/settings/certificates`
> 2. Your certificate will then be added to the `Traefik File System` in `/etc/dokploy/traefik/dynamic/certificates/`
> 3. When deploying your app, do not choose Letsencrypt. Keep the certificate option set to `None`
> 4. Go to the advanced tab of your app and modify the Traefik config. Change `entryPoints=web` to `websecure`.
> 5. Done! ✅

I fully follow these steps but it's not worked for my wildcard subdomain. Can you give me a solution that can support SSL certificate for wildcard subdomain.

**Comment by heruki** [comment]
Why is this closed ?

**Comment by Aadi-0110** [comment]
To anyone coming in later, dokploy will auto use the wildcard certificate in your certificate folder you just need to assign proper subdomain to it.

**Comment by nhridoy** [comment]
Does anyone have any solution?
I have added a certificate in the certificate menu. However, when trying to set that certificate for the Dokploy domain, there is only Let's Encrypt, similar to the project's domain option.

<img width="1326" height="572" alt="Image" src="https://github.com/user-attachments/assets/0b0bedfe-74bd-4d7a-b28e-aa1cd7064fa3" />

Server domain

<img width="1324" height="559" alt="Image" src="https://github.com/user-attachments/assets/799e7306-f971-442c-9ccf-d90fe045acc4" />

<img width="1343" height="552" alt="Image" src="https://github.com/user-attachments/assets/69e9d458-e7ad-4f09-8646-f1cebf8f8787" />

Project domain

I do have a certificate in the certificate menu:

<img width="1348" height="539" alt="Image" src="https://github.com/user-attachments/assets/87a1c0ae-c8c0-402f-a10e-70534205dc60" />
