### ISSUE TITLE
Add commit hash and commit message in the deployment list

### ISSUE THREAD

**Issue by miguelvictor** [Dokploy/dokploy#147]
### What problem will this feature address?

When i go to the deployments list of my dokploy service, i need to be sure that im deploying the correct commit (ADHD problems, maybe) so it would be nice if you could add the commit hash and message in each of the deployment in the list (like Vercel does).

### Describe the solution you'd like

add commit hash and message

### Describe alternatives you've considered

no alternatives found, i just have to make sure that my git branch is updated by going to bitbucket before actually deploying it

### Additional context

Thanks for the hard work!

**Comment by hehehai** [comment]
Its performance should be

- Each deployment has a corresponding branch and commit identification
- commit should show hash and message
- Display the git summary of the current application service (branch/commit) in the service list

**Comment by Siumauricio** [comment]
would definitely be a good idea

**Comment by Siumauricio** [comment]
In the next version you will see the hash when the webhook is being triggered
![Screenshot 2024-06-27 at 10 41 28 PM](https://github.com/Dokploy/dokploy/assets/47042324/96f265df-5d0a-49bc-be09-dc79c1d1dd94)

**Comment by miguelvictor** [comment]
Wow! Thank you!!
