### ISSUE TITLE
Backup DB (mongodb) to S3 errors

### ISSUE THREAD

**Issue by jdmry** [Dokploy/dokploy#149]
### To Reproduce

1. Create a DB (mongodb) and choose a user which is not the default
2. Try to backup to S3
3. See it display an error

### Current vs. Expected behavior

It shows an error instead of validating the backup

### Provide environment information

```bash
MongoDB, but might be similar for others.
```

### Which area(s) are affected? (Select all that apply)

Databases

### Additional context

I know what the problem is, as I checked the server logs.
It tries to initiate the mongodump command with 'mongo' (the default I think) as the database user to connect, instead of using the user provided when the container was created.

**Comment by Siumauricio** [comment]
Thank you, that was the issue we didn't use the databaseUser in the mongoDump, in the next version this should be fixed

**Comment by jdmry** [comment]
Awesome, thanks!

**Comment by Siumauricio** [comment]
Released in v0.2.3!
