### ISSUE TITLE
400 Oops, something went wrong.

### ISSUE THREAD

**Issue by nexmoe** [Dokploy/dokploy#151]
### To Reproduce

I haven't been in for a few days, so I went in at one o'clock today and that's it

### Current vs. Expected behavior

![image](https://github.com/Dokploy/dokploy/assets/16796652/25e893e5-e2a5-48d0-ab9f-4417009d20e7)

### Provide environment information

```bash
LSB Version:    core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

Dokploy Version: 0.22
```

### Which area(s) are affected? (Select all that apply)

Installation, Application, Databases, Docker Compose, Traefik, Docker

### Additional context

If there is any log you need, I will provide.

**Comment by Siumauricio** [comment]
we need more information, can you please check the logs?

do `docker service logs dokploy`

**Comment by Mr1Blaze** [comment]
May you give more information? 
Like Your VPS specs and VPS provider and some docker logs

**Comment by nexmoe** [comment]
> we need more information, can you please check the logs?
> 
> do `docker service logs dokploy`
> 
> One thing that could happen is:
> 
> If everything was fine, nothing should have happened, I think you probably ran out of space, if that happens you will get that error because you can not access the database because it is blocked due to lack of space. This happened to me yesterday

I checked and there is still enough remaining space.
The log is as follows, there is a problem with Redis.

```
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    | Error: getaddrinfo ENOTFOUND dokploy-redis
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |     at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:128:17) {
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |   errno: -3008,
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |   code: 'ENOTFOUND',
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |   syscall: 'getaddrinfo',
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    |   hostname: 'dokploy-redis'
dokploy.1.o6eb41s3xx4r@iZhp31wvaixopopstwow7tZ    | }
```

**Comment by nexmoe** [comment]
> May you give more information? Like Your VPS specs and VPS provider and some docker logs

2 Core(vCPU)
2 GiB

**Comment by Siumauricio** [comment]
@nexmoe can you try to do docker service scale dokploy=0 and then run docker service scale dokploy=1

**Comment by nexmoe** [comment]
> @nexmoe can you try to do docker service scale dokploy=0 and then run docker service scale dokploy=1
I tried, but it didn't work

**Comment by Mr1Blaze** [comment]
In logs I see that migrations was not done. I will check manual commands to do with docker terminal

**Comment by Siumauricio** [comment]
@nexmoe 

1. what vps provider are you using? 
2. can you try to run `docker service ls`

**Comment by nexmoe** [comment]
> @nexmoe
> 
> 1. what vps provider are you using?
> 2. can you try to run `docker service ls`

Aliyun

```
root@iZhp31wvaixopopstwow7tZ:~# docker service ls
ID             NAME                         MODE         REPLICAS   IMAGE                               PORTS
p6k5xxnd7rno   capture-website-api-07b711   replicated   2/2        robvanderleek/capture-website-api   
qcb16p2yj0fy   dokploy                      replicated   1/1        dokploy/dokploy:latest              
6eqw1m6oihwi   dokploy-postgres             replicated   1/1        postgres:16                         *:30000->5432/tcp
r4g55l2wh7ey   dokploy-redis                replicated   1/1        redis:7                             *:30001->6379/tcp
z63t1z9sazvl   dokploy-registry             replicated   1/1        registry:2.8.3                      
tktywg3wx0cr   dokploy-traefik              replicated   1/1        traefik:v2.5      
```

**Comment by Siumauricio** [comment]
Quite strange, since you mention that dokploy was working and you deployed several services with dokploy, what I find strange is that dokploy tries to connect through the hostname that docker assigns to each container, example to connect from dokploy to redis the connection would be dokploy-redis because this is the name assigned by docker, however I see that you can not even connect to the database, and is not fixed or restarting the service which is very strange because in all cases we have had that error has been solved by restarting it.

try running this:

1. `dokploy service rm dokploy dokploy-traefik dokploy-redis dokploy-postgres`
2.  Run this:
```bash
docker service create \
  --name dokploy \
  --replicas 1 \
  --network dokploy-network \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
  --publish published=3000,target=3000,mode=host \
  --update-parallelism 1 \
  --update-order stop-first \
  dokploy/dokploy:latest
  ```

**Comment by nexmoe** [comment]
> Quite strange, since you mention that dokploy was working and you deployed several services with dokploy, what I find strange is that dokploy tries to connect through the hostname that docker assigns to each container, example to connect from dokploy to redis the connection would be dokploy-redis because this is the name assigned by docker, however I see that you can not even connect to the database, and is not fixed or restarting the service which is very strange because in all cases we have had that error has been solved by restarting it.
> 
> try running this:
> 
> 1. `dokploy service rm dokploy dokploy-traefik dokploy-redis dokploy-postgres`
> 2. Run this:
> 
> ```shell
> docker service create \
>   --name dokploy \
>   --replicas 1 \
>   --network dokploy-network \
>   --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
>   --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
>   --publish published=3000,target=3000,mode=host \
>   --update-parallelism 1 \
>   --update-order stop-first \
>   dokploy/dokploy:latest
> ```

It didn't work, it may be a problem with the network.

**Comment by nexmoe** [comment]
```
root@iZhp31wvaixopopstwow7tZ:~# docker network ls
NETWORK ID     NAME                    DRIVER    SCOPE
65ce300899f1   bridge                  bridge    local
c2fe30a73344   docker_gwbridge         bridge    local
k12s94prcebw   dokploy-network         overlay   swarm
66ba28545d9b   host                    host      local
yj9o8ax1evj0   ingress                 overlay   swarm
6f36addcc12b   none                    null      local
c824f5959b35   rsshub-39f7a3_default   bridge    local

```

**Comment by Siumauricio** [comment]
Did this work for you before and then you got these errors?

Related #42

**Comment by nexmoe** [comment]
> Did this work for you before and then you got these errors?
> 
> Related #42

Worked for many days

**Comment by hubingkang** [comment]
I have the same problem, Is it because China can't pull docker hub?  before was good, I only pulled dokploy, will there be dependency problem?

**Comment by hubingkang** [comment]
docker service rm dokploy dokploy-traefik dokploy-redis dokploy-postgres

This works for me

**Comment by Siumauricio** [comment]
I have several servers with dokploy installed for a couple of months and I haven't had any problems, I don't know if the vps provider changed or did something to their vps because suddenly it doesn't work, it's something like internally in some configuration regarding the hostname resolution changed magically, which is strange.

 I honestly don't know what else to try, could you try to create another vps and run the installation script and see if it works?

**Comment by Siumauricio** [comment]
I don't know if this problem is coming from the network because as far as I see it is from china probably there are some restrictions so it is difficult to precede what is the main problem there. 

If the problem persists and you know how to reproduce it do not hesitate to open another issue, in this case I would suggest using a more secure and reliable provider such as digitalocean or hetzner.

**Comment by hubingkang** [comment]
> docker service rm dokploy dokploy-traefik dokploy-redis dokploy-postgresdocker 服务 rm dokploy dokploy-traefik dokploy-redis dokploy-postgres
> 
> This works for me这对我有用

Apart from dokploy, we also need to pull the images postgres:16, redis:7, and traefik
.5 to the Alibaba Cloud VPS.

**Comment by jynzo94** [comment]
In my case was the disk space. Everything just crashed.
Just when you build with docker it does not clean itself so your disk memory is full.

**This will fix your issue**: `docker system prune -a`

**You can also check "Daily docker clean"  in settings->server.**

Other usefull commands: 

- check linux disk report `df -h` 
- check docker usage `docker system df`

**Comment by one-matrix** [comment]
i have the same problem， case some time build，my  vps is 2 Core(vCPU) 4 GiB 80GB disk .  not beacase of the df  full.I'm confused. Every time I reboot the machine.

**Comment by jayxd-com** [comment]
## ⚡Fixed: How to Resolve 500/502 Errors on Dokploy

If you're encountering a 400 error on your Dokploy domain and are unable to access the dashboard, follow these steps:

1. **Scale the Dokploy Service:**
   ```
   docker service scale dokploy=0
   # Then
   docker service scale dokploy=1
   ```
   This will restart the Dokploy service and should restore access to your dashboard.

2. **Clear Unused Docker Images:**
   ```
   docker system prune -a
   ```
   This can free up a significant amount of space (for me, it cleared 40GB).

---

### 💡Walkthrough/Explanation

I was experiencing a 400 error on my Dokploy domain, and while my public sites were still accessible, I couldn't open the Dokploy dashboard. I had SSH access to the console from my local machine and saw that my Hetzner Dashboard was showing 400% CPU usage, even though I only had 5-6 active users on the public sites. A hard restart of my VPS didn’t resolve the issue.

After looking through the Dokploy documentation, I found a section about **common database connection issues**. My logs were similar to what was described, so I decided to try the following steps:

1. **Clear Unused Docker Images:**  
   I ran `docker system prune -a` to free up space. It cleared 40GB, but this didn't immediately fix the 400 error.

   ```
   docker system prune -a
   ```

2. **Restart Traefik:**  
   I tried restarting the Traefik service with the following command:
   
   ```
   docker restart dokploy-traefik
   ```
   However, this didn’t solve the problem either.

3. **Scale the Dokploy Service:**  
   Following the advice from the docs, I scaled the Dokploy service down to `0` and then back to `1`. This resolved the issue, and I was able to quickly access the Dokploy dashboard.

   ```
   docker service scale dokploy=0
   # Then
   docker service scale dokploy=1
   ```

After these steps, all my public sites remained accessible, and the issue with accessing the dashboard was resolved. 🛠️❤️

For more information, refer to the official Dokploy troubleshooting documentation: [Dokploy Troubleshooting Guide](https://docs.dokploy.com/docs/core/troubleshooting).

**Comment by Tomilola-ng** [comment]
God bless you @jayxd-com

**Comment by mahmoud-mohsen-dev** [comment]
Thanks, @jayxd-com — this worked for me.
