### ISSUE TITLE
When Cloudflare's CDN is enabled, the second project displays a 404 error. The issue is resolved when the CDN is disabled.

### ISSUE THREAD

**Issue by 2lifetop** [Dokploy/dokploy#157]
### To Reproduce

Enable Cloudflare's CDN.
Access the second project.
Observe that a 404 error is displayed.
Disable the Cloudflare CDN.
Access the second project again.
Observe that the project can be accessed normally.

### Current vs. Expected behavior

Actual Behavior:
With Cloudflare CDN enabled, the second project displays a 404 error.

Expected Behavior:
The second project should be accessible with Cloudflare CDN enabled, without any 404 errors.

### Provide environment information

```bash
OS:Debian 12
Version: 0.2.2
Browser: Chrome 126.0.6478.62
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
what happens is that you probably have activated the generation of SSL by cloudflare is not a bug, you have 2 options

1. Generate certificates by cloudflare
2. Generate certificates in dokploy with letsencrypt

If you want to choose the first option you do not have to change anything in cloudflare only that when you create a domain in any application make sure in the certificate select None and disable HTTPS.

If you choose the 2nd option you have to do the following go to your domain in cloudflare and go to the SSL/TLS section and you have to activate this option by default it comes in flexible change it to strict, and when you create a domain in dokploy make sure you use letsencrypt and HTTPS toggle.

If for any reason you see that something is not working simply restart traefik in settings.

![Screenshot 2024-06-22 at 8 49 36 AM](https://github.com/Dokploy/dokploy/assets/47042324/9a5b34ae-2b08-4601-bd36-e62c524c0137)

**Comment by Siumauricio** [comment]
If you have doubts or the problem persists, please feel free to open the issue again.
