### ISSUE TITLE
Database backup won’t stop after deleting it

### ISSUE THREAD

**Issue by iamkennethapp** [Dokploy/dokploy#160]
### To Reproduce

1 create an s3 destination 
2 create a database service
3 create a database backup for the service
3 delete the backup 

### Current vs. Expected behavior

When you delete the backup entry under the database service I expect the backup cron to stop but when I go to my R2 bucket I see that the backup happens every hour because that was the frequency I used. 

Before that the reason I deleted it was because the backup came as empty and didn’t have any database entries even though my database had content

### Provide environment information

```bash
Os ubuntu 24.04
Database image is mysql8
```

### Which area(s) are affected? (Select all that apply)

Databases

**Comment by Siumauricio** [comment]
Hi, I have followed the same steps and without success, everything seems to work fine, the backups stop once I delete the backup or deactivate it, regarding the backup that has no data, are you sure you checked the file, I added a table and a couple of data and the information is in the backup.

I wait for a few backups with cron * * * * * and it works fine, after that I deleted and you can see no more backups there
![Screenshot 2024-06-23 at 8 19 01 PM](https://github.com/Dokploy/dokploy/assets/47042324/d6e922b6-890a-4c30-83a8-9cce70bc035f)

The data I inserted
![Screenshot 2024-06-23 at 8 16 51 PM](https://github.com/Dokploy/dokploy/assets/47042324/f3c4f1bc-7b3d-49d4-8ebc-d97e2fb0ce7a)

**Comment by Siumauricio** [comment]
Since 1 week has passed and there has been no response, I assume that it is working well, if you can provide a video would be really helpfull to see
