### ISSUE TITLE
Invalid password set after creating a redis database

### ISSUE THREAD

**Issue by hubingkang** [Dokploy/dokploy#167]
### To Reproduce

1. create a redis database
2. set a password|
3. set External Port (Internet)
4. the password is not required to connect to redis from the outside. Using "default" and the password will not work

### Current vs. Expected behavior

redis must connect using password

### Provide environment information

```bash
redis:7

dokploy version: 0.2.4
```

### Which area(s) are affected? (Select all that apply)

Databases

**Comment by Siumauricio** [comment]
Thank you for reporting this, the issue is already fixed and will be available in the next version
