### ISSUE TITLE
dokploy not responding

### ISSUE THREAD

**Issue by mouayed-keziz** [Dokploy/dokploy#181]
### To Reproduce

after deploying dokploy to an ubuntu-s-1vcpu-1gb droplet (digital ocean), ive managed to deploy my postgres database and it works, 

when deploying my express js application with docker compose, the moment i hit deploy, dokploy stops responding and i need to restart the server to make it work again, 

its not necessary to put my dockerfile and docker compose file here but here r both

- Dockerfile
```
RUN npm install

COPY . .

RUN npm run build

#Production stage
FROM node:16-alpine AS production

WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

CMD ["node", "dist/index.js"]
```

- docker-compose.prod.yml
```yml
version: "3.7"
services:
  api:
    build:
      context: .
      target: production

    ports:
      - 5000:5000
```

note : before trying to deploy the expressjs application, i tried to deploy mysql which failed the same way i explain above, in the second try mysql worked perfectly, same for postgres, restarted the server again and again and its just not working with this express app, and it completely crashes dokploy (although the ram/disk/cpu usage is completely normal)

### Current vs. Expected behavior

dokploy crashes whenever i deploy my express app with docker compose

### Provide environment information

```bash
im using windows, but the issue here is related to a production environement, (digital ocean droplet, ubuntu 24, 1GB ram, 2vcpu, 20gb ssd storage)
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by Siumauricio** [comment]
This is not a dokploy bug, this is more the high ram consumption when building your project and as your machine doesn't have enough resources it crashes the server and therefore dokploy still doesn't get up.

I have tried to deploy multiple applications and I have experienced this problem when I have a server with very few resources, but once I increase them the problem goes away.

**Comment by Siumauricio** [comment]
as this is a docker problem, we can close this for now and the solution is to increase the resources of your server, dokploy itself consumes practically no resources so it is not a issue
