### ISSUE TITLE
ERR_EMPTY_RESPONSE on traefik domain [IPV6]

### ISSUE THREAD

**Issue by DemuraAIdev** [Dokploy/dokploy#190]
### To Reproduce

1. Create Project
2. Create Service
3. Using Template Pocketbase (its affect all services including Nextjs and more)
4. Deploy
5. Open generate domain by traefik

### Current vs. Expected behavior

After i do that i expect to show  website i deploy but show ERR_EMPTY_RESPONSE instad

![Cuplikan layar 2024-07-03 110107](https://github.com/Dokploy/dokploy/assets/71892583/690a900a-351b-4db0-b756-e71d2e67c753)

### Provide environment information

```bash
Operating System:
   OS: Ubuntu
   Arch: X64
Dokploy Version: 0.3.0
VPS Provider: Dihostingin
What application/services are you trying to deploy?
PocketBase
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Additional context

I using ipv6 it is affect?

**Comment by Siumauricio** [comment]
Well, I assume that the logs show that the image is working, I'm not sure if the traefik.me domains support ipv6 at the time of generation, because we generate the domains based on the IP that we saved when you created your instance, I imagine that your normal applications if you assign them a domain of yours if it works?

**Comment by DemuraAIdev** [comment]
the logs of image showing working, traefik logs showing this
```
time="2024-07-02T14:06:53Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-07-02T14:17:36Z" level=error msg="Unable to obtain ACME certificate for domains \"cyber-ai-pocketbase-647bb4-98-142-245-14.traefik.me\": unable to generate a certificate for the domains [cyber-ai-pocketbase-647bb4-98-142-245-14.traefik.me]: error: one or more domains had a problem:\n[cyber-ai-pocketbase-647bb4-98-142-245-14.traefik.me] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 98.142.245.14: Fetching http://cyber-ai-pocketbase-647bb4-98-142-245-14.traefik.me/.well-known/acme-challenge/nq_SBGM7-7uEDaFoDziWuXwqr-iQjgqXlY_UQ1bd6qE: Error getting validation data\n" rule="Host(`cyber-ai-pocketbase-647bb4-98-142-245-14.traefik.me`)" providerName=letsencrypt.acme routerName=websecure-cyber-ai-pocketbase-e8
```

**Comment by Siumauricio** [comment]
I mean, if you use your own domain does it work or not?

because using the domains generated by traefik.me I don't know if they work for ipv6, I think https://sslip.io/ does have ipv6 support.

**Comment by DemuraAIdev** [comment]
how can i use my own domain?

**Comment by DemuraAIdev** [comment]
![Cuplikan layar 2024-07-07 003114](https://github.com/Dokploy/dokploy/assets/71892583/2a32e9fc-a84f-4b6f-9bc6-02dee98c1fde)
hmmm why the IP show diffrent, its show ipv4 instad of ipv6?

**Comment by DemuraAIdev** [comment]
> I mean, if you use your own domain does it work or not?
how can i do that, in pocketbase its not show domain other than generated traefik

**Comment by Siumauricio** [comment]
Excellent, as I mentioned maybe it is a limitation of traefik.me domains, I will try to replicate this in a ipv6 server
