### ISSUE TITLE
Include Typebot in Dokploy Templates

### ISSUE THREAD

**Issue by gyancarlodasilva** [Dokploy/dokploy#195]
### What problem will this feature address?

Right now, Dokploy doesn't have a template for deploying Typebot, a great tool for creating interactive bots. Users who want to self-host Typebot have to set everything up manually, which can be time-consuming and complicated, especially if you're not very familiar with Docker.

### Describe the solution you'd like

It would be fantastic to have a template in Dokploy for Typebot. This template should include all the necessary configurations for deploying Typebot with Docker, making the process quick and easy for everyone. Additionally, please set the DEFAULT_WORKSPACE_PLAN environment variable to UNLIMITED by default. This ensures that the default plan for the admin user is set to UNLIMITED, simplifying the setup process.

### Describe alternatives you've considered

Users can follow the Typebot self-hosting guide to set it up manually. However, this can be a bit tricky and requires some Docker knowledge.

### Additional context

Adding Typebot to Dokploy templates would make the tool more versatile and helpful for users who need interactive bots. Here’s the [link to Typebot’s self-hosting documentation](https://docs.typebot.io/self-hosting/deploy/docker) for more information.

**Comment by freidev** [comment]
Here is a pull request about this https://github.com/Dokploy/dokploy/pull/380 @gyancarlodasilva
