### ISSUE TITLE
Docs: Compare to Dokku

### ISSUE THREAD

**Issue by elimisteve** [Dokploy/dokploy#2]
See https://github.com/dokku/dokku , thanks!

**Comment by muhammetsahin** [comment]
https://github.com/caprover/caprover

**Comment by jontstaz** [comment]
What about Coolify? How does it compare? Thats what I'm using and imo it looks the most similar to this app out of all the alternatives I've seen.

**Comment by ehmatthes** [comment]
Maybe it could be mentioned that Dokku is actually open source (MIT), while dokploy is absolutely [not open source](https://github.com/Dokploy/dokploy/discussions/3) under the current "license"?

**Comment by Siumauricio** [comment]
Hey I added a simple comparison between dokploy and caprover, coolify and dokku,  if you think something is wrong or is missing something, please make a PR to make a correction , I did the comparison based on my investigation, Thanks.

https://docs.dokploy.com/extra/comparison

**Comment by noahstreller** [comment]
> Hey I added a simple comparison between dokploy and caprover, coolify and dokku, if you think something is wrong or is missing something, please make a PR to make a correction , I did the comparison based on my investigation, Thanks.
> 
> https://docs.dokploy.com/extra/comparison

This was apparently moved to https://docs.dokploy.com/en/docs/core/extra/comparison

**Comment by aleclarson** [comment]
@Siumauricio Coolify now has monitoring: https://coolify.io/docs/knowledge-base/monitoring/
