### ISSUE TITLE
Feature: Categorize Templates for Improved UX

### ISSUE THREAD

**Issue by ciocan** [Dokploy/dokploy#202]
### What problem will this feature address?

Currently, our templates are presented in a single, extensive list. As this list expands, it becomes increasingly challenging to navigate and utilize effectively.

### Describe the solution you'd like

Simplify template selection by grouping them into logical categories. This will make our template library more usable as it expands.

### Describe alternatives you've considered

Filter by tags might be a solution

**Comment by Siumauricio** [comment]
I think here we could add some multi select or something like that and fill it with all the possible tags that are in the array of template information.
