### ISSUE TITLE
Cluster (Docker Swarm Worker Replication) Not Working on Ipv6

### ISSUE THREAD

**Issue by DemuraAIdev** [Dokploy/dokploy#203]
### To Reproduce

1. create application
2. using git provider for get nextjs apps
3. set replication 1 and registry (DockerHub)
4. Deploy
5. See Logs In Swarm Worker VPS (systemctl status docker)

https://hasteb.in/GZiij4Ah54UAyNg (log)

### Current vs. Expected behavior

i expect to work and container succesfully to pull

### Provide environment information

```bash
Operating System:
   OS: Ubuntu
   Arch: X64
Dokploy Version: 0.3.0
VPS Provider: Dihostingin
What application/services are you trying to deploy?
NextJS
```

### Which area(s) are affected? (Select all that apply)

Docker

### Additional context

im using ipv6

**Comment by Siumauricio** [comment]
Hi, Questions:

1. Does the logs of your application show that it is running?
2. I would also like to know what you want to achieve to understand more?

**Comment by DemuraAIdev** [comment]
1. THe logs show thats container **Exited**
2. I want that container assign to run at node worker, but the worker node failed and give that bounch of error

**Comment by Siumauricio** [comment]
Unfortunately I don't have ipv6 on my network, so testing this properly is not possible at the moment, a bit sad not to be able to help you.

**Comment by Mr1Blaze** [comment]
I will test with ipv6 in next future because now I don't have a lot time. Please wait it. Thank you!

**Comment by Siumauricio** [comment]
Well since IPV6 is not as well supported and not as mature as ipv4, we could close this issue, 

Related: https://github.com/moby/moby/issues/24379.
https://github.com/moby/moby/issues/24379#issuecomment-357480199
