### ISSUE TITLE
Every time I create a server on Hetzner, it does not work after restart

### ISSUE THREAD

**Issue by JohnMunsch** [Dokploy/dokploy#210]
## Create a server
- Ashburn, VA
- Ubuntu 24.04
- Shared vCPU
    - x86 (Intel/AMD)
- CPX11
- Networking
    - Public IPv4
    - Public IPv6
- SSH keys
    - (I used my Personal Public Key)
- Name
    - (I used the default provided)

## After the server came up
- I installed via the normal command: curl -sSL https://dokploy.com/install.sh | sh
- Once it came up I connected and signed in but did not create any applications or anything else
- I did a `/sbin/shutdown -r now` within the server, I *did not* power off the server from the Hetzner UI.

## After restart
- Once it came up, I refreshed the Dokploy UI and got a "400 oops, something went wrong" screen from Dokploy
- Trying to go to the home page did redirect me to the `/register` path automatically but still had the "400 oops" page

### Current vs. Expected behavior

I expected to see the home page for Dokploy but saw the 400 error instead and my attempt to go to the login page had the same result.

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 24.04
  Arch: Intel/AMD
Dokploy version: 0.3.2 (though I saw the same result with older versions too)
VPS Provider: Hetzner
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

I tried the same sequence with the lowest cost box on Digital Ocean but did not have the same thing happen even though it was the same version of Ubuntu on Intel.

**Comment by Mr1Blaze** [comment]
Can you share some docker logs ?

**Comment by Siumauricio** [comment]
Thanks for the detailed steps, in the next release this will be solved and all dokploy services will start automatically whether the system is rebooted or there is a crash.
