### ISSUE TITLE
Clarify error message for naming validation in `AppName` (`application`, `database`, and `compose`)

### ISSUE THREAD

**Issue by eremannisto** [Dokploy/dokploy#214]
### What problem will this feature address?

The current error message displayed when naming your `application`, `database`, or `compose` in `AppName` is misleading. It does not clearly communicate that **only lowercase letters** are supported. Updating the error message to explicitly state “lowercase letters” will improve user understanding.

### Describe the solution you'd like

The current error message for naming validation in `AppName` should be updated to state that **only lowercase letters** are supported explicitly. The new error message should be clear and concise, applying to naming **applications**, **databases**, and **compose items**. Here is the proposed change:

**Current Error Message:**
```tsx
.regex(/^[a-z](?!.*--)([a-z0-9-]*[a-z])?$/, {
    message:
        "App name supports letters, numbers, '-' and can only start and end with letters, and does not support continuous '-'",
})
```

**Proposed New Error Message:**
```tsx
.regex(/^[a-z](?!.*--)([a-z0-9-]*[a-z])?$/, {
    message:
        "App name supports lowercase letters, numbers, '-', can only start and end with letters, and does not support continuous '-'",
})
```

The same should be done in:
- `add-application.tsx`
- `add-compose.tsx`
- `add-database.tsx`

### Describe alternatives you've considered

1. **Providing a tooltip or help icon**: While this could help, it adds an extra step for users to find the information. **A clear error message is more direct and user-friendly**.

**Comment by Siumauricio** [comment]
Close in #215
