### ISSUE TITLE
Domains for services created via template

### ISSUE THREAD

**Issue by brickpop** [Dokploy/dokploy#216]
### What problem will this feature address?

Creating a service via a Template
- Traefik labels are being populated on Docker Compose file
- However, the Domains tab doesn't appear
- Even if the Docker compose labels for Traefik are set up, the service doesn't seem to be exposed

Instead, creating a Docker service with the same Docker image URL works just fine

### Describe the solution you'd like

- Add the Domains pane to template services
- Add the same Advanced sections as standard Applications get
- Ensure that template services are published via HTTP/s

### Describe alternatives you've considered

Manual Docker compose settings didn't work. Tried this https://docs.dokploy.com/en/docs/core/docker-compose/domains#step-1-add-the-network

**Comment by Siumauricio** [comment]
1. When you create a template it automatically generate the domains:
![image](https://github.com/user-attachments/assets/e3a5b917-68c4-4f4d-ae5d-ffddde9fa799)
2. The advanced features will not fit in docker compose since in docker compose we handle all the services in a single file, which in application is basically a single entity or just 1 service so that's why we can map some funcionalities like ports, redirects, volumes etc
3. By default all the templates are served with traefik.me domains which are http, if you want to have https use your own domain https://docs.dokploy.com/en/docs/core/docker-compose/domains or check this video https://www.youtube.com/watch?v=3qr_celxISA&t=1s, at the end is the same but of course you will need to convert or add more or less traefik labels to each service to fit in to your needs, but to add your own domain is the same for every service of docker compose so with that guide will be enough for probably most cases

**Comment by brickpop** [comment]
Thank you for your response @Siumauricio 

- Regarding the Domains behaviour, it would be great to have a consistent behaviour between apps, even if the domains tab was read-only
  - It may get confusing to see sometimes the "Domains" dropdown menu (from your screenshot), and sometimes the Domains tab
- Likewise with the Advanced tab
  - Having a (read-only) list of the volumes being used on a docker compose project would be very helpful. Now it leads to think that the service has no volumes
  - Same with ports, see what is exposed or mapped

Regarding the example video, it seems to be loading the files from a git repository. In my case, I am testing Docker compose by manually copying the docker-compose.yaml file to run a well known service. 
For some reason (still investigating) the Traefik subdomain is not being picked by LetsEncrypt, no certificate and visiting the URL returns a 404 Not found.

Thank you!

**Comment by brickpop** [comment]
I understand, and appreciate the huge work behind Dokploy

1) How about querying from Docker itself, rather than trying to figure out what the docker-compose file has?

```sh
docker container ls --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}" -a
# or
docker inspect -f "{{ .Mounts }}" <container-id>
```

---
I have an unrelated issue (probably should open a separate one)
When I try to use a web hook to trigger a redeploy:
- The given api/deploy/xxx URL returns `{"message":"Application Not Deployable"}` even if the app is running fine
- Clicking the reload button next to it shows an unrelated warning: `Are you absolutely sure? This action cannot be undone. This will permanently delete the domain`

Thank you!

**Comment by Siumauricio** [comment]
I like that idea to parse the config of the inspect command, let's add this as roadmap I can extract alot of interesting things with this!

Regarding to this:

> The given api/deploy/xxx URL returns {"message":"Application Not Deployable"} even if the app is running fine

I think you don't have activated the AutoDeploy toggle
![image](https://github.com/user-attachments/assets/c4ce42ac-6c38-40f7-a395-fe32b017e203)

> Clicking the reload button next to it shows an unrelated warning: Are you absolutely sure? This action cannot be undone. This will permanently delete the domain

Yeah I check and the text is incorrect

Altought I guess you are using github provider? if so you don't need to use the webhooks anymore, autodeploys are enabled by default

**Comment by brickpop** [comment]
That's very helpful, thank you :)

I'd like to suggest a few potential improvements:
- The "autodeploy" button could be more easily understood a checkbox on the app's settings tab.
- It could be enabled by default, as this is the expectation for any git-driven PaaS. 
- The `Application Not Deployable` JSON response might also become clearer as `Automatic deployments are disabled for this application`
- The web hook link dshould be hidden if autodeploy is disabled. Or at least show it grayed out, or maybe with a warning next to it.

Regarding the Domains topic, it would be very helpful if the domain/port HTTP proxy could be used on every type of container. 
- This shouldn't be an issue regarding Docker. You inspect the processes running within a given Docker Service, and allow to map a given domain to a given docker host + port. 
- Expecting people to discover that an env var named like `SOMETHING_HOST` will enable LetsEncrypt on some projects may result in more questions like the one I opened here.
- And also, having a separate way to do the same (Advanced > Domains) is another invitation for people to open more issues here

I hope that some of these ideas might ben helpful, thanks for suck a cool project ✨

**Comment by Siumauricio** [comment]
Thanks for the suggestions, appreciated!

1. Autodeploy will be enabled in the next update by default.
2. We will change the webhook messages

Can you give more details about the domains?

I think I will also work on integrating the domains in docker compose in a way that is quite friendly and similar to the applications.

**Comment by brickpop** [comment]
@Siumauricio sorry for the delay in replying

Trying to speak as a user advocate here ;)
In general, users shouldn't need to care about the internal design of the tool they are using. For example, simple apps behaving differently that Docker compose wrappers. Also, needing to define a `xxx_HOST` env var (in some cases) to set domains, etc.

My suggestion was to make the existing `Advanced > Domains` tab available for all types of projects (app, docker compose, etc)
- For standard apps, keeping what already exists
- For Docker Compose driven projects:
  - Listing the running hosts of the service
  - Showing them in a dropdown
  - Allowing to map a domain to one of the listed hosts + an internal port

Any other details I can help with?
