### ISSUE TITLE
Update default CNB builder image to `heroku/builder:24`

### ISSUE THREAD

**Issue by edmorley** [Dokploy/dokploy#220]
### What problem will this feature address?

We (Heroku) released `heroku/builder:24`, our new CNB builder image version based upon Ubuntu 24.04 LTS, in June:
https://github.com/heroku/buildpacks/discussions/12
https://github.com/heroku/cnb-builder-images#available-images

Currently this project uses the older Heroku CNB builder image, `heroku/builder:22`:
https://github.com/Dokploy/dokploy/blob/7bc6d0777d497cb09c14f89de13f6a3586fcd463/server/utils/builders/heroku.ts#L21-L22

### Describe the solution you'd like

It would be great to update the default CNB builder image to `heroku/builder:24`.

### Describe alternatives you've considered

-

### Additional context

The `heroku/builder:24` builder is now a multi-architecture image (AMD64 + ARM64), and offers smaller run image sizes thanks to dropping unnecessary build-time dependencies from the run image. The list of included buildpacks (and their versions) is identical between `heroku/builder:22` and `heroku/builder:24`. 

For more information on the differences between the two images, see:
https://devcenter.heroku.com/articles/heroku-24-stack#what-s-new
https://devcenter.heroku.com/articles/heroku-24-stack#upgrade-notes
https://devcenter.heroku.com/articles/stack-packages

**Comment by Siumauricio** [comment]
Hi @edmorley, thank you very much for the notice, we definitely had this problem that in arm architectures did not work, I didn't know that they had already released a new version that corrected this problem, I will add to my priority requests

Thank you
