### ISSUE TITLE
Should trafik be automatically configured for docker compose?

### ISSUE THREAD

**Issue by DemoMacro** [Dokploy/dokploy#223]
### What problem will this feature address?

My docker compose is automatically deployed via git, and I realise that this doesn't seem to make it possible to easily configure trafik routing and domains.

### Describe the solution you'd like

I think the deployment of compose should be as simple and easy as application.

### Describe alternatives you've considered

coolify is also auto-configured.

**Comment by Siumauricio** [comment]
Duplicate #216, Please see the comments to understand more why this is not implemented yet, and probably for now we will not implement this until I have a good idea and cover alot of cases
