### ISSUE TITLE
2 Factor Authentication

### ISSUE THREAD

**Issue by benbristow** [Dokploy/dokploy#225]
### What problem will this feature address?

Security, exposing a web panel without this seems dangerous.

### Describe the solution you'd like

TOTP (Authy, Google 2FA etc.) style authentication

### Describe alternatives you've considered

N/A

**Comment by channchetra** [comment]
You can find 2FA feature in Setting => Profile you will see Enable 2FA on top right of Setting page.

**Comment by benbristow** [comment]
Oh, I'm an idiot, thanks!
