### ISSUE TITLE
Add Support for Environment Variables During Dockerfile Build Process in Dokploy

### ISSUE THREAD

**Issue by valentingavran** [Dokploy/dokploy#227]
### What problem will this feature address?

Currently, Dokploy provides environment variables only to the final Docker image, but they should also be available during the build phase for the Dockerfile

### Describe the solution you'd like

The already available environment variables should be available during the Docker build process to the Dockerfile as well as to the final Docker image.

### Describe alternatives you've considered

I've considered committing a .env file to the repository, but this is not a secure option. Another workaround could be to manually pass the environment variables during the Docker build command, but this is not ideal for automated deployment processes.

**Comment by Siumauricio** [comment]
Hi @valentingavran ,

I guess this apply only when using Dockerfile as a build type right?, Because In the rest of Builders we pass all the envs

**Comment by valentingavran** [comment]
@Siumauricio Exactly. This only applies to Dockerfiles as a build type. I forgot to mention that

**Comment by predragnikolic** [comment]
Are you sure that it is available for Nixpacks build type? 
I think that env variables are not passed in that case.

I am getting the following error in the logs:
```
#13 [stage-0  9/11] RUN --mount=type=cache,id=lySJ2FpJ1kU-node_modules/cache,target=/app/node_modules/.cache npm run build
#13 0.422 npm WARN config production Use `--omit=dev` instead.
#13 0.472 
#13 0.472 > npm-workspace-monorepo@0.0.0 build
#13 0.472 > npm run build --workspaces --if-present
#13 0.472 
#13 0.758 npm WARN config production Use `--omit=dev` instead.
#13 0.838 
#13 0.838 > app-admin@0.0.0 build
#13 0.838 > tsc && vite build
#13 0.838 
#13 10.12 Invalid environment variables:
#13 10.13 [31merror during build:
#13 10.13 ZodError: [
#13 10.13   {
#13 10.13     "code": "invalid_type",
#13 10.13     "expected": "string",
#13 10.13     "received": "undefined",
#13 10.13     "path": [
#13 10.13       "VITE_SENTRY_DNS"
#13 10.13     ],
#13 10.13     "message": "Required"
#13 10.13   },
#13 10.13   {
#13 10.13     "code": "invalid_type",
#13 10.13     "expected": "string",
#13 10.13     "received": "undefined",
#13 10.13     "path": [
#13 10.13       "VITE_SENTRY_AUTH_TOKEN"
#13 10.13     ],
#13 10.13     "message": "Required"
#13 10.13   },
#13 10.13   {
#13 10.13     "code": "invalid_type",
#13 10.13     "expected": "string",
#13 10.13     "received": "undefined",
#13 10.13     "path": [
#13 10.13       "VITE_SENTRY_ORG"
#13 10.13     ],
#13 10.13     "message": "Required"
#13 10.13   },
#13 10.13   {
#13 10.13     "code": "invalid_type",
#13 10.13     "expected": "string",
#13 10.13     "received": "undefined",
#13 10.13     "path": [
#13 10.13       "VITE_SENTRY_PROJECT"
#13 10.13     ],
#13 10.13     "message": "Required"
#13 10.13   }
```
The reason why I see this message is that I have env variable validation.

I do not see this message if I choose `Heroku Buildpacks`.
