### ISSUE TITLE
Static Deployments

### ISSUE THREAD

**Issue by DarkPhoenix2704** [Dokploy/dokploy#233]
### What problem will this feature address?

I want to deploy some plain old html, css, js files without any buildstep. I tried with all the runtime, nothing seems to work

### Describe the solution you'd like

Ability to deploy a static website

### Describe alternatives you've considered

https://github.com/vercel/serve

**Comment by Siumauricio** [comment]
Nixpacks Staticfile Reference: https://nixpacks.com/docs/providers/staticfile

**Comment by DarkPhoenix2704** [comment]
Fixed

**Comment by ma-abaspour** [comment]
If anyone gets bad gateway in traefik link, change the port to 80.
Source: https://github.com/Dokploy/dokploy/discussions/471

**Comment by jimhouserock** [comment]
> If anyone gets bad gateway in traefik link, change the port to 80. Source: [#471](https://github.com/Dokploy/dokploy/discussions/471)

thank you very muchhhhhh!  more than two hours trying to fix this.  was pulling my hair out.
