### ISSUE TITLE
My program consistently gets stuck in the "Running" state during deployment.

### ISSUE THREAD

**Issue by revealGJW** [Dokploy/dokploy#235]
### To Reproduce

Create an application with GitHub provider
Use the default Nixpacks build type.
Click deploy.

### Current vs. Expected behavior

Error that occurs:
There's a chance that the deployment will remain stuck in the "Running" state indefinitely. After a few minutes, a new deployment will automatically start. This new deployment may also get stuck in the "Running" state. At this point, the service cannot be redeployed.

![image](https://github.com/user-attachments/assets/6c971e1d-8fce-4d2a-9972-1d200ff74b53)
![image](https://github.com/user-attachments/assets/d6de2b0f-aa40-47d4-b204-ff20d53adab8)

the part of running deploy's log:
Build nixpacks: ✅
Source Type: github: ✅

╔════════════ Nixpacks v1.24.4 ════════════╗
║ setup      │ nodejs_18, npm-9_x, openssl ║
║──────────────────────────────────────────║
║ install    │ npm ci                      ║
║──────────────────────────────────────────║
║ build      │ npm run build               ║
║──────────────────────────────────────────║
║ start      │ npm run start               ║
╚══════════════════════════════════════════╝

#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.57kB done
#1 DONE 0.0s

#2 [internal] load metadata for ghcr.io/railwayapp/nixpacks:ubuntu-1719273805
#2 DONE 1.7s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [stage-0  1/10] FROM ghcr.io/railwayapp/nixpacks:ubuntu-1719273805@sha256:b634eaa9c80812aee0bc469883ab00c3189b830e769467391e8530fbe6fb2b88
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 57.05MB 1.7s done
#5 DONE 1.7s

#6 [stage-0  2/10] WORKDIR /app/
#6 CACHED

#7 [stage-0  3/10] COPY .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix
#7 CACHED

#8 [stage-0  4/10] RUN nix-env -if .nixpacks/nixpkgs-bdd2f439c62aa0b8aa97f5c784a965c23f968fe6.nix && nix-collect-garbage -d
#8 CACHED

#9 [stage-0  5/10] COPY . /app/.
#9 DONE 1.0s

#10 [stage-0  6/10] RUN --mount=type=cache,id=3HhZI4Z6qM-/root/npm,target=/root/.npm npm ci
#10 1.379 npm WARN config production Use `--omit=dev` instead.
#10 25.55 npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
#10 26.70 npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
#10 26.79 npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
#10 27.45 npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
#10 28.12 npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
#10 28.20 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#10 28.20 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#10 28.20 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#10 28.20 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#10 28.21 npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
#10 29.16 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
#10 29.60 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

### Provide environment information

```bash
OS:Debian-12.0_x64 2C4G
dokploy version:Version: v0.3.1
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
Hi @revealGJW,  Quesions

1. What VPS Provider are you using?
2. What are the specs of the machine?
3. Have you had VPS freezes?

**Comment by revealGJW** [comment]
1. The VPS provider I'm using is based in Hong Kong. 
2. As for the specs of my machine, it has 2 CPUs, 4GB of RAM, and 30GB SSD storage. 
3. Regarding VPS freezes, I have indeed experienced instances where the VPS becomes unresponsive, particularly during build processes. During these times, the CPU utilization reaches 100%.

Here is some VPS metrics:
CPU:
<img width="779" alt="image" src="https://github.com/user-attachments/assets/002dbf09-bedf-4293-b39d-77791f2a420e">


Disk IO:
<img width="783" alt="image" src="https://github.com/user-attachments/assets/91987bbf-a02c-4657-bd6d-db34bad5011c">


Memory available:
<img width="733" alt="image" src="https://github.com/user-attachments/assets/faf2f963-34b6-4567-b5ce-5aca4b46f309">


Network (Color Green is Input):
<img width="766" alt="image" src="https://github.com/user-attachments/assets/833268ea-6810-4a31-94ad-32920b057e48">

**Comment by Siumauricio** [comment]
I understand, unfortunately this is not an issue that we handle because there can be many reasons.

1. If Your provider does not provide you with an optimized VPS which can cause it to be slow.
2. Builders like nixpacks consume a lot of ram just to build the project, although even docker building a project consumes a lot of ram.
3. According to the graph it seems to indicate that dokploy is really optimized, so this problem is due to the 2 reasons I mentioned above.

What I would suggest you to avoid these problems, because really running the applications is not the heavy task, the heavy thing is to build the project, an alternative that I would give you would be to build your project in a CI/CD from github and push to a registry and in dokploy you can use that registry to simply download it and run it and you avoid to be building the project in the VPS, or another solution could be increase your resources to avoid this issue.

**Comment by Siumauricio** [comment]
Duplicate #85
