### ISSUE TITLE
Feat: Global SSH Keys for git provider

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#255]
### What problem will this feature address?

At the moment, every service needs an SSH Key. This is what is most likely going to happen with just 5/6 repos:

<img width="805" alt="image" src="https://github.com/user-attachments/assets/b06fd3b5-bde2-4054-b3b0-447f4d7fc81e">

### Describe the solution you'd like

- Create a new SSH Keys view under _/dashboard/settings/server_
- Associate an SSH Key to multiple services

### Describe alternatives you've considered

.

### Additional context

@Siumauricio As usual, I'd like to work on that. Let me know!

**Comment by Siumauricio** [comment]
Sounds like a good idea, I think we could merge this idea with #98 To be able to reuse source providers

**Comment by lorenzomigliorero** [comment]
Umh, perhaps they can be developed independently?
You can select an SSH Key in the Provider view or associate an SSH Key to a reusable git provider.

Also, what is the benefit of creating a git provider rather than just associating an SSH Key? Fetching the repositories list would be a nice addition, but it changes depending on the provider's APIs, so it's more work.

**Comment by Siumauricio** [comment]
@lorenzomigliorero Ok, can you detail what will be the implementation and the workflow of this? just to understand more the integration

**Comment by lorenzomigliorero** [comment]
Sure! Here is how I'm imagining this working:

**UX**

Under _/dashboard/settings/server_, there will be another view, SSH Keys.
The view will be like this:

<img width="852" alt="image" src="https://github.com/user-attachments/assets/750c64dd-4c54-489f-982e-35c464612f95">

- In the project view, by clicking the Lock icon, you'll be able to select an SSH key or generate a new one.

**DB**

A new _sshKey_ table will be created with these fields:
```ts
sshKeyId: z.string(),
key: z.string().min(1),
name: z.string().min(1),
```

The application schema will have one relationship with the SSH Key:
```ts
customGitSSHKey: one(sshKey) 
```

When we'll support reusable git providers, it's enough to add a one one relationship with _sshKey_ to the _provider_ table.

**Comment by Siumauricio** [comment]
Sounds good the implementation makes sense @lorenzomigliorero, you are free to do this, thanks!
