### ISSUE TITLE
Traefik certificate provisioning fails when acme.json has permissions 777

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#259]
### To Reproduce

1. Create a service and enable HTTPS
2. Open the HTTPS url
3. The page says NET::ERR_CERT_AUTHORITY_INVALID

### Current vs. Expected behavior

Current: `/etc/dokploy/traefik/dynamic/acme.json` with permission 777 makes Traefik certificate provisioning fails
Expected: `/etc/dokploy/traefik/dynamic/acme.json` should have permission 600

### Provide environment information

OS: Ubuntu 24.04 LTS 
Dokploy: Version: v0.4.0
VPS Provider: Hetzner

### Which area(s) are affected? (Select all that apply)

Traefik

### Additional context

Traefik logs:
```
 level=error msg="The ACME resolver \"letsencrypt\" is skipped from the resolvers list because: unable to get ACME account: permissions 777 for /etc/dokploy/traefik/dynamic/acme.json are too open, please use 600"
 ``` 
 
 https://github.com/Dokploy/dokploy/blob/canary/docker/prod.sh#L60

**Comment by lorenzomigliorero** [comment]
@Siumauricio any news on this? It should be pretty simple to fix.

**Comment by Siumauricio** [comment]
@lorenzomigliorero Yes, initially everything will be 777, but once the dokploy server starts it will change to 600.
![Screenshot 2024-07-25 at 9 38 42 AM](https://github.com/user-attachments/assets/d9eab504-8559-4455-ab9b-c1b6e68056e3)
