### ISSUE TITLE
Allow Custom Advertise Address for Docker Swarm Initialization in Installation Script

### ISSUE THREAD

**Issue by binaryYuki** [Dokploy/dokploy#266]
### What problem will this feature address?

Enhance the Dokploy installation script to allow specifying a custom advertise address for Docker Swarm initialization.

Currently, the Dokploy installation script automatically determines the advertise address for Docker Swarm using the external IP address fetched from an external service (ifconfig.me). This can be problematic in internal network environments where security and address management are critical.

### Describe the solution you'd like

Modify the installation script to accept an optional parameter for the advertise address. This allows administrators to specify a known, trusted internal address, improving security and flexibility in various network environments.

```sh
advertise_addr=""
if [ "$1" ]; then
  advertise_addr=$1
else
  advertise_addr=$(curl -s ifconfig.me)
fi
```

Check for an optional parameter for the advertise address.
Use the provided parameter if available, otherwise default to the current behavior (using ifconfig.me).
This feature will help secure internal deployments and provide more control over Docker Swarm setups.

### Describe alternatives you've considered

Enhanced Security: Avoids exposing internal infrastructure to external address lookups, reducing potential security risks.
Greater Flexibility: Administrators can configure the Docker Swarm advertise address to fit specific network configurations and requirements.
Improved Control: Ensures that the Docker Swarm manager uses a predetermined and controlled address, facilitating better network management and troubleshooting.

**Comment by Siumauricio** [comment]
I think this case is precisely covered in the manual installation section https://docs.dokploy.com/en/docs/core/get-started/manual-installation, you can modify the script to your liking, I do not do this because docker swarm to work with the workers and manager needs a public IP, not the local one, otherwise it will not work.

**Comment by binaryYuki** [comment]
Hi @Siumauricio,

Thank you for your opinion!

Actually, Docker Swarm does not require public IP addresses for managers and workers to function properly. Docker Swarm can operate over private networks, using internal IP addresses for communication between manager and worker nodes.

Ref: [Docker Docs](https://docs.docker.com/reference/cli/docker/swarm/join/#--advertise-addr-value)

Another reason I raise this issue is that the script will prefer an IPv6 address rather than IPv4 automatically, which may cause connection issues. IPv6 addresses can sometimes lead to unexpected behaviour or connectivity problems if the network infrastructure is not fully compatible or properly configured for IPv6 (especially when other nodes will join after setting-up). This can result in nodes failing to communicate effectively, leading to potential downtime or disruption of services.

If maintaining the current setup is better, let's close this issue as guidance for others.

Thank you for your efforts!

**Comment by Siumauricio** [comment]
@binaryYuki 

>  Thank you for your opinion!
> 
> Actually, Docker Swarm does not require public IP addresses for managers and workers to function properly. Docker Swarm can operate over private networks, using internal IP addresses for communication between manager and worker nodes.
> 
> Ref: [Docker Docs](https://docs.docker.com/reference/cli/docker/swarm/join/#--advertise-addr-value)

Correct, but in the majority of the cases the people should expect to work with ip publics rather than private, even in a few versions ago we was working with localhost `Custom Advertise Address` and this was the main reasson of Cluster didn't work for any way, so that's the reasson we decided to switch to use the public IP

> Another reason I raise this issue is that the script will prefer an IPv6 address rather than IPv4 automatically, which may cause connection issues. IPv6 addresses can sometimes lead to unexpected behaviour or connectivity problems if the network infrastructure is not fully compatible or properly configured for IPv6 (especially when other nodes will join after setting-up). This can result in nodes failing to communicate effectively, leading to potential downtime or disruption of services.

Regarding the installation script you are right, IPV6 is a headache to work with, usually you have unexpected results including me, there is even an open issue #258 about  using IPV4 first and then try IPV6, but in the case that someone want to use a custom advertise address they should reference to manual installation

**Comment by binaryYuki** [comment]
Hello @Siumauricio,

That sounds very convincing!

I will close this issue as completed and hope this can help someone who has the same question.

And by the way, can we add these to the docs? I can PR if this sounds great to you.

**Comment by Siumauricio** [comment]
Sounds good @binaryYuki !

Docs Repo: https://github.com/Dokploy/docs

**Comment by maelp** [comment]
Is there a way to easily change IP addresses after initialization? I've been running on a machine with ephemeral IP address, and when I added a (new) static address, it broke all the config, and there was no clear documentation on how to update everything?

**Comment by Siumauricio** [comment]
@maelp If I am not wrong, you cannot change the IP of docker swarm just like that, first you would have to do a `docker swarm leave --force` but this would bring down all your services, so you can't really do that and it is not a problem of dokploy but rather how docker works, someone already asked that question you can read here https://forums.docker.com/t/migrate-docker-swarm-to-new-ip-net/93779

**Comment by maelp** [comment]
Nice thanks! Perhaps we can add his solution to the doc for people who have this question?
