### ISSUE TITLE
Feature - Implement Email Resend Functionality on Build Failure

### ISSUE THREAD

**Issue by freidev** [Dokploy/dokploy#27]
As part of the continuous improvement of Dokploy, I propose the implementation of a new feature that allows sending a notification email when a build fails in the process. This email resend mechanism will be useful to keep me, the developers, and the team immediately informed about any critical errors in the build process.

**Tasks:**
1. Develop the Email Resend Logic: Create the necessary logic to detect a build error and trigger the sending of a notification email.
2. Integrate with Dokploy's Build System: Ensure that the email resend functionality is properly integrated with Dokploy's current build system.
3. Email Template Configuration: Design and configure clear and concise email templates to notify about build errors.

**Benefits:**
1. Improved detection and notification of build errors.
2. Increased transparency and communication within the development team.
3. Reduced response time to critical issues in the build process.

**Comment by abdelrahman-essawy** [comment]
sounds good, but can we make this feature as notification channels ?
for example sending Email OR/AND Slack message on build success/failed.

**Comment by miguelvictor** [comment]
Discord webhooks would be great too since our company already left Slack for Discord 😅

**Comment by 190km** [comment]
An option to choose discord or slack would be to have several ways to configure, either by mail, discord or slack or simply all 3.

**Comment by Siumauricio** [comment]
Thanks for your suggestions, this will be the next feature I will be working on!
