### ISSUE TITLE
Error in Lightsail

### ISSUE THREAD

**Issue by gmautner** [Dokploy/dokploy#28]
Hello,

Installed according to the docs in AWS Lightsail on Ubuntu 20.04.

The admin page over the public IP and port 3000 shows the message:
An error occurred on client
The page you are looking was not found

(It is somehow hidden, the page appears blank but if you select with the mouse this message gets highlighted)

I noticed that, at the same time the page was hit, the postgres docker container issues this error in its log:

2024-05-02 23:51:03.500 UTC [73] ERROR:  relation "admin" does not exist at character 261
2024-05-02 23:51:03.500 UTC [73] STATEMENT:  select "adminId", "githubAppId", "githubAppName", "serverIp", "certificateType", "host", "githubClientId", "githubClientSecret", "githubInstallationId", "githubPrivateKey", "letsEncryptEmail", "sshPrivateKey", "enableDockerCleanup", "authId", "createdAt" from "admin" "admins" limit $1

**Comment by Siumauricio** [comment]
It looks like migration didn't apply succesfully.

can you please try this: 


1. docker service scale dokploy=0 
2. docker service scale dokploy=1
And then try to visit the the web app after 15 seconds?

 
Also if you can me the logs of this commands: 

1. docker service ls 
2. docker ps

**Comment by Siumauricio** [comment]
@gmautner 

Ok, I tried on 2 different instances of lightsail.

In the cheapest option of $5 it literally sucks, it is too slow without having installed anything, I tried installing it and it is too slow, I would not recommend this option.

I tried the $12 option using the Ubuntu 20.04 image, and did the following

1. go to your aws lightsail instance -> networking -> allow ports 3000, 443, 80 in the firewall rules
2. log in to your server through ssh.
3. run `sudo su`
4. run ` curl -sSL https://dokploy.com/install.sh | sh`
5. that's all and then wait a few seconds and go to the server-ip:3000 in your browser

**Comment by gmautner** [comment]
> It looks like migration didn't apply succesfully.
> 
> can you please try this:
> 
> 1. docker service scale dokploy=0
> 2. docker service scale dokploy=1
>    And then try to visit the the web app after 15 seconds?
> 
> Also if you can pass me the logs of this commands:
> 
> 1. docker service ls
> 2. docker ps

This solved it. Thanks.

**Comment by Siumauricio** [comment]
Nice!
