### ISSUE TITLE
Feat: Swarm overview

### ISSUE THREAD

**Issue by daniiba** [Dokploy/dokploy#281]
### What problem will this feature address?

I would like the see on which nodes my apps are currently running. Also It would be great to have monitoring for the worker nodes aswell.

### Describe the solution you'd like

Tab for swarm, that shows this information.

### Describe alternatives you've considered

-

**Comment by Siumauricio** [comment]
Hi @daniiba sounds good idea, let's add to the roadmap!

**Comment by ErickLuis00** [comment]
> Hi @daniiba sounds good idea, let's add to the roadmap!

This feature is essential when using swarm and replicas, it is not possible to know anything about the replicas currently. It's as if they don't exist, as only the containers on the current node where Dokploy is installed appear.
