### ISSUE TITLE
Add option to revert dokploy version & Opt in based auto updates

### ISSUE THREAD

**Issue by samuel-108** [Dokploy/dokploy#282]
### What problem will this feature address?

I am frustrated that automatic deployment (while reloading) of the dokploy instance caused all of my services to no longer work. 

As the newer version introduced shared SSH feature (which did not have support for multiple users), this broke every service that had been configured. 

![Screenshot 2024-07-29 at 12 37 12 PM](https://github.com/user-attachments/assets/6353b2f3-ca2b-4684-99aa-0d859114fe0c)

This caused the new version of dokploy to be installed

### Describe the solution you'd like

- Opt In based auto deployment (Those who want will opt in; for those that don't make it manual trigger) or opt out
- Warning if breaking changes has been introduced during a new update
- Rollback to old dokploy version, if the newer version crashed things

### Describe alternatives you've considered

None; as in the new update, non admin users are 3rd class citizen for adding private repos.

**Comment by Siumauricio** [comment]
Hi I am sorry for what you had, although I think you should have read the notes, explicitly before upgrading we give a warning that to prevent something from breaking, read the notes and we give the steps you have to take to do the migration which is quite simple for this case, what we can add is to add a permission for users to access the SSH Keys tab.
![image](https://github.com/user-attachments/assets/3575c1a8-4c92-4f32-aea1-175d5d5591af)

**Comment by samuel-108** [comment]
No I understand what you mean, but I did not go via that UI to update my server.

Going back would not be possible right now that I understand as I did try docker service rollback manually, which made me realize this. 

What I do mean was adding a feature to do so in the future directly from the UI so that if needed we can go back a version and the migrations can be reverted (up migration -> down migrations).

**Comment by samuel-108** [comment]
Please do note that I did not trigger update via the update button at all. All I did was reload the server, which cuased the update to happen automatically. 

I believe since the dokploy:latest is being used, it must have fetched the latest image. Maybe tagging it to a specific version, say 0.5.0 and during update fetching the latest version and updating the image in use would be better??

**Comment by samuel-108** [comment]
As I shared above this is what caused the update, not me going to the update tab and pressing on update button.

![image](https://github.com/user-attachments/assets/0be8fde3-ee4c-45f0-a4a4-4fd06b4406d4)

the version was updated when I reloaded the service

**Comment by samuel-108** [comment]
The reload option on the server button. It was this that caused the update. Which I believe was not something that was intended of the button.

**Comment by samuel-108** [comment]
Also in regards to the permission, would it be possible to limit the keys they can access as well. Currently only admin can access that page. But giving users access to all keys or no keys seems limiting.

_PS: Thank you for the product. Dokploy is a great software.._

**Comment by Siumauricio** [comment]
I added a new access for SSH Keys, and also added a validation to prevent update dokploy when you click the reload button
