### ISSUE TITLE
Feat: Dashboard External Link Icon to a domain

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#288]
### What problem will this feature address?

<img width="451" alt="image" src="https://github.com/user-attachments/assets/b28f1756-825d-408f-a6dc-1b5392a52aed">

By clicking on this icon, you enter the project rather than open the application domain in another tab.
I found it quite confusing, and it'd be nice to jump directly to one of the domain.

### Describe the solution you'd like

We need a new flag in the domain model to detect which domain is open from the dashboard.

<img width="680" alt="Screenshot 2024-07-29 at 18 21 18" src="https://github.com/user-attachments/assets/28e0fed1-6afc-43cd-8ea1-98915b6e745f">

A project can have only one domain attached to the external link icon.

### Describe alternatives you've considered

No alternatives

**Comment by Siumauricio** [comment]
Hmmm I am planning to integrate the same domain scheme to docker compose, I am thinking in the future I don't know how good an idea it would be to do this.

**Comment by lorenzomigliorero** [comment]
Docker compose projects can work the same way—there is no difference.
If there are multiple domains, you can select the main one.

If you want to avoid touching the schema, I suggest some alternatives.

**In case the project has only one domain (99% of cases):**
- The icon is linked to this domain

**In case the project has more than one domain:**
- By clicking on the icon, you select the domain to open

I found it frustrating having to click 4 times before opening the domain.
And we already have an icon perfectly placed for it!

Let me know, I can open a PR! I think is a nice addition!

**Comment by Siumauricio** [comment]
This was previously done I guess in the  https://github.com/Dokploy/dokploy/pull/524
