### ISSUE TITLE
Upgrade Traefik to its latest version

### ISSUE THREAD

**Issue by Flo4604** [Dokploy/dokploy#289]
### What problem will this feature address?

I would like to use traefik plugins via just proving their git location, this is currently not possible in traefik 2.5.

### Describe the solution you'd like

Upgrade dockploy to support the current latest traefik version.

### Describe alternatives you've considered

-

**Comment by Siumauricio** [comment]
Hi, it would be a good idea to migrate to traefik v3, I think we can plan it in a couple of releases because we have to test a lot of things to avoid breaking them.
