### ISSUE TITLE
Static project with build phase

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#294]
### What problem will this feature address?

I have several node repositories that generate a static output (dist or public folder) using a build command. However, Dokploy doesn’t support this scenario at the moment.

[Nixpacks static-file provider](https://nixpacks.com/docs/providers/staticfile) only works if the static output is already present; it doesn’t allow for an additional build command.

Coolify provides a specific flag for that:

<img width="744" alt="image" src="https://github.com/user-attachments/assets/e94bf419-e7f6-4fd2-85bb-bf53f410faff">

### Describe the solution you'd like

Similar to Coolify, we should add an “Is it a static site?” flag when the buildpack is Nixpacks. Here’s how it should work:

1.	When the “Is it a static site?” flag is enabled, you should be able to customize the publish directory.
2.	The Nixpacks build runs as usual.
3.	After the Nixpacks build is complete, a Dockerfile is created with a simple NGINX web server pointing to the publish directory.

.Dockerfile
```Dockerfile
FROM nginx:alpine
WORKDIR /usr/share/nginx/html/
COPY --from=${application.publish_directory} .
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
```

nginx.conf
```nginx
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri.html $uri/index.html $uri/ /index.html =404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

### Additional context

Another advantage of using NGINX is that it eliminates the need for a Node server in create-react-app repositories. Node servers are typically more memory-intensive compared to a standard NGINX web server.

@Siumauricio I'd like to work on this, I'm just waiting for your thumbs up.

**Comment by Siumauricio** [comment]
Sounds like a very good idea, we would just add a flag to determine if it is a static site?

**Comment by lorenzomigliorero** [comment]
Yes, and we also need a flag to determine the publishDirectory.

**Comment by pipuwong** [comment]
Hi, 请问，Dokploy 如何设置nginx 的配置 ？
我通过Dokploy 部署了一个静态网站，我还设计了404 的页面，但是在Dokploy 部署的网站，404 页面跳过去了nginx 的404而不是我设计的404。请问大佬知道这个如何解决吗？
<img width="489" alt="CleanShot 2024-12-01 at 00 34 48@2x" src="https://github.com/user-attachments/assets/31a1fd03-4063-4f62-be48-b29a9079e90a">

**Comment by pipuwong** [comment]
Hi, how does Dokploy set up the configuration of nginx?

I deployed a static website through Dokploy, and I also designed a 404 page, but on the website deployed by Dokploy, the 404 page skips to the nginx 404 instead of the 404 I designed. Does the boss know how to solve this?

**Comment by aitormunoz** [comment]
> Hi, how does Dokploy set up the configuration of nginx?
> 
> I deployed a static website through Dokploy, and I also designed a 404 page, but on the website deployed by Dokploy, the 404 page skips to the nginx 404 instead of the 404 I designed. Does the boss know how to solve this?

Hi! I had the same issue and ended up solving it by creating a custom Dockerfile with my own nginx.conf.
That way I could define the error_page 404 directive and serve my custom 404 page correctly instead of the default nginx one.

**Comment by djsisson** [comment]
nixpacks/railpacks already handle static sites by adding Caddy to the image, you can customise the caddyfile used by adding one to the root of your repo as well as alter the output dir if it's not detected

https://railpack.com/languages/node#static-sites
