### ISSUE TITLE
Add option to enable HTTP3 for Traefik

### ISSUE THREAD

**Issue by JonathanEkberg** [Dokploy/dokploy#295]
### What problem will this feature address?

From traefik version 3.0 and above [HTTP3 support ](https://doc.traefik.io/traefik/routing/entrypoints/#http3)is no longer experimental and is a feature I would like to use with Dokploy. I think it could work by adding buttons in the traefik actions dropdown menu to enable or disable HTTP3. [Similar to how traefik dashboard can be enabled/disabled](https://github.com/Dokploy/dokploy/pull/279).

![image](https://github.com/user-attachments/assets/2d8cdd98-7639-45d7-b2bc-43374c837ce6)

### Describe the solution you'd like

1. Add buttons in the Dokploy traefik server settings dropdown which enables/disables HTTP3 for the websecure traefik entrypoint in the static config.

traefik.yml
``` yml
entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'
    http3:
      advertisedPort: 443
    http:
      tls:
        certResolver: letsencrypt
```
2. Make the traefik container listen for both TCP **and** UDP on port 443 if HTTP3 enabled and only TCP otherwise.

### Describe alternatives you've considered

Could theoretically use nginx with http3 enabled as proxy for traefik but that would be impractical. 

### Additional context

I made a [fork ](https://github.com/JonathanEkberg/dokploy/commit/0eb575e53ed7e5f1ac1fa9b4dc9158c7549f7765)which enables HTTP3 but without ui to disable so it's always on and it seems to work. Dokploy [currently uses traefik v2.5](https://github.com/Dokploy/dokploy/blob/1e212d4e789794ea6493fbffe6ce205886b57712/apps/dokploy/server/setup/traefik-setup.ts#L15) which seems to have [HTTP3 as experimental support](https://github.com/traefik/traefik/releases/tag/v2.5.0) so updating to version 3.0 or above (which has HTTP3 as no longer experimental) might be necessary. Adding UDP on port 443 is because HTTP3 requires both TCP and UDP to work.

**Comment by Siumauricio** [comment]
Related #289

**Comment by Siumauricio** [comment]
Since v0.8.0 you can enable http3 manually, so I'm closing this.

**Comment by Fakerko** [comment]
> Since v0.8.0 you can enable http3 manually, so I'm closing this.

Your opinion that http/3 protocol can be turned on manually is ridiculous to me. So why can anything within Dokploy be turned off/on via the UI when it can be done manually?

For example, I'm not an experienced Traefik user, so an UI button to turn on/off the http/3 protocol would be appreciated.
