### ISSUE TITLE
Static buildtype

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#298]
### What problem will this feature address?

The current Nixpacks StaticFile provider generates images that are approximately 600MB in size, while they should ideally be around 50MB.

### Describe the solution you'd like

Once this [PR](https://github.com/Dokploy/dokploy/pull/297) is merged, I propose adding a new static build type. This new build type will use the [buildStatic](https://github.com/Dokploy/dokploy/blob/6ed379243ec3561f287923323dbbd83a2afb2925/apps/dokploy/server/utils/builders/static.ts) method to produce a much smaller and more efficient image based on nginx:alpine.

### Describe alternatives you've considered

Technically, you can achieve almost the same result by selecting Nixpacks and setting publishDirectory to /.
However, this approach results in the image being built twice unnecessarily.

**Comment by Siumauricio** [comment]
Okay only in this case you will not build any application, you will only get a publish directory right?

**Comment by lorenzomigliorero** [comment]
Yes correct. It will simply serve the directory with nginx. We need to merge [this](https://github.com/Dokploy/dokploy/pull/297/files#diff-288c8f3b12a83e27d5edb7987908322f106556e08d2cb73a52aa1562366cb4ff) first.
