### ISSUE TITLE
Exposing port has no effect

### ISSUE THREAD

**Issue by icebob** [Dokploy/dokploy#30]
Hello again,

I've started my own container which expose the port 3000 in the container. I would like to expose it as 3001 without domains.
I tried it within the Application Ports, but it has no effect any settings:

![image](https://github.com/Dokploy/dokploy/assets/306521/0431246f-e06a-456a-af44-9c56d103302d)

docker ps output:
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                                                                                                 NAMES
cf5170d050d9   registry.q:5000/qnet7:latest   "./bin/application-s…"   11 seconds ago   Up 9 seconds    3000/tcp, 4000/tcp, 8000/tcp                                                                                          app-generate-redundant-feed-poiep9.1.vkrlsh7w1g8pptyjcsz5wwq9e
```

May I have the wrong configuration somewhere?

Thanks in advance!

**Comment by Siumauricio** [comment]
Hey @icebob.

I tried the same config, and have you redeploy your app? in order to apply this changes is required to redeploy, i tested and is working now, maybe I should add a alert there when you add some port redeploy the app to take the effect!

**Comment by icebob** [comment]
Yes, I tried the redeploy, but it had no effect. However, yeah would be good a warning there,

Next week, I will try it again.

**Comment by Siumauricio** [comment]
@icebob another question are you deploying a custom docker registry?

**Comment by icebob** [comment]
I deployed a custom docker image from my registry.

**Comment by Siumauricio** [comment]
#29

**Comment by icebob** [comment]
It's different from #30.
In #30 I wanted to expose the Dokploy admin site port on different port instead of 3000.

In this ticket I wanted to expose the started app port to the host.

**Comment by ericaprieto** [comment]
Was this fixed? I'm also unable to map ports

**Comment by Siumauricio** [comment]
@ericaprieto Create a minimal reproduce example to test this
