### ISSUE TITLE
dokploy-postgres fails to start on install [Local Machine]

### ISSUE THREAD

**Issue by robinvalk** [Dokploy/dokploy#300]
### To Reproduce

When running the installer the postgres container fails to start.

### Current vs. Expected behavior

The dokploy-postgres container keeps restarting with the following message
```
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
```

Instead I'd expect it to start successfully and for the dokploy container to run the migrations against this contianer.

### Provide environment information

```bash
Postgresql's environment variables seem to be okay so I don't understand why it's complaining about the `POSTGRES_PASSWORD` environment variable.

docker service inspect dokploy-postgres
[
    {
        "ID": "nia860lh71ovtam53scp6ikci",
        "Version": {
            "Index": 708
        },
        "CreatedAt": "2024-07-31T19:23:05.838241106Z",
        "UpdatedAt": "2024-07-31T19:23:06.593322254Z",
        "Spec": {
            "Name": "dokploy-postgres",
            "Labels": {},
            "TaskTemplate": {
                "ContainerSpec": {
                    "Image": "postgres:16",
                    "Env": [
                        "POSTGRES_USER=dokploy",
                        "POSTGRES_DB=dokploy",
                        "POSTGRES_PASSWORD=amukds4wi9001583845717ad2"
                    ],
....
```
```


### Which area(s) are affected? (Select all that apply)

Installation

### Additional context

_No response_

**Comment by Siumauricio** [comment]
Hi @robinvalk, is this happening to you when installing it on a vps, or are you trying to run dokploy locally?

I just tried the install command on a server and it works without problems, could you give me more details of which provider you are using?

**Comment by robinvalk** [comment]
I'm trying to install it locally. I modified the install script from [here](https://docs.dokploy.com/en/docs/core/get-started/manual-installation) to use a private IP address to announce the swarm node and I updated the ports a bit. 

Script ran fine as it's just basic docker swarm. Docker container is created and the docker sock also works because the redis container get's spun up correctly. Theirs just something odd in the postgres initialisation. 

I checked the setup here: https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/server/setup/postgres-setup.ts#L50
Does it first initialise the service without any configuration and then afterwards it updates it with the correct environment variables? That might be an issue 🤔

**Comment by Mr1Blaze** [comment]
You try to install on windows?

**Comment by robinvalk** [comment]
Nope linux

**Comment by robinvalk** [comment]
> I'm trying to install it locally. I modified the install script from [here](https://docs.dokploy.com/en/docs/core/get-started/manual-installation) to use a private IP address to announce the swarm node and I updated the ports a bit.
> 
> Script ran fine as it's just basic docker swarm. Docker container is created and the docker sock also works because the redis container get's spun up correctly. There is just something odd in the postgres initialisation.
> 
> I checked the setup here: https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/server/setup/postgres-setup.ts#L50 Does it first initialise the service without any configuration and then afterwards it updates it with the correct environment variables? That might be an issue 🤔

Hmm I missed the catch block, so probably when it can't find the service it starts it with the correct configuration already: https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/server/setup/postgres-setup.ts#L59

When I try to do a `docker run` with a matching config the postgres container starts without any issue:
```
docker run --rm --name dokploy-postgres -e POSTGRES_PASSWORD=amukds4wi9001583845717ad2 -e POSTGRES_DB=dokploy -e POSTGRES_USER=dokploy postgres:16
```

**Comment by Siumauricio** [comment]
It's very strange, I don't know if somehow it's because you are installing it locally, but on a vps server it works fine.

**Comment by Mr1Blaze** [comment]
Can you tell more details about instalation or maybe some steps. I need more details to help you

**Comment by Siumauricio** [comment]
We suggest you to try in one of our recommended vps to avoid this kind of problems, we do not assure that doing it this way will work, so it is difficult to know what is the exact problem.
