### ISSUE TITLE
Fix: Containers are deleted when Dokploy Server Restart

### ISSUE THREAD

**Issue by lorenzomigliorero** [Dokploy/dokploy#306]
### To Reproduce

- Run `lsof -t -i:80 | xargs kill` to kill process on port 80
- Run `lsof -t -i:443 | xargs kill` to kill process on port 443
- Run `docker ps`, you should see all your containers
- Run `curl -sSL https://dokploy.com/canary.sh | sh`
- All your containers are deleted

### Current vs. Expected behavior

Containers should persist across updates

### Provide environment information

```bash
OS: Ubuntu 24
Dokploy version: canary (guess it's the same with the production version)
```

### Which area(s) are affected? (Select all that apply)

Installation, Application

### Additional context

I don't know if this happens only when you force a canary installation.

**Comment by lorenzomigliorero** [comment]
@Siumauricio still not fixed. you can replicate following the steps.

**Comment by Siumauricio** [comment]
I reboot the system and all the containers are succesfully restarted @lorenzomigliorero 
![Screenshot 2024-08-01 at 10 52 56 AM](https://github.com/user-attachments/assets/9f35b315-395b-4bc5-82dc-eaddc1f8b603)

**Comment by lorenzomigliorero** [comment]
Ok, so I suspect it happens only when you run install.sh or canary.sh. How can I install the latest canary without losing the containers?

**Comment by Siumauricio** [comment]
You need to redeploy them, if you have old containers which was deployed before the fix it will not start so you need to deploy again.

**Comment by lorenzomigliorero** [comment]
These are the steps I followed:

- `lsof -t -i:80 | xargs kill`
- `lsof -t -i:443 | xargs kill`
- `curl -sSL https://dokploy.com/canary.sh | sh`
- I deployed an application
- `lsof -t -i:80 | xargs kill`
- `lsof -t -i:443 | xargs kill`
- `docker ps` the deployed container is still there
- `curl -sSL https://dokploy.com/canary.sh | sh`
- Container is gone

Are you able to replicate it?

**Comment by Siumauricio** [comment]
That's fine the installation comand will make the docker swarm leave consequently it will cause all containers to be removed including dokploy and all containers, because in the installation command we do docker swarm leave --force so this will make all the containers being deleted

**Comment by lorenzomigliorero** [comment]
What will happen when Dokploy is updated through the updates button?
<img width="490" alt="image" src="https://github.com/user-attachments/assets/a9c1bbeb-f50d-44f9-ac73-9ee208a99a64">

**Comment by Siumauricio** [comment]
basically it will force the dokploy container to use the last downloaded image so it will do a forced restart.

**Comment by lorenzomigliorero** [comment]
And the deployed containers will persist, right?

**Comment by Siumauricio** [comment]
Correct, all the services will be normal

**Comment by lorenzomigliorero** [comment]
Thanks for clarifyng this!
