### ISSUE TITLE
Installation is stuck at [1/1: preparing]...

### ISSUE THREAD

**Issue by isaced** [Dokploy/dokploy#308]
### To Reproduce

exec `curl https://dokploy.com/install.sh > install.sh`

### Current vs. Expected behavior

```
Docker already installed
Node left the swarm.
Swarm initialized: current node (ip80x6q17a2azalgb2wbxpxox) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-58wbewlkkv6qa8pb524jt2g7fftk4p4t82txo9iabhiiz5rmz8-8vses5nw3k6pcjjtqczhgiq4w 8.130.25.130:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

Swarm initialized
r0788sc6gq3bhn94vj3qgzh4p
Network created
o27lm0hjr9riqemthryybpp3i
overall progress: 0 out of 1 tasks
overall progress: 0 out of 1 tasks
1/1: preparing [=================================>                 ]
```

### Provide environment information

```bash
Operating System:
  - OS: Alibaba Cloud Linux 3 (Compatible with RHEL/CentOS)
  - Arch: x86_64 
Dokploy version: v0.5.0
VPS Provider: Aliyun Cloud
```

### Which area(s) are affected? (Select all that apply)

Installation

### Additional context

I was able to install v0.3.3 before, but after uninstalling and reinstalling v0.5.0, I had a problem.

**Comment by Siumauricio** [comment]
Can you share the logs of docker service ls and docker service logs dokploy

**Comment by isaced** [comment]
It seems that the docker image was not pulled down successfully. I tried to manually pull the redis/traefik/postgres image and reinstall it, and then it worked.

**Comment by rafakwolf** [comment]
same issue here, even doing what you suggested, no success, docker service logs is attached.

[docker-service.txt](https://github.com/user-attachments/files/18925993/docker-service.txt)

**Comment by rafakwolf** [comment]
it looks like the VPS service I am using has a kernel without CONFIG_IPVLAN enabled, and it is not allowing me to install a new kernel.

**Comment by genpozi** [comment]
I felt the same thing and came here looking for answers.  While i was here, not watching it, it finished without me. I am trying hard not to be offended, but... you know.  As the FYI i needed.... it might sit on a step for quite some time.
