### ISSUE TITLE
Docs-Website: Error: `DialogClose` must be used within `Dialog`

### ISSUE THREAD

**Issue by structwafel** [Dokploy/dokploy#315]
### To Reproduce

1. Go to [https://docs.dokploy.com/en/docs/core/get-started/introduction](https://docs.dokploy.com/en/docs/core/get-started/introduction)
2. Click on the "search box" (Search), or press ctrl+k
![image](https://github.com/user-attachments/assets/2d9d780a-c64f-4ecc-ae1c-b897fda85fe6)

### Current vs. Expected behavior

should not error

### Provide environment information

```bash
-
```

### Which area(s) are affected? (Select all that apply)

Installation

**Comment by yayza** [comment]
I made a pull request https://github.com/Dokploy/docs/pull/18 for deps fix.

**Comment by Siumauricio** [comment]
@yayza The docs repo is deprecated, now we are using this repo to handle the website, docs and dokploy itself, can you please do the PR to this Repo please
