### ISSUE TITLE
Deploy Apps on other VPS

### ISSUE THREAD

**Issue by menjilx** [Dokploy/dokploy#32]
Hi, is it possible to add another "server" and deploy apps to this "server" but it will be managed under one dokploy dashboard? 

Thanks!

**Comment by therour** [comment]
I think there is already a feature request for this
https://github.com/Dokploy/dokploy/issues/1

**Comment by Siumauricio** [comment]
Currently not,  but there is a feature request for that, currently I have a feature branch to work on that.

We can close this issue since is duplicated!
