### ISSUE TITLE
Support for gitlab

### ISSUE THREAD

**Issue by ErSauravAdhikari** [Dokploy/dokploy#320]
### What problem will this feature address?

Similar to how github is supported it'd be great if there was some sort of support for gitlab.

### Describe the solution you'd like

Add support for gitlab

### Describe alternatives you've considered

Manual SSH key based private repo deployments

**Comment by Siumauricio** [comment]
Hi, this is a good idea,I will add it to the roadmap as I would like to work this with connecting multiple repositories. #98, also I want to see if it's possible to integrate the same with bitbucket

**Comment by Siumauricio** [comment]
Close #403
