### ISSUE TITLE
Add flexible www/non-www redirect option

### ISSUE THREAD

**Issue by axzilla** [Dokploy/dokploy#333]
### What problem will this feature address?

Currently, Dokploy does not offer a built-in option to automatically redirect between www and non-www versions of a domain. Users cannot easily set up this common user experience practice without technical expertise.

### Describe the solution you'd like

Add a simple option in the Dokploy dashboard that allows users to:

- Redirect www to non-www (e.g., [www.domain.com](http://www.domain.com/) to domain.com)
- Redirect non-www to www (e.g., domain.com to [www.domain.com](http://www.domain.com/))
- Disable redirection (keep both versions accessible)

### Describe alternatives you've considered

-

### Additional context

Many hosting platforms (like Vercel and Coolify) offer similar redirection features. Adding this to Dokploy would align with industry standards and improve user experience, especially for those without technical backgrounds.

**Comment by Siumauricio** [comment]
Sounds like a good idea, add presets in the redirects section, I will add this to the roadmap.

**Comment by tonyljx** [comment]
Hi, May I ask if it has been supported?

**Comment by b3nab** [comment]
Hello, yes it sounds like a good idea, but I'm wondering what kind of implementation is viable for the entire community?

In terms of feasibility, it should be simple. I just have some questions:
- Would something like a checkbox to flag inside the domain settings modal be enough?
- What about subdomains? Should they support the feature if flagged? E.g.: For some, it may sound strange to have a domain with both `www.subdomain.example.com` and `subdomain.example.com`, but for simplicity and consistency, we could leave it to users to decide and eventually also opt-in to add www to subdomains.

Besides from that I think it could be a little feature to start contributing. 👍 I can start that, what do you think @Siumauricio ?

**Comment by axzilla** [comment]
> Hello, yes it sounds like a good idea, but I'm wondering what kind of implementation is viable for the entire community?
> 
> In terms of feasibility, it should be simple. I just have some questions:
> 
> * Would something like a checkbox to flag inside the domain settings modal be enough?
> * What about subdomains? Should they support the feature if flagged? E.g.: For some, it may sound strange to have a domain with both `www.subdomain.example.com` and `subdomain.example.com`, but for simplicity and consistency, we could leave it to users to decide and eventually also opt-in to add www to subdomains.
> 
> Besides from that I think it could be a little feature to start contributing. 👍 I can start that, what do you think @Siumauricio ?

That's what Coolify does! Maybe that's a clue?

Image 1:
<img width="739" alt="Screenshot 2024-09-24 at 09 14 07" src="https://github.com/user-attachments/assets/6e3d3c69-d901-43a4-880c-5aabd5373e0f">

Image 2:
<img width="751" alt="Screenshot 2024-09-24 at 09 14 15" src="https://github.com/user-attachments/assets/74064254-4f12-40a9-bb43-eedddf95f447">

Image 3:
<img width="744" alt="Screenshot 2024-09-24 at 09 14 23" src="https://github.com/user-attachments/assets/a7fc7c30-cdc6-4b83-b597-671e8a161118">

**Comment by Siumauricio** [comment]
@b3nab Good idea, I prefer to have this option inside of Redirects section, I was thinking about this, have a select with some presets and then when you select one automatically fill the fields
![image](https://github.com/user-attachments/assets/e76e9f6a-ca60-4d11-b63c-25d8a1c32f9c)

**Comment by b3nab** [comment]
Yes sounds good. I created a new branch and started working on it.

Just one thing that maybe "Allow www & non-www." is not needed? Since basically is "no redirects".

**Comment by axzilla** [comment]
@Siumauricio Did you remove this feature again?

**Comment by talaikis** [comment]
Not supported on compose it seems

**Comment by axadrn** [comment]
> Not supported on compose it seems

@Siumauricio  Yep, we need that for compose too! Please reopen this issue!

**Comment by mmihalev** [comment]
So is this possible using compose?
