### ISSUE TITLE
Docs about how to add S3 storage (Backblaze especialy)

### ISSUE THREAD

**Issue by tristanremy** [Dokploy/dokploy#34]
I have an error when doing so, anyone could point me in the right direction ? Tried many things but always getting this error on request :
{error: {json: {message: "Error to connect to bucket", code: -32600,…}}}

**Comment by Siumauricio** [comment]
Hey probably you have something wrong I get work.

Follow this steps

1. Create a bucket in my make I made it public.
2. Go to application keys
3.  Add a new application key
4. just set a name key whatever, and with the default values click on `Create New Key`
5. The keyid is equivalent to accessKey and  Application Key is Secret Access Key
6. the region in my case was `us-west-002`
7. In endpoint please make sure to include the https://, if you pase this `s3.us-west-002.backblazeb2.com` it will throw an error make sure to put like this `https://s3.us-west-002.backblazeb2.com`

**Comment by Siumauricio** [comment]
Closing this issue since there are not bugs and the api is working. if you have any other bugs please feel free to open again.

**Comment by tristanremy** [comment]
Great, thank you so much for your help!
Not sure it's relevant, but maybe add some info in the fields label to help configure ? Especially the ones I had wrong :
- `https://` to start the Endpoint
- Bucket `name`
- Make the bucket public (seems obvious now, but didn't think about this one as I'm not used to work with those 😉)

Thanks for all the good work anyway, such an easy way to deploy something ! Hope I can help in the future !
