### ISSUE TITLE
Installation/start stuck

### ISSUE THREAD

**Issue by skhrlx** [Dokploy/dokploy#345]
### To Reproduce

I'm just modifying the ports inside the installation script (TRAEFIK_PORT and TRAEFIK_SSL_PORT) to 444 and 81 (which is not occupied)

### Current vs. Expected behavior

The script just get stuck at >> overall progress: 0 out of 1 tasks 1/1: ready (it loops between preparing and assigned & ready for infinite)

### Provide environment information

```bash
VPS Provider: Contabo
System OS: Ubuntu 22.04
Specs: 24GB RAM/1TB SSD NVME
```

### Which area(s) are affected? (Select all that apply)

Installation

**Comment by Siumauricio** [comment]
@skhrlx Please provide the script

**Comment by skhrlx** [comment]
> @skhrlx Please provide the script

[install script](https://github.com/user-attachments/files/16611735/install.txt)

**Comment by duylddev** [comment]
got the same issue in ubuntu 24

**Comment by duylddev** [comment]
default script

**Comment by duylddev** [comment]
![image](https://github.com/user-attachments/assets/d168eddd-aa95-43b4-bb5a-2141aca2bdff)

**Comment by Siumauricio** [comment]
I tested on a fresh hetzner vps server and is working fine, both cases, custom script and default script
<img width="629" alt="Screenshot 2024-08-14 at 2 39 48 PM" src="https://github.com/user-attachments/assets/85823c5b-c4d8-4196-8c77-a44302d062bb">

**Comment by Siumauricio** [comment]
@duylddev @skhrlx did you run the command on a fresh server or you already had docker installed?

**Comment by duylddev** [comment]
had Docker installed Docker version 24.0.5, build ced0996

**Comment by duylddev** [comment]
I've tried install Coolify and it said that
![image](https://github.com/user-attachments/assets/48cc28f6-5ec6-4f9b-981a-146431d98834)

might be the same issue?

**Comment by Siumauricio** [comment]
@duylddev that could be the issue, try on a fresh server first https://www.reddit.com/r/docker/comments/pzw7wi/why_am_i_getting_error_varlibdocker_readonly_file/

**Comment by duylddev** [comment]
I remove Docker 
and run the default script again
It works fine now

thanks a lot

**Comment by skhrlx** [comment]
> @duylddev @skhrlx did you run the command on a fresh server or you already had docker installed?

First time using docker, so, an fresh one

**Comment by Siumauricio** [comment]
I tested on a fresh contabo server an 0 issues
![Screenshot 2024-08-14 at 10 33 16 PM](https://github.com/user-attachments/assets/e2892479-57a7-4957-a485-1ce928ff05f5)
![Screenshot 2024-08-14 at 10 33 40 PM](https://github.com/user-attachments/assets/dfd42e2c-94ed-4051-b7ff-4504c15d25f9)

**Comment by olegasics** [comment]
Hello everyone
I have the same problem and I have this error message
I tried install default script
<img width="1401" alt="image" src="https://github.com/user-attachments/assets/1f95c0d9-5fec-4ce3-8a57-cdaca38a6759">

**Comment by FoPPi** [comment]
> ![image](https://private-user-images.githubusercontent.com/9783862/357986369-d168eddd-aa95-43b4-bb5a-2141aca2bdff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MjMyNjEsIm5iZiI6MTcyMzcyMjk2MSwicGF0aCI6Ii85NzgzODYyLzM1Nzk4NjM2OS1kMTY4ZWRkZC1hYTk1LTQzYjQtYmI1YS0yMTQxYWNhMmJkZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTVUMTE1NjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGIyZDQxNjg2ZWJlZjNjM2U2N2ViNWIyMTM2YjdjMjIxZWJmM2Y1N2QwNTMwNTZmZTY0MmZhMmQyYjFjYmRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7MLyNmLo6bY4WHAwEvSAjaczbLR_pbshmgciU9Qbw0E)

Problem in docker. I install Ubuntu server 24.02 and provide docker from installer and have the same problem. I fix it by give dokploy install docker

**Comment by Siumauricio** [comment]
I cannot reproduce this issue, if you have a video or steps to reproduce this I can try, but I tested with 2 providers and all is fine

**Comment by olegasics** [comment]
> I cannot reproduce this issue, if you have a video or steps to reproduce this I can try, but I tested with 2 providers and all is fine

Sorry, I reinstalled server and now it working
If I will meet this problem once more I will write to Discord channel

**Comment by Siumauricio** [comment]
If you have any video to see the problem on a new machine would be great, so far I tried it with 2 providers and everything works the same, we recommend not having docker installed to avoid any problems.

for now I will close this issue.

**Comment by Lolita1001** [comment]
I ran into the same problem while installing Dokploy inside a Proxmox LXC container.
The installer just kept looping with:
```
overall progress: 0 out of 1 tasks
1/1:
overall progress: 0 out of 1 tasks
```

When checking the service status with `docker service ps dokploy-postgres --no-trunc`, I found the actual error:

```
error during container init: open sysctl net.ipv4.ip_unprivileged_port_start:
permission denied
```

In my case the issue turned out to be AppArmor on the Proxmox side.
Docker Swarm inside an LXC container tries to touch some sysctl params, and AppArmor just blocks it, which causes the containers to never start properly.

What fixed it for me was setting the LXC container to use an unconfined AppArmor profile on the Proxmox host:

```
pct stop <CTID>
echo 'lxc.apparmor.profile: unconfined' >> /etc/pve/lxc/<CTID>.conf
pct start <CTID>
```

After that, I reran the installation and Dokploy finished without any issues.

For reference: Proxmox 8.x, Debian-based LXC, Docker 29.x, and nesting=1 was already enabled.
Hopefully this saves someone else a bit of time.

**Comment by kielnino** [comment]
I had the same error on my VPS. `docker service ps dokploy-postgres --no-trunc` gave me:

```
root@XXXX:~# docker service ps dokploy-postgres --no-trunc
ID                          NAME                     IMAGE                                                                                 NODE             DESIRED STATE   CURRENT STATE           ERROR                                                                                                                                                                                                                                                           PORTS
e74quitvxw6g7g59k7ldh1pgb   dokploy-postgres.1       postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417   XXXX   Ready           Ready 3 seconds ago                                                                                         
tenxewtc1wlyjfr6tl56siide    \_ dokploy-postgres.1   postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417   XXXX   Shutdown        Failed 4 seconds ago    "starting container failed: failed to set up container networking: error creating external connectivity network: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied: set environment variable DOCKER_IGNORE_BR_NETFILTER_ERROR=1 to ignore"
62p5fddlr6iwsowvepew5ba0z    \_ dokploy-postgres.1   postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417   XXXX   Shutdown        Failed 10 seconds ago   "starting container failed: failed to set up container networking: error creating external connectivity network: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied: set environment variable DOCKER_IGNORE_BR_NETFILTER_ERROR=1 to ignore"
o5bmshqlkrdf3et0udgznu4ab    \_ dokploy-postgres.1   postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417   XXXX   Shutdown        Failed 16 seconds ago   "starting container failed: failed to set up container networking: error creating external connectivity network: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied: set environment variable DOCKER_IGNORE_BR_NETFILTER_ERROR=1 to ignore"
vom33z6ctie96f73itaep5b13    \_ dokploy-postgres.1   postgres:16@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417   XXXX   Shutdown        Failed 22 seconds ago   "starting container failed: failed to set up container networking: error creating external connectivity network: open /proc/sys/net/bridge/bridge-nf-call-iptables: permission denied: set environment variable DOCKER_IGNORE_BR_NETFILTER_ERROR=1 to ignore"
```

I fixed it with:

```bash
mkdir -p /etc/systemd/system/docker.service.d
nano /etc/systemd/system/docker.service.d/override.conf
```
Adding to `override.conf`
```
[Service]
Environment="DOCKER_IGNORE_BR_NETFILTER_ERROR=1"
```
And finally:
```bash
systemctl daemon-reload
systemctl restart docker
```
