### ISSUE TITLE
Monitoring inconsistency 

### ISSUE THREAD

**Issue by bloor** [Dokploy/dokploy#347]
### To Reproduce

Fresh install

### Current vs. Expected behavior

While this is my Database instance monitoring graph:
Each 5min a heavy procedure is running, that shows as 100% cpu for 15s.
![image](https://github.com/user-attachments/assets/c00cebda-afa5-42a2-90de-35b49bdef5cf)

However.. as you can see on main graph, it is not showing any spikes.
This is my dokploy central monitoring
![image](https://github.com/user-attachments/assets/c9e0c3e4-fcf9-4a2c-96db-a462bcea2a95)

I suspect is not monitoring all cpu cores ?!
Because `htop` shows the spike, as 1 core bein fully utilized and it's either core 2 or core 3.
![image](https://github.com/user-attachments/assets/0b042cf1-3595-40e5-82da-0fc3245748e3)

### Provide environment information

```bash
Ubuntu 20.4
VPS Contabo: 4cores / 6GB / 200 SSD
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

Tested on VPS with latest Dokploy 0.6.2

**Comment by Siumauricio** [comment]
We use docker stats, which does the job of monitoring the container and its resources, I wouldn't be too sure to give you a concrete answer about this, the only thing you can try is to use docker stats in the terminal and see the usage and now compare what we have in dokploy to see if something is wrong

**Comment by Siumauricio** [comment]
I do not consider that this is really a bug, we use the main functionality provided by docker, which is `docker stats` so I would not have a specific solution for this case, for now I will close it since I do not know how to proceed.
