### ISSUE TITLE
Redirection Error

### ISSUE THREAD

**Issue by sutidor** [Dokploy/dokploy#349]
### To Reproduce

Create a dokploy deployment like in the video on a VPS and using cloudflare. Then setting up my own domain and configure to use letsencrypt for it.

### Current vs. Expected behavior

Infinite redirect error in the browser (tested multiple browsers)

Cause: I think it will double https: 1. cloudflare, 2. dokploy. But there is no way to deactivate the dokploy one without going full ssl-less.
Fix: Deactivate cloudflare proxy (unlike it was shown in the video)

### Provide environment information

```bash
used dokploy deploy script on fresh Ubuntu24
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Additional context

I tested with other DNS service, works fine. I tested with cloudflare proxy deactivated, works fine.

**Comment by muningis** [comment]
Indeed related with Cloudflare Proxy - however I've more apps running which are pointed to with Cloudflare proxy and they work fine.

However:
1. If I turned of Cloudflare Proxy'ing - I get traefik's `Bad Gateway`
2. there are couple differences between traefik configs from what I see.
3. Traefik fails to reload when trigerring it from dokploy interface

**Comment by Siumauricio** [comment]
I have tried to deploy multiple applications and without problems, if you say that it fails only in cloudflare and in other providers it works is more a problem of cloudflare than dokploy, probably you have to change the encryption mode of cloudflare, we mention in the documentation

https://docs.dokploy.com/en/docs/core/domain/certificates

duplicated #157
