### ISSUE TITLE
Start service again in Compose (no deploy)

### ISSUE THREAD

**Issue by FoPPi** [Dokploy/dokploy#351]
### What problem will this feature address?

Hello. I need a button to start some services without re-deploying them and losing all data. Hope You can make this) 

### Describe the solution you'd like

Add button in Deploy Settings.
![image](https://github.com/user-attachments/assets/6e5f42d5-7c8f-448f-b9d3-b77a0743e3ab)

### Describe alternatives you've considered

Add stop and delete buttons on the Docker tab. To delete containers
![image](https://github.com/user-attachments/assets/cfb9f1ad-fefa-4f4f-b33a-99fee0192943)

**Comment by predragnikolic** [comment]
A redeployment sould not cause data loss, at least that's what I as a end user expect.

Maybe it is a bug with the template of the service? 
What service are you using?

**Comment by FoPPi** [comment]
I found 1 thing. I can't run again in compose (I create Postgres DB by compose) but if u create a Database u can stop it. But problem the same, I can't run again in compose.

**Comment by Siumauricio** [comment]
Read the docs: https://docs.dokploy.com/en/docs/core/docker-compose/overview#advanced

We explain what you should do to persist the data between deployments when using volumes in docker compose

**Comment by FoPPi** [comment]
Thank You)
