### ISSUE TITLE
domains tab missing from templetes

### ISSUE THREAD

**Issue by dustinwloring1988** [Dokploy/dokploy#352]
### To Reproduce

Click and launch any templete

### Current vs. Expected behavior

When launching apps you have it but templetes you dont

### Provide environment information

```bash
Ubuntu 24
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

linode, ubuntu 24.04, 4vcpu

**Comment by Siumauricio** [comment]
This is not a bug, Duplicated #216
