### ISSUE TITLE
Domain Binding Form Does Not Accept Russian Domains and Punycode Domains

### ISSUE THREAD

**Issue by DenisVASI9** [Dokploy/dokploy#353]
### What problem will this feature address?

The domain binding form currently does not allow users to input and bind domains that are either in Russian (Cyrillic) script or in Punycode format. This limitation affects users who need to bind domains that are not in the standard Latin alphabet, specifically those with Cyrillic characters or those represented using Punycode.

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by Siumauricio** [comment]
lol I didn't know these domains exist, I will remove the validation so you can enter any hostname!
