### ISSUE TITLE
!Data lost while upgrade to Version: v0.7.0

### ISSUE THREAD

**Issue by binaryYuki** [Dokploy/dokploy#366]
### To Reproduce

check updates-update

### Current vs. Expected behavior

When you reopened the page, were asked to sign up again, and all your projects were missing, despite traefik.yaml still being in place.
<img width="1513" alt="截屏2024-08-20 00 38 56" src="https://github.com/user-attachments/assets/f07723e5-408a-4556-9501-701567820891">

### Provide environment information

```bash
Linux managera1 6.5.0-1026-oracle #26~22.04.1-Ubuntu SMP Mon Jun 24 14:22:18 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Which area(s) are affected? (Select all that apply)

Installation

**Comment by Siumauricio** [comment]
Hi, the only way your data will be lost is to delete the volume of the database, I have 3 instances running dokploy in v0.7.0 and all of them are fine, if you can provide steps to reproduce would be helpfull

**Comment by binaryYuki** [comment]
> Hi, the only way your data will be lost is to delete the volume of the database, I have 3 instances running dokploy in v0.7.0 and all of them are fine, if you can provide steps to reproduce would be helpfull

Hi，

Yes that‘s the case. I just check updates and update as usual. Nothing different from usual.

But there is one thing that warn me is it takes quite long for dokploy to restart, while their is a volume not found error raised by swarm.

```bash
root@managera1:/home/ubuntu# docker service ps animeapi-fastapi-045aef 
ID             NAME                            IMAGE                            NODE                     DESIRED STATE   CURRENT STATE            ERROR                              PORTS
ofm2ehxxm9uc   animeapi-fastapi-045aef.1       animeapi-fastapi-045aef:latest   workere2-2               Ready           Preparing 1 second ago                                      
tiblxwqdnaed    \_ animeapi-fastapi-045aef.1   animeapi-fastapi-045aef:latest   instance-20240718-1134   Ready           Rejected 1 second ago    "No such image: animeapi-fasta…"   
8jxmemu2qfjx    \_ animeapi-fastapi-045aef.1   animeapi-fastapi-045aef:latest   workera1                 Ready           Rejected 3 seconds ago   "No such image: animeapi-fasta…"   
93sk6vztpc28    \_ animeapi-fastapi-045aef.1   animeapi-fastapi-045aef:latest   workere2-2               Shutdown        Rejected 4 seconds ago   "No such image: animeapi-fasta…"   
75m6mqf2s8u9    \_ animeapi-fastapi-045aef.1   animeapi-fastapi-045aef:latest   workera1                 Shutdown        Rejected 8 seconds ago   "No such image: animeapi-fasta…"   
```

**Comment by binaryYuki** [comment]
I think I should investigate if the folder was override by something.
I would be helpful if you would like to provide where the datas are storage.

**Comment by binaryYuki** [comment]
And are there any methods to restore them?

**Comment by Siumauricio** [comment]
1. Regarding to dokploy take a while to restart is because that process is handled by docker swarm
2. We use a volume called `dokploy-postgres-database` but maybe we should change this to be a bind mount instead of volume to save in the file system
3. If you deleted that volume all your data is gone unfortunately, I don't know if you clean the vps or you did something which makes the volumes being eliminated, but as far I know we don't touch the volumes of dokploy itself

**Comment by binaryYuki** [comment]
Thank you for your clarification.

I just got
```bash
root@managera1:/home/ubuntu# docker volume ls
DRIVER    VOLUME NAME
local     bark
local     connectors
local     dokploy-postgres-database
local     e5-renew_renewx-appdata
local     e5-renew_renewx-deploy
local     oneapi-data
local     oneapi-logs
local     open-webui
local     portainer_portainer_data
local     redis-data-volume
local     registry-data
local     traefik_traefik-certificates
root@managera1:/home/ubuntu# docker volume inspect  dokploy-postgres-database
[
    {
        "CreatedAt": "2024-07-24T13:49:04Z",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/dokploy-postgres-database/_data",
        "Name": "dokploy-postgres-database",
        "Options": null,
        "Scope": "local"
    }
]
```
So I think this might be dokploy was move to another instance, as we did not specify which instance to deploy.

**Comment by binaryYuki** [comment]
@Siumauricio 
Hi,

Thank you for your clarification and help.

After further investigation, I've identified that the issue was caused by the dokploy-postgres service being allocated to a different server, which led to the data not being loaded correctly. Since we didn't specify which instance to deploy the service on, Docker Swarm might have scheduled it to a different node. This also explains the "volume not found" error.

I'll adjust the deployment strategy to ensure that the dokploy-postgres service is fixed to a specific instance to avoid similar issues in the future.

Thanks again for your assistance!

**Comment by binaryYuki** [comment]
Here is my solution: docker service update --constraint-add 'node.hostname == managera1' dokploy-postgres Hope this may help others who met this.

**Comment by Siumauricio** [comment]
I don't if you have a old version, in a recent version we added a constraint to make the database be on the manager node

**Comment by samuelperezh** [comment]
@Siumauricio I just got the same issue in version 0.29.8, the database was in another node of the swarm

**Comment by Fauzdar1** [comment]
Has happened with me twice now, ~not by updating but Dokploy lost the data and asked me to re-register after a system restart.~

Claude Opus 5 says It did happen because of an update.

> Your dokploy service is running image dokploy/dokploy:v0.29.7, but the service env still reads RELEASE_TAG=v0.29.2 (env vars don't auto-update, image tags do). So an update ran across this restart — v0.29.2 → v0.29.7 — and a schema migration during that update is almost certainly what reset your metadata tables. That's the recurring mechanism: suspension → restart → Dokploy updates itself → migration wipes the panel DB while leaving your app containers untouched.
