### ISSUE TITLE
Not able to use second root domain on an application

### ISSUE THREAD

**Issue by henriklovhaug** [Dokploy/dokploy#368]
### To Reproduce

1. Set up Dokploy as normal
2. Set both A and B domain to point at the VPS IP address
3. Set up dokploy site on domain A. `dokploy.A.com` for example.
4. Create a service (application or template) and assign B domain

### Current vs. Expected behavior

I expect to access the application, but I just get invalid SSL error.

The funny, but unexpected is that all of domain B's subdomains work. I can access the application at the domain `C.B.com`, but not at `B.com` directly. `A.com` works as expected.

### Provide environment information

```bash
OS: Ubuntu 24.04 LTS, x86_64
VPS: Hetzner
Dokploy: 0.7.1
Cloudflare for name server
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Additional context

I tested with applications, my own raw docker compose and templates

**Comment by Siumauricio** [comment]
Can you share the Invalid SSL Error? @henriklovhaug

**Comment by henriklovhaug** [comment]
![image](https://github.com/user-attachments/assets/c79c1d2f-3f1f-4d95-b446-46f8f664928b)
![image](https://github.com/user-attachments/assets/f837f6ea-a16a-4564-944b-57481af0e36a)

**Comment by Siumauricio** [comment]
What I mean is to share the traefik SSL error, go to settings -> traefik -> show logs, then you will see the error

**Comment by henriklovhaug** [comment]
`time="2024-08-20T06:56:59Z" level=error msg="Error renewing certificate from LE: {B.com []}, error: one or more domains had a problem:\n[B.com] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 2606:4700:3036::6815:7d5: Invalid response from http://B.com/.well-known/acme-challenge/mYGa-_b1dmfFmuJfAbTYGmOWTAeebh1GHhCr_HX1W1M: 404\n" providerName=letsencrypt.acme`

**Comment by henriklovhaug** [comment]
A quick reload of Traefik fix the issue. I should have tried it before posting an issue

**Comment by Siumauricio** [comment]
No Worries!
