### ISSUE TITLE
Add MongoDB Replication Set Creation Capability

### ISSUE THREAD

**Issue by SHCDevelops** [Dokploy/dokploy#370]
### What problem will this feature address?

The current system lacks high availability and fault tolerance for the MongoDB database. In case of a single MongoDB instance failure, the entire system may become unavailable, leading to downtime and potential data loss.

### Describe the solution you'd like

Add the capability to automatically deploy a MongoDB cluster with replication. This should include:
1. Setting up a replica set with multiple nodes (minimum of 3).
2. Automatically distributing nodes across different servers or availability zones.
3. Configuring automatic failover.
4. Providing an interface for monitoring replication status.

### Describe alternatives you've considered

1. Manual replication setup by administrators.
2. Using a managed cloud solution like MongoDB Atlas.
3. Switching to a different database with built-in replication.

### Additional context

This feature is critical for ensuring business continuity and meeting SLA requirements. It will also allow for database maintenance with minimal impact on application performance.

**Comment by talaikis** [comment]
Replica set can be pretty easily deployed with docker compose: https://medium.com/workleap/the-only-local-mongodb-replica-set-with-docker-compose-guide-youll-ever-need-2f0b74dd8384
