### ISSUE TITLE
can't stop running deployment

### ISSUE THREAD

**Issue by Dacong-wu** [Dokploy/dokploy#373]
### To Reproduce

![image](https://github.com/user-attachments/assets/92cae8fb-2c71-4dc1-a061-f3cde1aabc27)

### Current vs. Expected behavior

I wish I could stop it manually

### Provide environment information

```bash
Opersting System:
 OS: Ubuntu 22.04
 Arch: arm64
Dokploy version: 0.7.1
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
This is not a Bug, duplicate #360

**Comment by Dacong-wu** [comment]
Thanks
