### ISSUE TITLE
for arch linux it not installing

### ISSUE THREAD

**Issue by Vickydmt** [Dokploy/dokploy#378]
### What problem will this feature address?

for arch linux it not installing and its says error please make for arch linux also thanking you

### Describe the solution you'd like

i want for arch linux

### Describe alternatives you've considered

in arch endeavouros

**Comment by Siumauricio** [comment]
Hi, what architecture you have? you can run this command `uname -p`

We support for amd and arm

**Comment by Siumauricio** [comment]
Currently we do not support this operating system because I do not use it, if anyone knows what we should change to support it I would be happy to accept changes.
