### ISSUE TITLE
Removing domain not working 

### ISSUE THREAD

**Issue by TheoCouss** [Dokploy/dokploy#38]
Removing a domain from a service does not work, the domain is still mapped to the service in Traefik, rebooting Traefik does not solve the issue. It even breaks the custom domain of the panel. 

I had to delete the service

**Comment by Siumauricio** [comment]
Hi, @TheoCouss can you provide steps to reproduce the issue?

**Comment by TheoCouss** [comment]
Sure!

To reproduce the issue:

1. Begin with an empty project.
2. Create a service using the nginxdemos/hello:plain-text Docker image.
3. Add a domain to this service.
4. Verify if the service is functioning properly.
5. Remove the domain from the service in Dokploy.

Despite redeploying, Traefik continues to forward the domain to the service, which shouldn't be the case.

Additionally, attempting to restart Traefik from the settings exacerbates the problem by breaking the panel. To resolve this, it becomes necessary to delete the file associated with the service we initially created.

**Comment by Siumauricio** [comment]
Thank you! you were right, in order to prevent this if we delete the last domain, traefik config should be deleted aswell, since traefik cannot containt this structure by default.

```yaml
http:
  routers:
  services:
```
