### ISSUE TITLE
Custom service hostname

### ISSUE THREAD

**Issue by TheoCouss** [Dokploy/dokploy#39]
The service hostname is currently generated randomly, which is not convenient for setting up and developing applications that use multiple internal services. It would be more useful if the hostname could be generated based on the project and service names, and also be modifiable as needed.

**Comment by Siumauricio** [comment]
This is a good idea, but the thing is that there could be some conflicts regarding the container service name, so allowing this way can lead to unexpected problems, for example you create 2 projects and inside create the same name of an application or database, the idea sounds good, however you have to think of something extra to prevent that problem

**Comment by TheoCouss** [comment]
Instead of random names, I suggest generating hostnames based on the project and service names. For example, if the project is called "MyProject" and the service is "nginx", the hostname could be something like "myproject-nginx". This way, it's clearer which service each hostname corresponds to, making it simpler to set up and work with multiple internal services within a project. It will be necessary to add a function which checks if the hostname already exists or not.
