### ISSUE TITLE
Feature request: automatically generates domains

### ISSUE THREAD

**Issue by GabrielFNLima** [Dokploy/dokploy#40]
It will be good if Dokploy automatically generates domains like to Coolify and Vercel in the future.

**Comment by Siumauricio** [comment]
Hi @GabrielFNLima, Can you share more details about this feature? sounds good!

Where we can get this domains?

**Comment by TheoCouss** [comment]
Maybe you can prompt the user to provide a wildcard domain so you can generate domains for exposed services automatically
example: <servicename-with-hash>.example.com

**Comment by ewallz** [comment]
you can have a look at how caprover implemented the wild card sub-sub domain. For example, during setup i can set the main domain or subdomain i want to use (e.g: domain.com), then i point A record of domain.com to my Dokploy instance. I just do this once, so when i create a new app, Dokploy will automatically create a subdomain + issue ssl based on the app settings. Let say if the app name is 'radarr', Dokploy will assign radarr.domain.com for the app public url.

In Caprover, I used sub-sub domain which also works. Example: app.mydomain.com point to server IP. All app will automatically get a public url like: https://appname.app.mydomain.com

**Comment by dmatora** [comment]
Here is relevant Coolify doc https://coolify.io/docs/knowledge-base/traefik/wildcard-certificates

**Comment by Siumauricio** [comment]
I am planning to work on this issue soon, the issue is that there will be users who do not use wildcards as is my case, I usually use 1 or 2 domains and that's all, which I think would not be adapted for any case, what we could do would be something similar, implement domains generated with https://traefik.me so anyone who does not have domains can have them.

**Comment by akhil-naidu** [comment]
https://github.com/Dokploy/dokploy/pull/166#issuecomment-2189223897

**Comment by wesllycode** [comment]
Good evening. Has anyone managed to solve this problem for wildcard domains in dokploy?
