### ISSUE TITLE
Need to redeploy after adding a domain

### ISSUE THREAD

**Issue by missuo** [Dokploy/dokploy#402]
### What problem will this feature address?

I found that when I set a domain name, it automatically changes my original Compose file. (This is something I discovered after reading the documentation) However, after adding the domain name, I can't access my service, and it prompts a 404 not found error. The reason is that the latest Compose hasn't been used for redeployment. 

### Describe the solution you'd like

I hope that when the operation of adding a domain name is performed, it will automatically execute redeployment, as I think this would be more reasonable.

### Describe alternatives you've considered

Manual redeploy

**Comment by Siumauricio** [comment]
I think it would make sense to deploy when saving or creating a new domain, but this behavior can be too heavy, imagine that you have to wait several deployments to add more domains, I think it would not make sense, it would be better to add some alert to warn the user that any action should deploy for the domains to be updated.

**Comment by Siumauricio** [comment]
Close #403
