### ISSUE TITLE
Port mappings are not respected even when set properly

### ISSUE THREAD

**Issue by harshit-budhraja** [Dokploy/dokploy#422]
### To Reproduce

1. Create a new service
2. Select provider as **Github**, select your project and branch
3. Select built type as **Dockerfile**. In the path, set the path (for me, it was the root of the project, so I put it as `Dockerfile`). Leave the context blank (default value).
4. In domains tab > add a new domain. Set host, path, container port (3001 in my case).
5. In advanced tab > ports,
<img width="485" alt="image" src="https://github.com/user-attachments/assets/7ce1c1a2-a4f6-4e95-8db6-de7ef8d0ca1b">

Here, published port is the one we exposed to the internet (i.e. 3001 as set in point (4)) and target port is the port on which app listens i.e. 3000 (mentioned in my Dockerfile as `EXPOSE 3000`)
6.  In advanced tab > cluster settings, select self-host (assume that it is correctly setup already).
7. Click **Deploy**.

### Current vs. Expected behavior

# Current behaviour
The container is up and running. But it does not correctly map to a host port which is why the app is not accessible.

<img width="624" alt="image" src="https://github.com/user-attachments/assets/d1041b95-8434-4f66-89e4-515374ca784b">

Tried running `curl http://localhost:3001` which times out. This is correct because traefik configuration correctly shows an ingress route to port 3001.

<img width="714" alt="image" src="https://github.com/user-attachments/assets/470375ed-d0d7-4391-8f30-bb716f4c70cf">

The problem is that `3001 -> 3000` mapping is not happening properly.

# Expected behaviour

The ports `3001 -> 3000` mapping happens properly and app gets exposed to the set domain path.

# Sample Application
Repo: https://github.com/shuding/nextra-docs-template

P.S. Add a `Dockerfile` and `.dockerignore` to the repo before trying out.
```
# Use Node.js LTS version
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy the the application files
COPY . .

# Install dependencies
RUN npm install -g pnpm && pnpm install

# Build the application
RUN pnpm build

# Expose the port the app runs on
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]
```

### Provide environment information

```bash
OS: Ubuntu 24.04 (LTS)
Arch: ARM
Dokploy Version: v0.7.3
VPS Provider: AWS
Application Type: Nextjs
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

**Comment by PixelFederico** [comment]
I'm having the same issue, how did you fix the problem?
