### ISSUE TITLE
Template:Grafana Error

### ISSUE THREAD

**Issue by prakis** [Dokploy/dokploy#428]
### To Reproduce

1. After Login, click 'Create Service'.
2. Select 'Template' item from the list.
3. Select Grafana 9.5.20 from the templates list.
4. Click 'Confirm' button.

### Current vs. Expected behavior

Tried to create Grafana service from template and getting the deployment error "Initializing deploymentError".

Logs say 'Error response from daemon: No such container: select-a-container'

'Select a container ' drop down is having 'Containers (0)' item which is nto selectable.

### Provide environment information

```bash
OS: Ubuntu 24.0r LTS

Runnign other Go application on 80 port (not installed via Dokploy). Other NodeJS apps installed with Dokploy are working fine. On Hetzner with 4 GB RAM, Resources are not an issue, very low CPU/RAM are used.
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

I am running other applications on port 80 which are not installed via Dokploy.

**Comment by Siumauricio** [comment]
I couldn't reproduce the issue for me is working fine, what version you have? @prakis

**Comment by prakis** [comment]
@Siumauricio I installed these last week, I already had a docker + nodejs app running on port 80. So I tweaked the default Dokploy ports, maybe that caused this issue. 
Tonight I am going to create a fresh new server and try Grafana again and update you.
Thank you.

**Comment by prakis** [comment]
Hi @Siumauricio 

With a fresh new linux server on Hetzner I am still getting this error. Nothing else installed, only Dokploy and Grafana.

OS: Ubuntu 24.04

'Select a container' dropdown show as 'Containers (0)'

![dokploy-grafana-error](https://github.com/user-attachments/assets/7291ad57-e2cf-4e4e-9cb3-4807af890d2d)

![dokploy-0-containers2](https://github.com/user-attachments/assets/f7405c6e-0298-4b9c-ad02-f257ff5ddb16)

**Comment by Siumauricio** [comment]
@prakis 
1. Share the logs fo the deployment
2. What Distro you choose it?
3. Can you please go to `docker` tab to see all the containers running?

**Comment by prakis** [comment]
1.A:  I coudn't see any logs 'Error response from daemon: No such container: select-a-container'
2.A: Ubuntu 24.04: Hetzner

For Logs I clicked on 'Rebuild' from Deploy Settings and I can see Grafana started working. 

3.Answer: Before clicking 'Rebuild' button there were no dockers under the docker tab in container settings. Now I see one for grafana after Rebuild.

In couple of weeks I am going to do the same setup on a fresh VM. I will keep an eye on it and keep you posted.

**Comment by Siumauricio** [comment]
I mean when you create the template or any other service you need to click on deploy first in order to build the docker compose

**Comment by prakis** [comment]
My bad, I must have not done that first time. I will close this issue.
