### ISSUE TITLE
Swarm Helthcheck error

### ISSUE THREAD

**Issue by clifinger** [Dokploy/dokploy#435]
### To Reproduce

1) create application
2) add in swarm config 
```json
{
  "Test": [
    "CMD-SHELL",
    "HEALTHCHECK CMD curl --fail 'http://localhost:3000'"
  ],
  "Interval": 10000,
  "Timeout": 10000,
  "StartPeriod": 10000,
  "Retries": 10
}
```

### Current vs. Expected behavior

Still have error on deploy

`(HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = ContainerSpec: Interval in HealthConfig cannot be less than 1ms`

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 20.04
  Arch: arm64
Dokploy version: 0.8.1'
VPS Provider: Hetzner
What applications/services are you tying to deploy?
NodeJS
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
@clifinger can you try to assign this value `5 * 60 * 1000 * 1000`

**Comment by clifinger** [comment]
> @clifinger can you try to assign this value `5 * 60 * 1000 * 1000` ? That value is 5 mins

@Siumauricio Hello, no, always the same: (HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = ContainerSpec: Timeout in HealthConfig cannot be less than 1ms

**Comment by Siumauricio** [comment]
Acording to the api this is the min value expected `1000000` ms [Docker API](https://docs.docker.com/reference/api/engine/version/v1.33/#tag/Container/operation/ContainerCreate)
![image](https://github.com/user-attachments/assets/d7e2da68-f6ed-46cc-97e2-e654907fb2d1)

**Comment by clifinger** [comment]
I will check the code this weekend end because something is not normal :)

**Comment by Siumauricio** [comment]
what do you mean is not normal? 

I attached the screenshot from the API of docker which expect a min value, in runtime we pass this values without modifying so it should be 1:1

**Comment by Siumauricio** [comment]
See the code here 

https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/server/utils/docker/utils.ts#L221

and 

https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/server/utils/builders/index.ts#L115

**Comment by clifinger** [comment]
I install dokploy on a fresh new server right now and then I will test :) thank btw for your detailed answer and for this formidable Dokploy :)

**Comment by clifinger** [comment]
Hello @Siumauricio,

It work perfectly with 30s / 3s / 90s:

```json
{
  "Test": [
    "CMD-SHELL",
    "curl --fail http://localhost:3000/socket.io/?EIO=4&transport=polling || exit 1"
  ],
  "Interval": 30000000000,
  "Timeout": 3000000000,
  "StartPeriod": 90000000000,
  "Retries": 3
}
```
Many thanks for the help!
