### ISSUE TITLE
Unable to open swagger

### ISSUE THREAD

**Issue by wizd** [Dokploy/dokploy#439]
### To Reproduce

settings -> profile -> open swagger

### Current vs. Expected behavior

Unable to render this definition, as seen by the snapshot image

### Provide environment information

```bash
OS: Ubuntu 22.04
Hyper-V vm
Dokploy version: Version: v0.8.1
App: Next.js
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

![image](https://github.com/user-attachments/assets/3b7ba067-ddef-4a8e-8fb6-21b16392164e)

**Comment by SashaGoncharov19** [comment]
Looks like the problem is here.

![image](https://github.com/user-attachments/assets/78af8154-27f4-4bae-89cf-4252872d7292)

Zod validation failed.

![image](https://github.com/user-attachments/assets/08a5048d-0f71-4898-a604-8820142e1d07)

@Siumauricio The code seems to be valid, but it throws a very strange error.

```
❌ tRPC failed on settings.getOpenApiDocument: [query.settings.readStatsLogs] - Input parser key: "page" must be ZodString, ZodNumber, ZodBoolean, ZodBigInt or ZodDate
 GET /api/trpc/settings.getOpenApiDocument?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D 500 in 7749ms
```

**Comment by Siumauricio** [comment]
Yes, what happens is that the open api parser that we are using has certain restrictions with the data types that we must return, it is something quite easy to correct

**Comment by SashaGoncharov19** [comment]
> Yes, what happens is that the open api parser that we are using has certain restrictions with the data types that we must return, it is something quite easy to correct

Okay, will check it out
