### ISSUE TITLE
Databases server placement constraints

### ISSUE THREAD

**Issue by Satont** [Dokploy/dokploy#441]
### What problem will this feature address?

I need to place all databases on separate server in swarm cluster.

### Describe the solution you'd like

It can be done via swarm constraints.

### Describe alternatives you've considered

It can be done via selector on database setup, so user can easily select server on where database should be setted up, and this selector will just set swarm constraint maybe?

**Comment by Siumauricio** [comment]
We could expose the swarm settings api, however many people will think this will work out of the box, which is not the case you would need to synchronize the database mounts to keep the data in sync, someone created a similar issue #370 , however for now this remains outside the scope of the project.
