### ISSUE TITLE
Implement Coolify.io-like support of envs and Railway.app envs (Shared, Project, Service Env)

### ISSUE THREAD

**Issue by Siumauricio** [Dokploy/dokploy#443]
### Discussed in https://github.com/Dokploy/dokploy/discussions/419

<div type='discussions-op-text'>

<sup>Originally posted by **RedStar071** September  4, 2024</sup>
is it possible to do something like this on dokply? like like another hosting (railway.app)

Example 1:
```
Service 1: 
// use env from another service example Postgres (DATABASE)
${{Postgres.DATABASE_URL}}

Project variables:
${Project.HELLO_WORLD}}
or
All project variables:
${Shared.FOO_BAR}}
```

example 2: 
![image](https://github.com/user-attachments/assets/4efad06c-aa49-4db4-9143-de573b2c20cc)
![image](https://github.com/user-attachments/assets/9d4d51c2-f04e-4474-b780-68ab0c9be848)</div>

**Comment by AprilNEA** [comment]
Is anyone moving forward with content on this?

If not, I'm willing to try to carry it out and keep updated on progress

**Comment by Siumauricio** [comment]
Hi @AprilNEA,I am busy with other things, if you are willing to send a PR that would be awesome I am open to suggestions, can you propose some flow of how you plan to implement this functionality, what will it include, how will it be designed?
