### ISSUE TITLE
Can't clone private gitea repo by SSH on deploy

### ISSUE THREAD

**Issue by ShenQingchuan** [Dokploy/dokploy#444]
### To Reproduce

1. Prepare a live Gitea instance
2. Generate a SSH key on Dokploy admin panel `/dashboard/settings/ssh-keys`
3. Copy generated public key to Gitea user's SSH key setting
4. Create a project and set source from custom git repository URL, use repo's SSH URL, e.g. `git@git.example.com:user/repo.git`, and select the SSH key generated on Dokploy
5. Trigger deployment

### Current vs. Expected behavior

The deployment will suddenly crashed in the beginning and the error message is:
```
Initializing deployment
ERROR Cloning Custom Git: Error: Command failed: ssh-keyscan -p 22 git.my.site >> /etc/dokploy/ssh/known_hosts
: ❌
```

### Provide environment information

```bash
Dokploy is self-hosted on my VPS

         _,met$$$$$gg.           
      ,g$$$$$$$$$$$$$$$P.        OS: Debian 11 bullseye
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.10.0-23-amd64
   ,$$P'              `$$$.      
  ',$$P       ,ggs.     `$$b:    
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.8
   $$P      d$'     ,    $$P     Disk: 9.4G / 81G (13%)
   $$:      $$.   -    ,d$$'     CPU: Intel Core (Broadwell, no TSX) @ 2x 2.195GHz
   $$\;      Y$b._   _,d$P'      GPU: Cirrus Logic GD 5446
   Y$$.    `.`"Y$$$$P"'          RAM: 1081MiB / 3917MiB
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

It seems like that it's not able to retrieve SSH key info from my sub-domain "git.my.site", which is "proxyed" by Cloudflare in that DNS settings.

How can I deal with this?

**Comment by Siumauricio** [comment]
Looks like everything is working fine when using repos from the official Gitea.com

**Comment by ShenQingchuan** [comment]
Oh, I find out where the problem is.

I should start gitea internal(or we should called it "built-in" ?) SSH server, and modified the `app.ini` config file

```
DISABLE_SSH      = false
SSH_PORT         = 2222
SSH_LISTEN_PORT = 2222
START_SSH_SERVER = true
```

And reset the DNS record on Cloudflare to make sure the gitea site's record is targeting to my VPS IP address.

> Use `dig git.my.site` on my another server (which deployed Dokploy) to check whether it knows that IP)

| Type | Name          | Content         | Proxy Status     |
|------|---------------|--------------|--------------|
| A    | git.my.site   | 192.0.2.1    | DNS only     |
| A    | *.my.site     | 192.0.2.2    | Proxyed      |

and I manually run `ssh-keyscan -p 2222 git.my.site`

Then I got a correct response.

**Comment by ShenQingchuan** [comment]
Oh, I find out where the problem is.

I should start gitea internal(or we should called it "built-in" ?) SSH server, and modified the `app.ini` config file

```
DISABLE_SSH      = false
SSH_PORT         = 2222
SSH_LISTEN_PORT = 2222
START_SSH_SERVER = true
```

And reset the DNS record on Cloudflare to make sure the gitea site's record is targeting to my VPS IP address.

> Use `dig git.my.site` on my another server (which deployed Dokploy) to check whether it knows that IP)

| Type | Name          | Content         | Proxy Status     |
|------|---------------|--------------|--------------|
| A    | git.my.site   | 192.0.2.1    | DNS only     |
| A    | *.my.site     | 192.0.2.2    | Proxyed      |

and I manually run `ssh-keyscan -p 2222 git.my.site`

Then I got a correct response.
