### ISSUE TITLE
Error to start the Database

### ISSUE THREAD

**Issue by Traubenfuchs** [Dokploy/dokploy#449]
### To Reproduce

1. install dokploy
2. create project
3. create postgres database with standard settings besides un, pwd and db-name being "postgres"
4. start db
5. receive absolutely useless error message "Error to start the Database" with no hint on how to debug or what the causative error was

(same thing happens if I try to start MySql DB)

### Current vs. Expected behavior

database starts OR dokploy tells me what I did wrong
alternatively, display causative error message so I can debug myself

### Provide environment information

```bash
Latest Ubuntu image from EC2
```

### Which area(s) are affected? (Select all that apply)

Databases

**Comment by Traubenfuchs** [comment]
I didn't click "Deploy".
Would be great if the error message would tell me I need to do this.

**Comment by broven** [comment]
same behavor, I dumped log form the dokploy container
```
Error: Command failed: docker service scale windmill-db-rt3qic=1 
windmill-db-rt3qic: Error response from daemon: service windmill-db-rt3qic not found

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'docker service scale windmill-db-rt3qic=1 ',
  stdout: '',
  stderr: 'windmill-db-rt3qic: Error response from daemon: service windmill-db-rt3qic not found\n'
}
```
