### ISSUE TITLE
Feature: Custom Networks for projects/services

### ISSUE THREAD

**Issue by OskarWiedeweg** [Dokploy/dokploy#450]
### What problem will this feature address?

Currently, everything is in the dokploy-network network. This is great so every container can communicate with every other container. But I think it would be more suited to have a separate network for each project to have a bit more separation and security. 

### Describe the solution you'd like

I would like a new network for every project, a separate network in wich traefik operates in and every service that needs external access via Traefik will be added to.

### Describe alternatives you've considered

I think a new Networks Tab would also make sense so you can create custom networks and join individual services to it.

**Comment by Siumauricio** [comment]
Duplicate #129
