### ISSUE TITLE
Backup settings changes not applied

### ISSUE THREAD

**Issue by mpcref** [Dokploy/dokploy#452]
### To Reproduce

Configure a backup schedule for a database (in my case MariaDB) and save it. (e.g. every minute)
Then change the settings and save.
The new settings won't be applied.
If I change the cron pattern, disable the backup or even completely remove the backup, Dokploy will just keep making backups.
Even when I stop the database or completely remove it, Dokploy will keep trying (and failing) to make backups!
The only thing that stops the backups is to reload the server.

### Current vs. Expected behavior

Changes to a backup schedule should be applied immediately.

### Provide environment information

```bash
Rocky Linux release 9.4 (Blue Onyx)
Docker v27.2.1
Dokploy v0.8.1
```

### Which area(s) are affected? (Select all that apply)

Databases

**Comment by Siumauricio** [comment]
Thanks for reporting this, I already got the bug, in the next version will be fixed!

**Comment by mpcref** [comment]
great!

**Comment by Siumauricio** [comment]
Close in #469
