### ISSUE TITLE
Does the docs up to date?

### ISSUE THREAD

**Issue by dinhmai74** [Dokploy/dokploy#46]
Follow the docs and the video step by step and it does not works.   

https://www.youtube.com/watch?v=mznYKPvhcfw&t=277s
https://docs.dokploy.com/domains/web-domain-setup

**Comment by Siumauricio** [comment]
Is basically the same, is just a different design, but what doesn't work can you give more details about what is not working?

**Comment by dinhmai74** [comment]
I'm stuck at the Web Domain Setup step. I did everything like the video, but maybe the Cloudflare setup is not correct. In the video, he doesn't show the settings. @Siumauricio , it could help to start from the 'Add Site' step instead of only the final step of it.

**Comment by dinhmai74** [comment]
<img width="1639" alt="Screenshot 2024-05-05 at 02 35 46" src="https://github.com/Dokploy/dokploy/assets/40544043/85265a40-a423-44b7-b0c7-7dc4cae3e0bb">
<img width="1611" alt="Screenshot 2024-05-05 at 02 34 54" src="https://github.com/Dokploy/dokploy/assets/40544043/f410a630-cafb-47d3-a755-7b91cdc12266">
<img width="1617" alt="Screenshot 2024-05-05 at 02 34 46" src="https://github.com/Dokploy/dokploy/assets/40544043/efa41516-52de-4383-ba92-5f054be90634">
<img width="1461" alt="Screenshot 2024-05-05 at 02 34 36" src="https://github.com/Dokploy/dokploy/assets/40544043/0dca2646-19bc-424a-aeac-389cf05f0d1d">

**Comment by Siumauricio** [comment]
Everything looks good.

Go here and click on View Logs, and please share all the logs
![image](https://github.com/Dokploy/dokploy/assets/47042324/1b312183-e377-43b0-9cd9-60741602cb15)

**Comment by dinhmai74** [comment]
@Siumauricio  

> time="2024-05-04T17:14:17Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-05-04T17:14:17Z" level=error msg="Cannot start the provider *file.Provider: /etc/dokploy/traefik/dynamic/app-calculate-virtual-bandwidth-ev6stp.yml: routers cannot be a standalone element (type map[string]*dynamic.Router)"



<img width="1653" alt="Screenshot 2024-05-05 at 02 49 33" src="https://github.com/Dokploy/dokploy/assets/40544043/e36a8fe9-1a20-409a-bb1f-439be8bd4ae3">

**Comment by Siumauricio** [comment]
Got it!, it looks like an application doest not have any domain, someone opened a issue about this https://github.com/Dokploy/dokploy/issues/38, is already fixed and merged in canary branch, in the meantime you can do the following, simply go to the application that doesnt have any domains and go to advanced scroll down and delete all the content from traefik config, and then go back to settings -> traefik -> reload

**Comment by dinhmai74** [comment]
works like a charm now, thank a lot @Siumauricio
