### ISSUE TITLE
Incorrect environment DATABASE_URL 

### ISSUE THREAD

**Issue by vksee** [Dokploy/dokploy#460]
### To Reproduce

After deploy container env contain wrong Environment, but not specified value.

Service compose. 

Environment Settings: 
`DATABASE_URL=some_value`

Docker compose: 
```
version: '3.4'
services:
  backend:
    environment:
      - DATABASE_URL
```

### Current vs. Expected behavior

After deploy container contain wrong Environment:
`DATABASE_URL="postgres://dokploy:amukds4wi9001583845717ad2@localhost:5432/dokploy"`
This value from [apps/dokploy/.env.example](https://github.com/Dokploy/dokploy/blob/66a4e86209ef78065227a6ee6ecf10f3683552d9/apps/dokploy/.env.example) or [apps/dokploy/.env.production.example](https://github.com/Dokploy/dokploy/blob/66a4e86209ef78065227a6ee6ecf10f3683552d9/apps/dokploy/.env.production.example)

Expected: 
DATABASE_URL=some_value

### Provide environment information

```bash
Dokploy Version: v0.8.1
Docker version 27.2.1, build 9e34c9b
Ubuntu 24.04.1 LTS
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by SashaGoncharov19** [comment]
@vksee Hi! You need to add environments in environment tab

![image](https://github.com/user-attachments/assets/0ce61fbe-806b-4320-9fb7-494323c1a21b)

After this, you can use it by:
```version: '3.4'
services:
  backend:
    environment:
      - DATABASE_URL=${DATABASE_URL}

**Comment by vksee** [comment]
![Screenshot_20240918_180925](https://github.com/user-attachments/assets/48444a34-4e73-404c-a90d-f61136c7ba24)

![Screenshot_20240918_180857](https://github.com/user-attachments/assets/cde80525-fcce-4bfc-abe6-f9f06e481580)

![Screenshot_20240918_181013](https://github.com/user-attachments/assets/6e6afeb9-faf2-4f5b-bcda-4b7aabbe2120)

**Comment by vksee** [comment]
For security reasons, should this variable be made unavailable in containers?

**Comment by Siumauricio** [comment]
Thanks for reporting this very strange behavior, after a couple hours trying to fix this this looks like spawnAsync from nodejs inherit the enviroment variables for some reason 

I solve with this 😄
https://github.com/nodejs/node/issues/12986#issuecomment-300951831
