### ISSUE TITLE
Domains not working - only accessible via port and IP

### ISSUE THREAD

**Issue by quiint** [Dokploy/dokploy#467]
### To Reproduce

1. Set domain in Dokploy (local.domain.com)
2. Set Cloudflare to Full (Strict)
3. Add DNS record with DNS only (doesn't work with proxied)
4. Visit local.domain.com, doesn't work
5. Visit http://local.domain.com:3000, does work

### Current vs. Expected behavior

I expected to be able to visit my Dokploy server from the domain local.domain.com, but it's only accessible from http://local.domain.com:3000

### Provide environment information

```bash
Operating System: 
  OS: Ubuntu 24.04
  Arch: x86_64
Dokploy version: 0.8.2
VPS provider: Local home server
Trying to deploy Supabase
```

### Which area(s) are affected? (Select all that apply)

Installation, Traefik

### Additional context

The server is exposed on a public IP and it is accessible at PUBLIC_IP:3000, and the Cloudflare record is the public IP as well

**Comment by Siumauricio** [comment]
Can you please test this with another basic template like Pocketbase, just to see if the real problem comes from the supabase template?

**Comment by nhCoder** [comment]
I m facing this with Appwrite, i can access it via vps localhost curl but cannot access it outside after adding domain from dokploy with the epxosed port

**Comment by nhCoder** [comment]
bug: https://www.youtube.com/watch?v=YrEE5QVbZuI

**Comment by Siumauricio** [comment]
@nhCoder That looks like more a configuration issue from the appwrite template, can you paste the compose file and the envs you are using to see? please format it well to just copy and paste

**Comment by nhCoder** [comment]
Compose file: https://appwrite.io/install/compose

Env vars: https://appwrite.io/install/env

**Comment by nhCoder** [comment]
Keep us updated please

**Comment by Siumauricio** [comment]
Looks like you didn't make a single change to the file, you should read the documentation to better understand how to integrate any docker compose file into dokploy which is really simple, you need to add dokploy-network, remove the container_name properties, also looks like they are using their own instance of traefik which you need to remove as internally we use traefik, I would like to help you but I think you didn't try to at least read the documentation and make a minimum effort, we have a similar template which is supabase and it works fine so I'm sure this is a configuration problem if you like you can create an issue to implement this new template!

**Comment by nhCoder** [comment]
Brother, I have been researching and edting these files since 3 days , read all the documentation of dokploy, and i also know they use their own container of traefik,i removed it as well, and I also added the dokploy network to appwrite accordingto docs.. Maped ports, and did everything  possibly i could do.. The video link i sent you earlier, i have done everything exactly you told me now.. But it's not works

**Comment by nhCoder** [comment]
Can you please make a video while deploying Appwrite, i suggest you make its template as well.
I already deployed Appwrite on Coolify with the same steps but wasn't successful with Dokploy

**Comment by Siumauricio** [comment]
can you share with me the docker compose that you have modified with all dokploy's suggestions, so it will be easier for me to know the problem.

**Comment by nhCoder** [comment]
Sure here https://gist.github.com/nhCoder/eb6ae03110921d0c3a39fdcf5779e0af

**Comment by quiint** [comment]
this might have been my bad, but i didn't mean i was running supabase and that was the issue. the issue with the domain was the actual dokploy dashboard that was having the issue. 🙃

**Comment by nhCoder** [comment]
Adding domains via Dokploy Dashboard only worked for me with NixPacks

**Comment by Siumauricio** [comment]
@quiint Have you tried to restart traefik?

**Comment by nhCoder** [comment]
Yes, i did

**Comment by Siumauricio** [comment]
Feel free to reopen, I tested and everything was working as expected, I tested with Flexible and SSL Strict

**Comment by cristodcgomez** [comment]
Sorry for commenting in a closed ticket, but there is some hard changes to make appwrite to work inside dokploy. I just finished the setup after almost 2 days. I'll add a detailed guide later, but if there is a way to contribute with a template for the project I'll try to make a PR for it :)
