### ISSUE TITLE
Multi Environment Deployment

### ISSUE THREAD

**Issue by mystogan99** [Dokploy/dokploy#472]
### What problem will this feature address?

I want to deploy multiple branches using the same app. I now have to add various apps as App [Staging/Production] to deploy different versions.

### Describe the solution you'd like

Deploy 1 app with different branches. This will include different env variables for different branches, different domains etc.  

### Describe alternatives you've considered

Add different apps as different env and select different branch.

**Comment by SashaGoncharov19** [comment]
Hi @mystogan99!
Just create a new service, link to your github and deploy different branches with different envs.

**Comment by lobre** [comment]
Sorry to comment on a closed issue, but I have the same issue. And even before finding that closed issue, I effectively created another service to handle my dev/preproduction environment, which is on a different branch.

However, it raises a problem as all services from the same project seem to share the same Docker network. I am totally capable of pinging my production database, for example, from my development application. And this is bad for security, as my dev (with a potentially unstable feature) could serve as a rebound to hit and affect my production database.

Is there a way to isolate them that I missed?
