### ISSUE TITLE
Authenticate docker user before start docker-compose up command

### ISSUE THREAD

**Issue by kucherenko** [Dokploy/dokploy#478]
### What problem will this feature address?

The problem with the docker-compose deployment, when I try to install from private ghcr.io registry I faced with error like:

Head "https://ghcr.io/v2/myprivate/package/manifests/main": unauthorized

### Describe the solution you'd like

Add ability to execute command like 
echo $CR_PAT | docker login ghcr.io -u kucherenko --password-stdin

before deployment starts

### Describe alternatives you've considered

don't know any other workarounds

**Comment by Siumauricio** [comment]
hi, Are you deploying applications on your own dokploy server or on a remote server?

**Comment by abdussamadbello** [comment]
> hi, Are you deploying applications on your own dokploy server or on a remote server?

can I user ghcr as my docker repo?

<img width="649" alt="image" src="https://github.com/user-attachments/assets/fd5b4e10-6467-4a21-acdc-b7182230404d">

**Comment by kucherenko** [comment]
> hi, Are you deploying applications on your own dokploy server or on a remote server?

Hi, I use dokploy on the remote server, I've installed it there just dokploy and manage all applications there.

**Comment by Siumauricio** [comment]
Have you tried to login in the settings -> cluster -> registry and then login there?

**Comment by abdussamadbello** [comment]
Please how can I?

**Comment by Siumauricio** [comment]
@abdussamadbello go into settings -> cluster -> create registry

For Registry Name you can use Github
Username: The github username you are logging in
Password: The github token that has access to read packages 
Image prefix: ghcr.io
Registry url: https://ghcr.io

and in your application add ghcr.io/ in front of the docker image name
