### ISSUE TITLE
The access failed using the postgresql:// protocol

### ISSUE THREAD

**Issue by monsterooo** [Dokploy/dokploy#480]
### To Reproduce

I used Dokploy to create the supbase service, and then my local development failed to access the database using postgresql.

Is there anything else I need to do?

### Dokploy domain
![1727171316573](https://github.com/user-attachments/assets/7890bb41-c483-4494-8751-bf9e95affdc7)

### Error info
![WX20240924-175224@2x](https://github.com/user-attachments/assets/de09b84c-fe47-47d0-a2a8-603cb818e8ed)

I'm sure the password information is correct.

Thank you.

### Current vs. Expected behavior

I want native development to be able to connect to the database via postgresql://

### Provide environment information

```bash
OS
  Ubuntu 24
Dokploy
  latest
```

### Which area(s) are affected? (Select all that apply)

Databases

**Comment by Siumauricio** [comment]
This is not a bug you need to access trought ipAddress:port, why? because databases transport in tcp protocol not in http, and in the case you want to configure a hostname to the db you can read the traefik docs.
