### ISSUE TITLE
Add support for Gravatar profile images

### ISSUE THREAD

**Issue by sandrofigo** [Dokploy/dokploy#483]
### What problem will this feature address?

Currently I'm not able to see the profile image that is configured via Gravatar (linked to the Email that I use in Dokploy).

### Describe the solution you'd like

It would be nice to have an option in the current profile picture selection menu (e.g. last item) that shows the image configured via Gravatar and applies it to the profile picture in Dokploy.

There exists a related suggestion here https://github.com/Dokploy/dokploy/issues/213

### Describe alternatives you've considered

No alternatives available right now.

### Additional context

I would like to contribute and open a PR for this if more people find this useful.

**Comment by Siumauricio** [comment]
Close #721
