### ISSUE TITLE
Cluster Settings Option Missing After Cluster Setup

### ISSUE THREAD

**Issue by mrcloudbook** [Dokploy/dokploy#485]
### To Reproduce

1. Followed https://docs.dokploy.com/en/docs/core/get-started/manual-installation
2. Cluster https://docs.dokploy.com/en/docs/core/cluster/overview

### Current vs. Expected behavior

After following the setup instructions for creating a cluster in Dokploy, I am unable to find the "Cluster Settings" option in the advanced tab of the application settings. This issue prevents me from deploying an application with the specified number of replicas and selecting the registry for nodes to pull images from.

Expected Behavior
I expected to see the "Cluster Settings" section in the advanced tab of the application settings, allowing me to change the number of replicas and select the registry for the nodes to pull images from.

Actual Behavior
The "Cluster Settings" option is not visible in the advanced tab of the application settings.
<img width="1371" alt="image" src="https://github.com/user-attachments/assets/e831d8f7-86e9-4e29-b250-49c816dbbfdd">
<img width="1379" alt="image" src="https://github.com/user-attachments/assets/8de83a96-5d3a-4a37-9a42-d39e30d3255f">

### Provide environment information

```bash
Dokploy version: dokploy latest
Docker version: 27.2.1
Operating System and version: Ubuntu 24.04 ( Hetzner )
Browser (if applicable): Chrome and Firefox
```

### Which area(s) are affected? (Select all that apply)

Installation

### Additional context

Tested on Hetzner and Digital Ocean

**Comment by Siumauricio** [comment]
Hi this is not a bug, you are using docker compose, Cluster feature is exclusively for docker stack and applications.

If you read this, you will see we are deploying an application not a docker compose
https://docs.dokploy.com/en/docs/core/cluster/overview#deploying-an-application

**Comment by silasabbott** [comment]
Anyone know how to achieve zero downtime deployments with templates (docker compose)?
