### ISSUE TITLE
Private Docker container pull failed despite having docker registry configured in registry

### ISSUE THREAD

**Issue by renoldsingh** [Dokploy/dokploy#487]
### To Reproduce

We encountered a failure while attempting to pull a private Docker container from our configured Docker registry. Despite having the Docker registry properly set up, including the necessary authentication credentials, the pull request returned an error. 

### Current vs. Expected behavior

Initializing deployment
Creating File 'docker-compose.yml' to /etc/dokploy/compose/myappc12b99/code: ✅

File 'docker-compose.yml' created: ✅

╔══════════════════════════════════════════════════════════════════════════════╗
║                                                                              ║
║ App Name: myapp-c12b99                                         ║
║ Build Compose 🐳                                                             ║
║ Detected: 0 mounts 📂                                                        ║
║ Command: docker compose -p {redacted}c12b99 -f docker-compose.yml  ║
║ up -d --build --remove-orphans                                               ║
║ Source Type: docker raw ✅                                                   ║
║ Compose Type: docker-compose ✅                                              ║
║                                                                              ║
╚══════════════════════════════════════════════════════════════════════════════╝
time="2024-09-27T00:50:52Z" level=warning msg="/etc/dokploy/compose/{redacted}-{redacted}-c12b99/code/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
 pgadmin Pulling 
 adminer Pulling 
 migrate Pulling 
 api Pulling 
 db Pulling 
 api Error Head "https://{redacted}.com/v2/{redacted}api/manifests/test-image": no basic auth credentials
 pgadmin Error context canceled
 db Error context canceled
 migrate Error context canceled
 adminer Error context canceled
Error response from daemon: Head "https://{redacted}.com/v2/{redacted}-api/manifests/test-image": no basic auth credentials
Error ❌

### Provide environment information

```bash
Ubuntu
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

### Additional context

I tested on Hetzner VPS

**Comment by Siumauricio** [comment]
Hi @renoldsingh, are you deploying the docker compose in external server or in the same server where dokploy is installed?

**Comment by johngrimsey** [comment]
I'm experiencing this issue too. I am deploying the docker compose to an external server.

**Comment by Siumauricio** [comment]
you are right @johngrimsey, I think for remote server I forgot to add some option to log in the registry, I will see if I add it today, for now you can log in manually on the remote server and it will work, I will add an option in the registry section to log in the remote server.

**Comment by johngrimsey** [comment]
Thanks @Siumauricio !

**Comment by johngrimsey** [comment]
Heads-up I noticed Dokploy is pulling from `https://ghcr.io/v2/*` when I've only tagged and pushed to `https://ghcr.io/*`, not sure if that's something worth noting.

**Comment by johngrimsey** [comment]
I tried logging in at the CLI on both servers and it's actually still refusing to pull any images.

```
Error Head "https://ghcr.io/v2/<snip>/<snip>/manifests/latest": unauthorized
<snip> Error context canceled
 <snip> Error context canceled
Error response from daemon: Head "https://ghcr.io/v2/<snip>/<snip>/manifests/latest": unauthorized
```

Hope that helps 👍
