### ISSUE TITLE
Env editor not support multiline variables

### ISSUE THREAD

**Issue by SergiyIva** [Dokploy/dokploy#488]
### To Reproduce

1. Add new multiline variable, for example PGP key

### Current vs. Expected behavior

Env editor transform variable to plain text on multi lines, that not supported and throw error.

Expected: env file read correct and build not fail.

### Provide environment information

```bash
Operation system:
  Ubuntu 22
Dokploy version:
  v0.9.0
Application:
  docker-compose
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by b3nab** [comment]
Hi @SergiyIva , please can you provide more info and some steps on how to reproduce the issue you are facing? Like the an example of the env variables you're trying to use?

**Comment by SergiyIva** [comment]
Hi, @b3nab, of course! Here some example:
![image](https://github.com/user-attachments/assets/9993ae8f-a970-4296-94e8-361053313588)
As you can see I provide some multiline variable, I put in double quotes, but at the build stage .env file, that used by dokploy converting to multiline string without quotes. As result, we have this error:
![image](https://github.com/user-attachments/assets/65b1ee90-e759-4112-8c1d-422a2e1fc3e4)

**Comment by Siumauricio** [comment]
can you wrap in double quotes just like this `'"here_is_my_private_key"'`

**Comment by SergiyIva** [comment]
> can you wrap in double quotes just like this `'"here_is_my_private_key"'`

Yeah! That's work! Thank you, I think it would be nice to describe this behavior in the documentation.

**Comment by b3nab** [comment]
Yeah sure, I will do :)

**Comment by predragnikolic** [comment]
Requiring `"` for multiline env vars feels odd. 
For now, the good step was to document that someone needs `"` and that was done. 

It would be better if people didn't have to think about this issue and have Dokploy handle multiline env vars better.
