### ISSUE TITLE
Github Auto Deploy

### ISSUE THREAD

**Issue by JoseSanchez54** [Dokploy/dokploy#5]
Is it possible to make the deployment of the app automatic with each commit in github?

**Comment by Siumauricio** [comment]
@JoseSanchez54  Yes, you just have to do it manually once time, simpy follow this steps

- Go to any application
- Enable autodeploy toggle
- Go to deployments tab
- Copy the webhook url is at the start of the content
- Go to your repository -> Settings -> Webhooks -> Add new webhook -> in the payload URL paste the webhook URL you've copied in content-type select `application/json` and make sure to select `Just Push event`

Currently we support Github, Gitlab, Bitbucket, Gitea and dockerhub

So is basically the same steps for the rest of providers
