### ISSUE TITLE
External credentials not using correct server IP?

### ISSUE THREAD

**Issue by johngrimsey** [Dokploy/dokploy#502]
### To Reproduce

* Add a second Dokploy server
* Setup server
* Install redis, specify server 2
* Edit "External credentials", set port to 6379
* External host URL is shown but with FIRST server's IP

### Current vs. Expected behavior

Should show external host connection URL using second server's IP address

### Provide environment information

```bash
VPS provider OVHCloud
OS: Ubuntu 20.04 (primary server), Debian 12 (secondary server)
redis:alpine templated install on second server
```

### Which area(s) are affected? (Select all that apply)

Databases

### Additional context

Dokploy is WONDERFUL thank you so much!

**Comment by Siumauricio** [comment]
Thank you for reporting this, I will fix today!

**Comment by johngrimsey** [comment]
Thanks @Siumauricio !
