### ISSUE TITLE
ACME Let's Encrypt is failing

### ISSUE THREAD

**Issue by Metratrj** [Dokploy/dokploy#51]
### Version
Latest 0.0.1

### OS
Ubuntu

### This bug affects...
Certificates

### Description

First of all thank you for this nice piece of software! So now to the problem.
In general I tried many things but I can't get this to generate a valid Let's encrypt certificate. I also tried adding my own certificate in the settings but it can not be selected in the server tab.
Back to the main issue

#### traefik logs
time="2024-05-05T17:59:36Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-05-05T18:10:37Z" level=error msg="Unable to append certificate /etc/traefik/etc/dokploy/traefik/dynamic/certificates/certificate-override-auxiliary-alarm-zmw62g/chain.crt to store: unable to generate TLS certificate : tls: failed to find any PEM data in certificate input" tlsStoreName=

#### traefik config
certificatesResolvers:
  letsencrypt:
    acme:
      email: metratrj@r4p1d.xyz
      storage: /etc/dokploy/traefik/dynamic/acme.json
      httpChallenge:
        entryPoint: web

But in the 
#### acme.yml
{
  "letsencrypt": {
    "Account": {
      "Email": "test@localhost.com",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:test@localhost.com"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/1710270577"
      },
...

### Expected Behavior
Generate a valid certificate or provide a solution to the other traefik cert providers for example cloudflare but for this we should be able to set enviroment variables

**Comment by Siumauricio** [comment]
Are you using custom certificate?

**Comment by DontFred** [comment]
To add custom [provider](https://doc.traefik.io/traefik/https/acme/#providers) e. g. cf you need to add env variables. There for we need a input to add traefik env v's.

**Comment by Metratrj** [comment]
@Siumauricio I couldn't even select the custom certificate so, no I am not using one.

**Comment by Siumauricio** [comment]
This log tell me you created a custom certificate, so please go to settings -> certificates and then delete it

time="2024-05-05T18:10:37Z" level=error msg="Unable to append certificate /etc/traefik/etc/dokploy/traefik/dynamic/certificates/certificate-override-auxiliary-alarm-zmw62g/chain.crt to store: unable to generate TLS certificate : tls: failed to find any PEM data in certificate input" tlsStoreName=

**Comment by Metratrj** [comment]
@DontFred you could add one in the settings panel but not use it. U mean the use a custom certificate provider, which I noted at the end.

**Comment by DontFred** [comment]
On my end I'm even unable to create one on a fresh server.

time="2024-05-05T19:47:48Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-05-05T19:47:54Z" level=error msg="Unable to obtain ACME certificate for domains \"dok.local-lab.cc\": unable to generate a certificate for the domains [dok.local-lab.cc]: error: one or more domains had a problem:\n[dok.local-lab.cc] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: 178.27.169.30: Invalid response from https://dok.local-lab.cc/.well-known/acme-challenge/vNFcqU6QnysYpBX6yGlpmBK9jfy9M9bjS-2dTpPmW9E: 404\n" providerName=letsencrypt.acme rule="Host(`dok.local-lab.cc`)" routerName=websecure-dokploy-router-app@fi

**Comment by Metratrj** [comment]
time="2024-05-05T19:50:14Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
time="2024-05-05T19:50:18Z" level=error msg="Unable to obtain ACME certificate for domains \"dokploy.local.r4p1d.xyz\": unable to generate a certificate for the domains [dokploy.local.r4p1d.xyz]: error: one or more domains had a problem:\n[dokploy.local.r4p1d.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: no valid A records found for dokploy.local.r4p1d.xyz; no valid AAAA records found for dokploy.local.r4p1d.xyz\n" routerName=websecure-dokploy-router-app@file rule="Host(`dokploy.local.r4p1d.xyz`)" providerName=letsencrypt.acme

**Comment by Metratrj** [comment]
![image](https://github.com/Dokploy/dokploy/assets/111083448/92a9bff4-3fa7-4c48-8e33-29a176872c6c)

**Comment by Metratrj** [comment]
Even with valid DNS settings

**Comment by Siumauricio** [comment]
did you point the A record to the ip of your vps?

**Comment by DontFred** [comment]
There is the error. All domians need to be public and no ip listing is allowed.

**Comment by Metratrj** [comment]
Yes, but evaluated the problem is that you *need* to have this a public ip. So this whole setup can't be run in a homelab. It is okay, but a bit sad.

**Comment by DontFred** [comment]
The possible fix would be custom provider with wildcards 

#31

**Comment by Metratrj** [comment]
So my approach would be to provide support for the homelab community, is a solution to set/provide enviroment variables for the traefik container. So we could use all the other providers.

**Comment by Siumauricio** [comment]
We can close this issue since this isn't a Dokploy bug specific this is more an external thing that we cannot handle, if @DontFred said with wildcards feature can probably be fixed we can mark this as a duplicate, Thanks!

**Comment by DontFred** [comment]
@Siumauricio @Metratrj Maybe just as a Hotfix, we could go back to initialize Dokplay with a docker-compose. So that everybody can "easy" change the docker-compose to there liking. 

For that we need to skip then the DB and Traefik inits:

[server.ts](https://github.com/Dokploy/dokploy/blob/canary/server/server.ts)	
```ts
			await initializePostgres();
			await initializeTraefik();
			await initializeRedis();
```

**Comment by Siumauricio** [comment]
@DontFred I don't see much reason to change it, since we provide the traefik.yml file which allows you to achieve the same result, only that in compose you use labels and in our case you use yaml files.

**Comment by tianheg** [comment]
> time="2024-05-05T19:50:14Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml" time="2024-05-05T19:50:18Z" level=error msg="Unable to obtain ACME certificate for domains "dokploy.local.r4p1d.xyz": unable to generate a certificate for the domains [dokploy.local.r4p1d.xyz]: error: one or more domains had a problem:\n[dokploy.local.r4p1d.xyz] acme: error: 400 :: urn:ietf:params:acme:error:dns :: no valid A records found for dokploy.local.r4p1d.xyz; no valid AAAA records found for dokploy.local.r4p1d.xyz\n" routerName=websecure-dokploy-router-app@file rule="Host(`dokploy.local.r4p1d.xyz`)" providerName=letsencrypt.acme

Same 400 error as you @Metratrj, open VPS's 80 and 433 port at the same time, then reload the Traefik should fix it.
