### ISSUE TITLE
Fractional CPU reservation and limit?

### ISSUE THREAD

**Issue by johngrimsey** [Dokploy/dokploy#510]
### What problem will this feature address?

Inability to specify floating point values for CPU values. As I understand it docker allows partial CPU allocation/reservation.

Allowing partial CPU allocation allows more fine-grained control over resource allocations.

### Describe the solution you'd like

Allow floating point values in CPU boxes

### Describe alternatives you've considered

Not sure!

**Comment by Siumauricio** [comment]
I think it would be better to remove the conversion that we do internally, and leave the field free to put any value based on the docker api. 


![image](https://github.com/user-attachments/assets/af1ee076-a055-496c-9b77-1dbb84dcaeb7)

**Comment by johngrimsey** [comment]
Perfect 👍

**Comment by Siumauricio** [comment]
I removed the conversion we use and left the value as docker api expect 

https://docs.docker.com/reference/api/engine/version/v1.45/#tag/Container/operation/ContainerUpdate
