### ISSUE TITLE
In the settings, the domain name cannot be configured correctly.

### ISSUE THREAD

**Issue by SheldonLiu0412** [Dokploy/dokploy#512]
### To Reproduce

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/d6ad98cf-6de4-4cab-a316-2976d334bc94">

### Current vs. Expected behavior

When I correctly configured the domain name and email here, a 404 not found error occurred. I could only modify the host address to the domain name in the dokploy.yml file, and then everything worked normally. Is there a problem with the template? Moreover, once the file is set, it will change and cannot be reverted.

### Provide environment information

```bash
Centos7
```

### Which area(s) are affected? (Select all that apply)

Traefik

**Comment by Siumauricio** [comment]
Hello, I do not understand much the issue, can you give step by step how to reproduce the problem, more context?

**Comment by SheldonLiu0412** [comment]
> Hello, I do not understand much the issue, can you give step by step how to reproduce the problem, more context?

I purchased a domain name and set up the A@ server IP address. If I manually change the default host name to this domain in the dokploy.yml, then the dokploy website on port 3000 can be accessed through the domain name. However, if I enter the domain name in the settings, a 404 error occurs when visiting the domain name. I have confirmed that this issue is not caused by the firewall, so I can only guess that there is a problem with the template setup?

**Comment by Siumauricio** [comment]
@SheldonLiu0412 What changes did you make to the traefik file to make it work? I have tested on a new server and it is working correctly, just remember that if you add the domain before adding the DNS A record it will not work in case you are using letsencrypt, you need to first point the A record to the vps ip and then you put the domain name in dokploy, this order should be like this because traefik prevents retrying the certificate generation unless you modify the domain or restart traefik.

**Comment by amkayondo** [comment]
Just a question, why is the IP address still unsecure but the domain is and also are there steps to make sure the IP address redirects to the domain automatically

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 What changes did you make to the traefik file to make it work? I have tested on a new server and it is working correctly, just remember that if you add the domain before adding the DNS A record it will not work in case you are using letsencrypt, you need to first point the A record to the vps ip and then you put the domain name in dokploy, this order should be like this because traefik prevents retrying the certificate generation unless you modify the domain or restart traefik.
I modify the line for the host, just change the default domain to the new one. I will try again in your order and provide feedback later. Additionally, there is indeed another issue. When I use a third-level domain for the application, even if I check the option for automatic certificate generation, it still prompts that the website is not secure. I'm not sure if it's due to the order. Can Dokploy add automatic redirection in the future?

**Comment by SheldonLiu0412** [comment]
> @SheldonLiu0412 What changes did you make to the traefik file to make it work? I have tested on a new server and it is working correctly, just remember that if you add the domain before adding the DNS A record it will not work in case you are using letsencrypt, you need to first point the A record to the vps ip and then you put the domain name in dokploy, this order should be like this because traefik prevents retrying the certificate generation unless you modify the domain or restart traefik.

I modify the line for the host, just change the default domain to the new one. I will try again in your order and provide feedback later. Additionally, there is indeed another issue. When I use a third-level domain for the application, even if I check the option for automatic certificate generation, it still prompts that the website is not secure. I'm not sure if it's due to the order. Can Dokploy add automatic redirection in the future?

**Comment by Siumauricio** [comment]
> Just a question, why is the IP address still unsecure but the domain is and also are there steps to make sure the IP address redirects to the domain automatically

Simple, if you do something wrong in terms of traefik your service will be unreachable via the domain, so the last option will be to access through the port.

**Comment by Siumauricio** [comment]
> I modify the line for the host, just change the default domain to the new one. I will try again in your order and provide feedback later. Additionally, there is indeed another issue. When I use a third-level domain for the application, even if I check the option for automatic certificate generation, it still prompts that the website is not secure. I'm not sure if it's due to the order. Can Dokploy add automatic redirection in the future?

I'm sorry, I still don't quite understand the context of what options you are using, if you would provide a step-by-step it would be better to understand the problem.

**Comment by Siumauricio** [comment]
Feel free to reopen with the steps to take a look on this issue!
