### ISSUE TITLE
Add an option to also delete local volumes when deleting Compose

### ISSUE THREAD

**Issue by AprilNEA** [Dokploy/dokploy#513]
### What problem will this feature address?

Currently, when using Dokploy to manage Docker Compose applications, users face a significant inconvenience: the inability to automatically delete local volumes associated with a Docker Compose setup when the setup is deleted. This can lead to frustration as users must manually clean up these volumes, which can accumulate over time and consume unnecessary disk space.

I often find myself needing to remove not just the containers and networks created by Docker Compose but also the local volumes that are no longer needed. The manual process of identifying and deleting these volumes separately is tedious and error-prone.

### Describe the solution you'd like

The proposed solution is straightforward: add an option to the Docker Compose management dialog for deleting Dokploy that allows users to automatically delete local volumes when deleting a Compose setup.

<img width="724" alt="image" src="https://github.com/user-attachments/assets/abfa8f08-c185-4279-8039-654896d4c233">

By integrating this feature into the core functionality of Dokploy, users would benefit from a streamlined process, enhancing usability and efficiency in managing their Docker environments.

### Describe alternatives you've considered

While there are some workarounds available, they are not ideal. One alternative is to manually run Docker commands to remove volumes after deleting the Compose setup. For instance, users could execute:

```bash
docker volume rm $(docker volume ls -qf dangling=true)
```

However, this requires additional steps and knowledge of Docker commands, which may not be user-friendly for everyone.

### Additional context

Integrating this feature aligns with common practices in container management, where automatic cleanup of resources helps maintain a clean environment and reduces clutter. Many users expect such functionality from modern deployment tools, making it a valuable addition to Dokploy's feature set.

By addressing this issue, Dokploy would enhance its appeal to users who prioritize efficiency and ease of use in their application deployment workflows.

**Comment by AprilNEA** [comment]
> Thanks, but I have a doubt if you have activated the docker cleanup that runs every day, the volumes will be deleted anyway,

Yes, cleanup can be clean. But there are times when we may want to clean up right away.

**Comment by DJKnaeckebrot** [comment]
As an FYI for whoever is following in this, I have it in the works. Can be tracked in #886
