### ISSUE TITLE
Failing to refresh docker-compose.yml from GitHub repo

### ISSUE THREAD

**Issue by johngrimsey** [Dokploy/dokploy#514]
### To Reproduce

* Create a compose application
* Specify GitHub source, authenticate using app
* Specify repo
* Specify branch
* Specify correct compose file path
* Create domain(s)
* Click "Preview Compose" button
* Click "Refresh"

### Current vs. Expected behavior

**Expected:**
Changes to the docker compose file are reflected in the updated preview modal contents

**Actual:**
Toast notification with message "Error to fetch source type" appears. Modal content is not updated.

### Provide environment information

```bash
Ubuntu 20.04
Dokploy v0.9.3
```

### Which area(s) are affected? (Select all that apply)

Docker Compose

**Comment by Siumauricio** [comment]
I cannot reproduce the issue, for me is working

https://github.com/user-attachments/assets/b6442338-d472-4af1-a542-bf69cf125bda

**Comment by johngrimsey** [comment]
Hey thanks - my repo is a private repo, not sure if that would change anything?

**Comment by Siumauricio** [comment]
I tested on a private repo also and is working fine, are you sure you specified the right docker compose path?

**Comment by johngrimsey** [comment]
Yes it loaded it the first time right after I created the project.

**Comment by Siumauricio** [comment]
Can you share a video? you will have the error in the case you didn't save the source provider

**Comment by johngrimsey** [comment]
![CleanShot 2024-10-02 at 21 38 54 2@2x](https://github.com/user-attachments/assets/8b4619ab-d741-410a-911f-0bed4822f62d)
![CleanShot 2024-10-02 at 21 38 59 3@2x
![CleanShot 2024-10-02 at 21 39 11 2@2x](https://github.com/user-attachments/assets/804847d3-2556-4cd4-8750-e6d3b08e8233)
](https://github.com/user-attachments/assets/23aa390d-803f-431f-b3f1-0aab74b38810)

Here's a sequence of screens, hope this helps.

**Comment by Siumauricio** [comment]
Are you deploying in a remote server or dokploy server?

**Comment by johngrimsey** [comment]
Remote
