### ISSUE TITLE
Installation script fail with "This script must be run as root"

### ISSUE THREAD

**Issue by monkeymonk** [Dokploy/dokploy#517]
### To Reproduce

1. run `curl -sSL https://dokploy.com/install.sh | sh`

### Current vs. Expected behavior

Currently throw a message "This script must be run as root"

### Provide environment information

```bash
Ubuntu 24.04.1
ZSH 5.9
```

### Which area(s) are affected? (Select all that apply)

Installation

### Additional context

I started the installation process on my local environnement and was stuck on the curl by this message.

**Comment by Siumauricio** [comment]
I think the error is quite clear, you have to run the command in root user

**Comment by monkeymonk** [comment]
So should i ‘sudo su’ before executing this? I’ve try doing ‘sudo curl’ but obviously didn’t work.

Thank you! I should have think twice indeed…

Dumb question but why the script break on this instead of implementing the switch?

**Comment by Siumauricio** [comment]
try to run like this `curl -sSL https://dokploy.com/install.sh | sudo sh`

**Comment by Siumauricio** [comment]
> So should i ‘sudo su’ before executing this? I’ve try doing ‘sudo curl’ but obviously didn’t work.
> 
> Thank you! I should have think twice indeed…
> 
> Dumb question but why the script break on this instead of implementing the switch?

I assume it depends on the user you are running the script, the privileges the user have, more things can cause that error
