### ISSUE TITLE
Create application service with Dockerfile provider from private ghcr.io account

### ISSUE THREAD

**Issue by johngrimsey** [Dokploy/dokploy#528]
### To Reproduce

* Add ghcr.io registry login to cluster settings, selecting external server
* Create new Application service on external server
* Choose Docker provider
* Use private registry credentials (Docker image, username, password)
* Click deploy

## Current behaviour

Deploy fails to pull image from registry

![CleanShot 2024-10-04 at 22 34 17@2x](https://github.com/user-attachments/assets/557b6cf6-a9c4-4536-bb11-c365d667c23a)

## Expected behaviour

Specifying login details on the Provider panel should allow image to be pulled for deployment, whether on external server or Dokploy server.

### Provide environment information

```bash
Dokploy 0.9.4
```

### Which area(s) are affected? (Select all that apply)

Docker

### Additional context

Unsure if there is a relationship between the registry details in the Cluster Settings, and the login details on the provider panel.

**Comment by Siumauricio** [comment]
In the latest version we add a option to login in the remote server, have you tried?

![image](https://github.com/user-attachments/assets/ca4155e5-ef7b-4d05-9de6-fbdeaed5f652)

**Comment by johngrimsey** [comment]
Yep did that first! Now works great with docker-compose. Not working deploying a single Dockerfile from a remote registry, putting the credentials into the provider box. Works on Dokploy server but not to external server.

**Comment by Siumauricio** [comment]
Strange, I tested with dockerhub in remote server and is working fine, can you follow this steps to configure the ghrc registry?

https://github.com/Dokploy/dokploy/issues/478#issuecomment-2372174495

**Comment by johngrimsey** [comment]
Yes I did exactly that first. Current state is:

* External server (VPS1) and Dokploy server (VPS2)
* External registry added, specified VPS1
* Create application, Docker provider
* Specify private image - add username/password on the Provider options
* Works to deploy to Dokploy server, fails to pull when on external

I did manually login to ghcr.io on my external VPS (`/home/root/.docker/config.json` exists)

**Comment by Siumauricio** [comment]
Can you show how did you configured your ghrc registry in the registry section?

**Comment by Siumauricio** [comment]
@johngrimsey I did this without login manually 

Steps:

1. Login via docker registry UI
![image](https://github.com/user-attachments/assets/9a1e25b0-fc85-43f2-a0eb-9c53440df77d)
2. Create the application and set the image like this 
![image](https://github.com/user-attachments/assets/10b87313-08d3-429a-b141-e499bac776c7)
Before without authenticating
![image](https://github.com/user-attachments/assets/50af067e-700a-4a60-8b8f-4e592f540b79)
After
![image](https://github.com/user-attachments/assets/3066bb16-d45c-4efa-ab4f-fab25e34efeb)

**Comment by johngrimsey** [comment]
Thanks @Siumauricio that worked for me too thanks.

Perhaps in the Provider panel, the UI can show it will use global registry credentials, or provide the option to override with specific username/password. That might have made it clearer for me. I didn't try without the username/password in the Provider panel!

**Comment by Siumauricio** [comment]
Yes, I think it makes sense to hide the build type when it is a dockerhub image.

**Comment by juandl** [comment]
Have same issue here
![image](https://github.com/user-attachments/assets/e7fb3e28-3dde-4608-bd6d-f0d32cc8db6b)

I already add the "registry" in settings and still doesn't work
