### ISSUE TITLE
Access the hosted application in localhost

### ISSUE THREAD

**Issue by shubhankartrivedi** [Dokploy/dokploy#53]
It says to add a domain to access to application but there is no way to access in localhost.
Like a port forward in docker will be good.
Example: My NextJS website hosts in 3000 port inside container and then it is forwarded to 3001 port outside the container in my localhost.

**Comment by Siumauricio** [comment]
If you want to fordward to another port you can do in your application -> advanced -> Ports

**Comment by shubhankartrivedi** [comment]
Thanks, it works!
