### ISSUE TITLE
Calcom template not working

### ISSUE THREAD

**Issue by drupler** [Dokploy/dokploy#532]
### To Reproduce

1. Deploy default template for Calcom and attach a custom domain
2. Visit it, and you should be getting it
![calcom-template](https://github.com/user-attachments/assets/58340e02-1574-4b71-80f6-334edbaad72a)

### Current vs. Expected behavior

I expected the application to run

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 20.04
  Arch: arm64
Dokploy version: 0.9.4
VPS Provider: Hetzner.
What applications/services are you tying to deploy?
Calcom
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
I tested and is working as expected 

![image](https://github.com/user-attachments/assets/20206076-4aa0-499a-a001-7ddcba166311)
![image](https://github.com/user-attachments/assets/317ecc91-e2da-4e6b-bf02-bd8807ef100f)
![image](https://github.com/user-attachments/assets/82bad65e-2190-44ed-8264-ef2797d36a0e)
