### ISSUE TITLE
GitLab Provider Error: Missing or invalid code

### ISSUE THREAD

**Issue by ido-pluto** [Dokploy/dokploy#534]
### To Reproduce

Try to configure GitLab provider, when redirecting back to your server you will get an error: "Missing or invalid code"

I suspect that the error is related to something here:

```ts
	if (!code || Array.isArray(code)) {
		return res.status(400).json({ error: "Missing or invalid code" });
	}

	const gitlab = await findGitlabById(gitlabId as string);

	const response = await fetch("https://gitlab.com/oauth/token", {
		method: "POST",
		headers: {
			"Content-Type": "application/x-www-form-urlencoded",
		},
		body: new URLSearchParams({
			client_id: gitlab.applicationId as string,
			client_secret: gitlab.secret as string,
			code: code as string,
			grant_type: "authorization_code",
			redirect_uri: `${gitlab.redirectUri}?gitlabId=${gitlabId}`,
		}),
	});

	const result = await response.json();

	if (!result.access_token || !result.refresh_token) {
		return res.status(400).json({ error: "Missing or invalid code" });
	}
```

[apps/dokploy/pages/api/providers/gitlab/callback.ts
](https://github.com/Dokploy/dokploy/blob/a237c651c30f085432e7931ea23569701381375c/apps/dokploy/pages/api/providers/gitlab/callback.ts#L11)

The redirect URL looks like this: https://server.com/api/providers/gitlab/callback?gitlabId=id&code=something

### Current vs. Expected behavior

To redirect successfully

### Provide environment information

```bash
Ubuntu 24.04.1 LTS
x86_64
Dokploy: v0.9.4
VPS: Contabo
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

BTW: This is an amazing project!, thank you 🙏

**Comment by Siumauricio** [comment]
This information is not helpful, I need steps to reproduce the problem, I tried this and it is working as expected, I don't know if you followed the instructions in the gitlab modal?

**Comment by ido-pluto** [comment]
Yes, I did. 
For some reason, when I did it again today, it **failed the first time** and **succeeded the second** time, even though I did not do anything different other than **give it more delay** between steps.

Maybe it is worth doing a kind of retry mechanism as GitLab take time to  process.

**Comment by Siumauricio** [comment]
If you don't select the right permissions it will not work, is required to select all the permissions described in the modal which are 3

**Comment by correiarmjoao** [comment]
@Siumauricio 
Not exactly sure if its the same problem I had yesterday while setting up gitlab but seems like it. The problem I had seems to be this line.

https://github.com/Dokploy/dokploy/blob/dc9a194bbe44198accdef77b6c9a4d4de9c01579/apps/dokploy/pages/api/providers/gitlab/callback.ts#L36

If the gitlab response doesn't have expires_in field expiresAt will be NaN and the db call will throw.

https://github.com/Dokploy/dokploy/blob/dc9a194bbe44198accdef77b6c9a4d4de9c01579/packages/server/src/services/gitlab.ts#L65-L77

When creating an app in gitlab theres an option to active the expires, with that option selected there is no problem.
