### ISSUE TITLE
Have you consider OCI (Oracle Cloud Platform) or a way to deploy with another VPS easy (perhaps an example) ?

### ISSUE THREAD

**Issue by kaesar** [Dokploy/dokploy#54]
Have you consider OCI (Oracle Cloud Platform) or a way to deploy with another VPS easy (perhaps an example) ?
Oracle Cloud Platform is cheap when you get a free VPS for years (price 0) and their plans seems competitive.
Thanks because this project is a great idea.

**Comment by ashermyers** [comment]
Installation should be pretty similar across different vps providers if that is what your asking. If you need help opening ports on your oracle vps for dokploy, I recommend checking this out: https://www.reddit.com/r/oraclecloud/comments/r8lkf7/a_quick_tips_to_people_who_are_having_issue/

**Comment by Siumauricio** [comment]
Hey @kaesar @ashermyers  recently I added a docs step by step how to deploy on a oracle cloud.

https://docs.dokploy.com/deployment/oracle-cloud
