### ISSUE TITLE
Need more control over Docker Compose command in deployments

### ISSUE THREAD

**Issue by Brayan233** [Dokploy/dokploy#540]
### What problem will this feature address?

Hey team,

We're running into some limitations with our current deployment setup using dokploy. The main issue is that we can't fully customize the Docker Compose command, which is causing some headaches.

Right now, we can only tweak the parameters for the `up` command, but we can't add options that need to go before `up`. This is a problem when we want to use things like profiles or set a custom project name.

For example, we can't do something like this:

`docker compose -p my-project --profile prod up -d --build`

### Describe the solution you'd like

It'd be great if we could have more flexibility here. Maybe we could have an option to specify the entire Docker Compose command in our deployment config?

This would help us use more advanced Docker Compose features without having to resort to workarounds.

### Describe alternatives you've considered

As a workaround, I simply removed the profiles option in my compose file, so the default command is able to run the whole stack.

**Comment by Siumauricio** [comment]
I could implement a field to put a customizable command, however I will have to put in that modify the command or something may make dokploy ui not work with things like logs, monitoring and maybe other things.
