### ISSUE TITLE
Install failed due to docker swarm initialize failed

### ISSUE THREAD

**Issue by jiz4oh** [Dokploy/dokploy#541]
### To Reproduce

1. add  `"live-restore": true` in `/etc/docker/daemon.json`
2. restart docker `systemctl restart docker`
3. install dokploy `curl -sSL https://dokploy.com/install.sh | sh`

### Current vs. Expected behavior

raise an error instead of successful message if docker swarm initalize failed

### Provide environment information

```bash
Operating System:

OS: Debian 12

Arch: amd64

Dokploy version: latest
```

### Which area(s) are affected? (Select all that apply)

Installation

### Additional context

![image](https://github.com/user-attachments/assets/485eb424-4864-4dfd-ba3b-37eff99bdd34)

**Comment by Siumauricio** [comment]
Hi, I think the message is clear, you can't use live-restore flag in docker configuration with docker swarm, dokploy depends a lot on docker swarm to work well.

**Comment by jiz4oh** [comment]
hi @Siumauricio , I think the installation is not finished and the message tells me to *wait 15 seconds for the server to start*. but there is nothing at all after 15 seconds, nothing happened on *3000*. I were not sure what's the next step, maybe a friendly remind is better

**Comment by Siumauricio** [comment]
@jiz4oh The problem is that you are using a flag that is not supported by docker swarm, I think it would be good to exit the script if there is an error when trying to initialize docker swarm.
