### ISSUE TITLE
Feat: add 'dokploy env' cli command to manage environment variables

### ISSUE THREAD

**Issue by kidylee** [Dokploy/dokploy#555]
### What problem will this feature address?

Update environment variables via UI is the the only option.

### Describe the solution you'd like

Add a `dokploy env` and sub-commands in cli to manage `.env` file between codebase and deployment target.

* `dokploy env pull [ENV_FILE_NAME]` this sub-command will pull environment variables from deployment target to the '.env' file, `ENV_FILE_NAME` is an alternative name to prevent file collision. Eg: `dokploy env pull .env.production.local`
* `dokploy env add KEY VALUE` adding new environment variable to a specific deployment target
* `dokploy env rm KEY` removing environment variable from deployment target.

### Describe alternatives you've considered

None

### Additional context

I could contribute pr.

**Comment by Siumauricio** [comment]
Hi, could you give me more details on how it would work? I would be happy to accept a PR on this.

**Comment by kidylee** [comment]
> * `dokploy env pull [ENV_FILE_NAME]` this sub-command will pull environment variables from deployment target to the '.env' file, `ENV_FILE_NAME` is an alternative name to prevent file collision. Eg: `dokploy env pull .env.production.local`
> * `dokploy env add KEY VALUE` adding new environment variable to a specific deployment target
> * `dokploy env rm KEY` removing environment variable from deployment target.

@Siumauricio  Sorry for the confusion. I have update some details.

**Comment by Siumauricio** [comment]
sounds good, this is the repo of the CLI https://github.com/Dokploy/cli
