### ISSUE TITLE
feat: Add an input box to enter the project name for a second confirmation when deleting the application.

### ISSUE THREAD

**Issue by skyoct** [Dokploy/dokploy#556]
### What problem will this feature address?

Reduce losses caused by operational errors.

### Describe the solution you'd like

Add an input box to enter the project name for a second confirmation when deleting the application.

### Describe alternatives you've considered

Add an input box to enter the project name for a second confirmation when deleting the application.

**Comment by Siumauricio** [comment]
This sounds like a good idea!

**Comment by Siumauricio** [comment]
Close in #777
