### ISSUE TITLE
Unable to access cluster application by ip and port

### ISSUE THREAD

**Issue by AprilNEA** [Dokploy/dokploy#557]
### To Reproduce

1. Create a application
2. Add ports
3. Increase the number of cluster replicas greater than 1

### Current vs. Expected behavior

Current: Accessing by ip and port will result in a 404 not found
Expected: Normal access via IP and port

### Provide environment information

```bash
Operating System:
	- OS: Ubuntu 22.04
	-Arch: amd64

Dokploy version: 0.10.0

VPS Provider: Netcup

What applications/services are you tying to deploy?

Dockerfile
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
I deployed this application which is a simple express app 

https://github.com/Dokploy/swarm-test

My Settings:

![image](https://github.com/user-attachments/assets/dcffc1da-e288-4749-a4c2-7827ed7382c7)
![image](https://github.com/user-attachments/assets/67593940-e78a-4a16-b22c-924924de6169)
![image](https://github.com/user-attachments/assets/427d0787-da8c-41e8-9fb2-bc4c31183e15)
![image](https://github.com/user-attachments/assets/abf0d7a3-c96c-45ea-8049-38c1a8cc4e83)


then you can access to `http://your-ip:5000/`

**Comment by Siumauricio** [comment]
feel free to reopen if you still have the issue, as you can see above everything is working as expected

**Comment by AprilNEA** [comment]
Thanks. I'll try again. My program is running from Dockerfile, I'll try to see if I can reproduce it using Dockerfile.
