### ISSUE TITLE
Import existing docker images as projects

### ISSUE THREAD

**Issue by dmatora** [Dokploy/dokploy#56]
Not sure what would be proper title for this issue.
Initially I had glitchtip installed via docker and serving via nginix.

After bringing down ngninx and installing Coolify to serve on port 80 instead, I was still able to get glitchtip served by Traefik, by updating Traefik configuration according to Coolify docs (added environment configuration with cloud flare keys and added domain labels to glitchtip docker-compose.yml)

After I installed Dokploy, my glitchtip instance of Traefik refused to respect glitchtip docker-compose.yml domain labels, so I had to go back to Coolify

Dokploy uses traefik:v2.5
Coolify uses traefik:v2.10
Maybe that is an issue.

Anyway, besides supporting serving existing docker containers via dokploy-traefik having some sort of UI assisting in importing these into dokploy would be helpful and maybe significant advantage over Coolify

**Comment by Siumauricio** [comment]
Hmm so you are running two traefik instances? the dokploy instance and the coolify?

**Comment by dmatora** [comment]
No, I had to bring down coolify instances to try dokploy

**Comment by Siumauricio** [comment]
Got it.

I understand, I think this problem would come from traefik, from the panel you have to enable docker mode and swarm mode, and now traefik should recognize the labels

```yaml
providers:
  docker:
    exposedByDefault: false
```

and make sure to pass this label to the glitchtip instance 


```
  - "traefik.enable=true"
```

**Comment by Siumauricio** [comment]
#111 Done
