### ISSUE TITLE
Provide API to Modify Environment Variables

### ISSUE THREAD

**Issue by lostz** [Dokploy/dokploy#573]
### What problem will this feature address?

I am considering using GitHub Actions to call the Dokploy API for deploying my Docker Compose application. However, my environment variables are stored in GitHub Secrets. I need a way to automatically retrieve these Secrets during the deployment process and pass them to the Docker Compose setup.

### Describe the solution you'd like

The solution I'd like is an API that allows modifying the environment variables (env) for a specific project.

### Describe alternatives you've considered

None

**Comment by Siumauricio** [comment]
Hey @lostz, you can use the compose.update endpoint, and then pass to the env field

https://docs.dokploy.com/en/docs/api/reference-api/reference-compose#compose-update

**Comment by Siumauricio** [comment]
I think we can close this issue, we already provide a method for applications and compose to be able to pass environment variables.
