### ISSUE TITLE
Feature Request: API to trigger actions / change settings

### ISSUE THREAD

**Issue by mezotv** [Dokploy/dokploy#588]
### What problem will this feature address?

Currently in Dokploy you cant trigger actions like backups, service creation or redeployments from outside of the Dokploy dashboard.

### Describe the solution you'd like

It would be awesome if dokploy came with an optional api service allowing you to create services, manually trigger backups or redeploy an application. This could be useful for people who for example run a hosting company for example for minecraft servers where users are able to create their own server. This would be similar to Pterodactyl Panel but much prettier.

The api should be securied with api keys and (optional) with different permissions per api key. Along with a user permission to create such an api key. 

### Describe alternatives you've considered

Another way to modify settings or trigger actions would also work it doesnt need to be an api!

**Comment by mezotv** [comment]
A lot of discord bots that have a custom instance as a paid membership would be able to benefit a lot from this if the paying bot user could also access the dashboard and see tabs based on their permission. This would be a major feature though!

**Comment by Siumauricio** [comment]
Hi @mezotv, You can do all that with the dokploy API, you can trigger deployments, rebuilds, manual backups, almost 97% of dokploy's functionality is done through the API, so it should work without problems except for things like monitoring which is not available, you can create an API Key to authenticate in the profile section

**Comment by mezotv** [comment]
> Hi @mezotv, You can do all that with the dokploy API, you can trigger deployments, rebuilds, manual backups, almost 97% of dokploy's functionality is done through the API, so it should work without problems except for things like monitoring which is not available, you can create an API Key to authenticate in the profile section

Can I also automate the whole process of lets say one of my users getting an account access to the dashboard being able to start/stop their custom instance? And well restricting what tabs they see and things they can do?

**Comment by Siumauricio** [comment]
I would say yes, at the end the API is the same as the one used in dokploy UI, so if you want to build another UI using the api you can do it

**Comment by mezotv** [comment]
> I would say yes, at the end the API is the same as the one used in dokploy UI, so if you want to build another UI using the api you can do it

Is the api documented somewhere?

**Comment by Siumauricio** [comment]
Yes here https://docs.dokploy.com/en/docs/api
