### ISSUE TITLE
Use advertise_addr from environment variable in dokpoy service

### ISSUE THREAD

**Issue by medihack** [Dokploy/dokploy#593]
### What problem will this feature address?

We would like to use dokploy in a non-public hospital network. It is possible to specify a custom `advertise_addr` in the installation script, but the dokploy service itself still [tries to fetch its IP using the ifconfig.io website](https://github.com/Dokploy/dokploy/blob/182f908c314f78ea25b5832a56f7d7dc7c75e5b1/apps/website/public/install.sh#L44). It would be nice if the `advertise_addr` is also respected in the dokploy service itself.

### Describe the solution you'd like

Allow to provide the `advertise_addr` by using an environment variable, e.g.
```
# Pull and deploy Dokploy
docker pull dokploy/dokploy:latest
docker service create \
  --name dokploy \
  --replicas 1 \
  --network dokploy-network \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
  --publish published=3000,target=3000,mode=host \
  --update-parallelism 1 \
  --update-order stop-first \
  -e ADVERTISE_ADDR=$advertise_addr \
  -e PORT=<Value For PORT eg(3000)> \
  -e TRAEFIK_SSL_PORT=<Value For SSL PORT eg(444)> \
  -e TRAEFIK_PORT=<VALUE FOR TRAEFIK HTTP PORT eg(81)> \
  dokploy/dokploy:latest
```

And if that environment variable is set in the service then prefer it over ifconfig.io

### Describe alternatives you've considered

A workaround is to create a ssh tunnel and access the dokploy interface using localhost.

**Comment by Siumauricio** [comment]
Sounds like a good idea, this is possible in fact dokploy in early versions worked on a private network, that solutions looks simple and easy
