### ISSUE TITLE
Support environment variables in Stack configuration

### ISSUE THREAD

**Issue by medihack** [Dokploy/dokploy#594]
### What problem will this feature address?

Currently, only the "Docker Compose" method allows to specify environment variables. The "Stack" method doesn't have this configuration tab. I know this wasn't supported previously, but at least it works for us with a single node (we use Docker Swarm for the replicas).

### Describe the solution you'd like

There should be some way to inject environment variables into the Docker Swarm stack.

### Describe alternatives you've considered

I don't see a workaround, but I'm happy for some tips on handling this.

**Comment by Siumauricio** [comment]
This is a limitation of docker stack https://github.com/docker/cli/issues/939

However the `application` service works with docker swarm so anything works there.

**Comment by xenonwellz** [comment]
You can parse the env with `envsubst` which comes with the `gettext` package on almost every linux distros, please consider this. or guide me to create a pr

**Comment by Paillat-dev** [comment]
Would it be possible to reopen this issue as a feature request ? There are a number of ways to implement this feature, and it is quite limiting currently.

**Comment by jonhattan** [comment]
Done in #637
