### ISSUE TITLE
Dokploy internal postgres database is publicly accessible by default

### ISSUE THREAD

**Issue by libeanim** [Dokploy/dokploy#595]
### To Reproduce

1. Provision a new server e.g. on Hetzner
2. Ssh into the server
3. Run `curl -sSL https://dokploy.com/install.sh | sh`

#### Current behavior
1. Dokploy creates Postgres (and Redis) containers that are accessible from the outside:
   <img width="1091" alt="Screenshot 2024-10-26 at 00 28 52" src="https://github.com/user-attachments/assets/d051a657-30e6-45c8-b22b-0f3396575455">
2. The Postgres password is the default password `amukds4wi9001583845717ad2` as shown in the [.env.example](https://github.com/Dokploy/dokploy/blob/182f908c314f78ea25b5832a56f7d7dc7c75e5b1/apps/dokploy/.env.example)
3. Everyone can access the postgres database and read user data
   ![psql](https://github.com/user-attachments/assets/c7723325-668f-481a-b111-f86736296df8)
   ![psql2](https://github.com/user-attachments/assets/56f08201-2250-41c2-97f8-b0b3408fba29)

#### Expected behavior
1. Dokploy internal postgres is not accessible from the outside
2. The database password is newly (and securely) generated when dokploy is first deployed
(The same applies to the redis database)

### Provide environment information

```bash
Operating System:
   Debian 12
   amd65
```

### Which area(s) are affected? (Select all that apply)

Installation, Databases, Docker

### Additional context

- Setting [PublishedPort to `0`](https://github.com/Dokploy/dokploy/blob/182f908c314f78ea25b5832a56f7d7dc7c75e5b1/packages/server/src/setup/postgres-setup.ts#L39) does not lead to an unpublished service.
- The password seems to be hardcoded [here](https://github.com/Dokploy/dokploy/blob/182f908c314f78ea25b5832a56f7d7dc7c75e5b1/packages/server/src/setup/postgres-setup.ts#L15).

**Comment by Siumauricio** [comment]
Hello, it is strange that this had already been solved in previous versions, I think there was some regression I think, I'll check it!

**Comment by libeanim** [comment]
Great, thanks!

**Comment by Siumauricio** [comment]
The usage is `curl -sSL https://dokploy.com/install.sh | ADVERTISE_ADDR="192.168.1.100" sh` this will apply only to clean installations
