### ISSUE TITLE
Integrate with cloudflare to allow automatic DNS configurations

### ISSUE THREAD

**Issue by pedroramon** [Dokploy/dokploy#610]
### What problem will this feature address?

Currently, all deployed apps need to be configured externally to receive a DNS record.

### Describe the solution you'd like

Cloudflare has a REST api that allows you to create a DNS record. We can integrate with this to eneble auto DNS configurations.

### Describe alternatives you've considered

An alternative could be to add a bind service, but that would be a more complex feature.

**Comment by Siumauricio** [comment]
I would like to integrate this, but I want to keep dokploy unnopinionated, that is to say that it is not governed by any provider or service, 

If in the future I plan to do some integration that I see it very much from any point of view I will be happy to re-open this issue.

We can close that issue, Thanks!

**Comment by designorant** [comment]
Given Mauricio's comments, shall we rename this suggestion to: "Allow automatic DNS configurations via Domain Provider API"?

After all, there's plenty of DNS APIs out there:
- https://dns.hetzner.com/api-docs#tag/Records
- https://docs.digitalocean.com/reference/api/api-reference/#tag/Domain-Records

**Comment by rockiestar-com** [comment]
is that possible to define a plugin system so that folks can activate whatever they want?
