### ISSUE TITLE
Submodules cloning fails using GitHub provider

### ISSUE THREAD

**Issue by samdze** [Dokploy/dokploy#621]
### To Reproduce

1. Create an application using a GitHub provider selecting a repository with a private submodule owned by the same GitHub account.
2. Try to deploy the application.
3. Cloning of the submodule fails during deployment:
```
...

Receiving objects: 100% (60/60), 1.22 MiB | 8.92 MiB/s, done.
Submodule 'extensions/example-submodule-repo' (git@github.com:samdze/example-submodule-repo.git) registered for path 'extensions/example-submodule-repo'
Cloning into '/etc/dokploy/applications/example-app-a3525e/code/extensions/example-submodule-repo'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:samdze/example-submodule-repo.git' into submodule path '/etc/dokploy/applications/example-app-a3525e/code/extensions/example-submodule-repo' failed
Failed to clone 'extensions/example-submodule-repo'. Retry scheduled

...
```
https://github.com/Dokploy/dokploy/pull/575 added `--recurse-submodules` to git commands, but seems like it is not enough.
I tested with GitHub only, but this probably happens with GitLab and Bitbucket too.

### Current vs. Expected behavior

Cloning of the submodules should complete with no issues as long as the GitHub App has the rights to access the submodules repository.

### Provide environment information

```bash
Dokploy version 0.10.4
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

Cloning a repository without submodules works fine.
Cloning a repository with private submodules using the Git provider with an SSH key works fine.

**Comment by Siumauricio** [comment]
I think the references you have are ssh based so it makes sense that you can't download the repositories without having a private key to be able to authenticate, 

Internally we use HTTP to download repos by default, so if you have submodule references that are SSH they will fail, in this case I think you would be better off using GIT's source type.

Trying to solve this I think would make the code somewhat complicated in terms of handling these 2 cases, my recommendation would be that the submodule is based on https and not ssh in case you want to use the Github provider.

**Comment by Siumauricio** [comment]
Feel free to reopen if you need something else

**Comment by theboringhumane** [comment]
I'm on [Dokploy Canary](https://registry.hub.docker.com/layers/dokploy/dokploy/canary/images/sha256-336fdf57cb24488ff481f16cadc2fa3104f0e0827ef29d60459d3836d13027ce)

![50713](https://github.com/user-attachments/assets/4a137b92-32ce-40fe-8c74-604b17f40d1d)

**Comment by nengha** [comment]
> > I'm on [Dokploy Canary](https://registry.hub.docker.com/layers/dokploy/dokploy/canary/images/sha256-336fdf57cb24488ff481f16cadc2fa3104f0e0827ef29d60459d3836d13027ce) getting this error https [@Siumauricio](https://github.com/Siumauricio)
> > ![50713](https://private-user-images.githubusercontent.com/46974223/398739812-4a137b92-32ce-40fe-8c74-604b17f40d1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjE1NzUsIm5iZiI6MTczNTIyMTI3NSwicGF0aCI6Ii80Njk3NDIyMy8zOTg3Mzk4MTItNGExMzdiOTItMzJjZS00MGZlLThjNzQtNjA0YjE3ZjQwZDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDEzNTQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwYTY0NzM4ZmJhMmY2MzdmZWU3ODg2NGE0N2E3ZDRhYTZiYWY2YzExMWE2OGIzNmJmNzg5ZmJlZDlmODUwZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mHMHd8p7E3sPBhJe3gsM9-WOdN0Fm-L4LyTIFqqy1Bk)
> 
> ## If i give relative path this works
> 
> ![41580](https://github.com/user-attachments/assets/fe9c260d-8d15-4d47-811d-fa3d4f77ac82)

This works for me too. Thanks!
