### ISSUE TITLE
Memory leak on virtual machine

### ISSUE THREAD

**Issue by ValyaBabenkov** [Dokploy/dokploy#622]
### To Reproduce

Good afternoon.
I recently started using the Dokploy service.
The service worked for about 4 days, after which it stopped responding to requests with the Bad Gateway message.
Upon detailed analysis it was found that the memory on the virtual machine ran out.
<img width="1603" alt="Снимок экрана 2024-10-29 в 21 14 03" src="https://github.com/user-attachments/assets/55427eda-8f6b-4206-b75b-8256f9beaec0">
<img width="951" alt="Снимок экрана 2024-10-29 в 21 16 03" src="https://github.com/user-attachments/assets/cd7e4f4c-f5dc-4c4c-ad64-2a66ffd6f61d">

After clearing docker image with the command (sudo docker system prune -a), managed to get the service up.

During the observation, new postgres services were observed (screenshot in attachment)
<img width="1563" alt="Снимок экрана 2024-10-29 в 21 43 45" src="https://github.com/user-attachments/assets/3d15f135-7802-4382-8a6d-5e7c78bedee2">

### Current vs. Expected behavior

Can you please tell me how to fix the situation with memory leaks and running unnecessary postgres on a virtual machine?

### Provide environment information

```bash
Ubuntu 24.04
Cores - 2
Storage - 60GB
```

### Which area(s) are affected? (Select all that apply)

Docker

**Comment by Siumauricio** [comment]
I don't see any memory leak here, you simply ran out of space, make sure you enable docker cleanup in settings to prevent this, if you did a lot of deployments you may run out of space so the database can't write and goes into a block mode which is normal.

There is no solution here, other than to keep an eye on your storage.
