### ISSUE TITLE
Allow NGINX config editing

### ISSUE THREAD

**Issue by ohkimur** [Dokploy/dokploy#627]
### What problem will this feature address?

I'm trying to host next js as a static build using the nixpacks and the NGINX static server. However, according to nextjs [docs](https://nextjs.org/docs/app/building-your-application/deploying/static-exports) it's necessary to configure NGINX to handle `try_files` in a certain way.

### Describe the solution you'd like

Expose NGINX config

### Describe alternatives you've considered

none

**Comment by Siumauricio** [comment]
You can use File mounts to mount a nginx.conf to the container

**Comment by pipuwong** [comment]
Hi, 请问，Dokploy 如何设置nginx 的配置 ？
我通过Dokploy 部署了一个静态网站，我还设计了404 的页面，但是我在Dokploy 部署的网站，404 页面跳过去了nginx 的404而不是我设计的404。请问大佬知道这个如何解决吗？
![Uploading CleanShot 2024-12-01 at 00.34.48@2x.png…]()

**Comment by pipuwong** [comment]
Hi, 请问，Dokploy 如何设置nginx 的配置 ？
我通过Dokploy 部署了一个静态网站，我还设计了404 的页面，但是我在Dokploy 部署的网站，404 页面跳过去了nginx 的404而不是我设计的404。请问大佬知道这个如何解决吗？
<img width="489" alt="CleanShot 2024-12-01 at 00 34 48@2x" src="https://github.com/user-attachments/assets/cdce8297-5025-49e0-88b9-06378cd9f35a">

**Comment by Siumauricio** [comment]
This functionality is easily abstracted with mounts, where you can create an nginx.conf file and modify it, so I think we can close it since it is not necessary.

**Comment by JoshuaMichaelHanson** [comment]
> This functionality is easily abstracted with mounts, where you can create an nginx.conf file and modify it, so I think we can close it since it is not necessary.

If anyone wants specifics on how to do this please see this thread -> Its more on the Docker side but I left the answer I used for
[![Typing SVG](https://readme-typing-svg.herokuapp.com?font=Fira+Code&pause=1000&color=0E00F7&vCenter=true&width=435&lines=React+Router+SPA;---+Deep+Link+%2F+Refresh+---;Answer.....)](https://git.io/typing-svg)
[How To Use UI to customize .conf file](https://github.com/Dokploy/dokploy/issues/503#issuecomment-3533323280)

#503
