### ISSUE TITLE
Adding Email for password recovery

### ISSUE THREAD

**Issue by flutterde** [Dokploy/dokploy#63]
First of all, thank you for this amazing Paas, 
 have tried it and it's a game-changer,
I have you add a way to reset the password, through the Email by sending email recovery to the admin

**Comment by Siumauricio** [comment]
Thank you,for reseting the admin password you can run the following command 

`docker exec -it <container-id> bash -c "pnpm run reset-password"‘

**Comment by Siumauricio** [comment]
This was already added to the documentation so we can close for now.
