### ISSUE TITLE
Allow health check values to be string

### ISSUE THREAD

**Issue by egoist** [Dokploy/dokploy#636]
### What problem will this feature address?

Currently it only supports number, which is in nanoseconds:

```json
{
  "Test": [
    "CMD",
    "curl",
    "-f",
    "http://localhost:3000"
  ],
  "Interval": 30000000000,
  "Timeout": 10000000000,
  "StartPeriod": 30000000000,
  "Retries": 3
}
```

It's kinda confusing

### Describe the solution you'd like

Would be better if it support string as well to align with `HEALTHCHECK` in Dockerfile:

```json
{
  "Test": [
    "CMD",
    "curl",
    "-f",
    "http://localhost:3000"
  ],
  "Interval": "30s",
  "Timeout":"10s",
  "StartPeriod":"30s",
  "Retries": 3
}
```

### Describe alternatives you've considered

Well, just use number for now

**Comment by Siumauricio** [comment]
Honestly I would like to change it, but I prefer to keep the standard that docker uses and that is 1:1 what docker expects

when something is not clear about how it is used it is usually a good idea to check the API to know what value in what format it expects it.

https://docs.docker.com/reference/api/engine/version/v1.45/

For now we can close it.
