### ISSUE TITLE
Compose services ignore domain path setting

### ISSUE THREAD

**Issue by ignissak** [Dokploy/dokploy#648]
### To Reproduce

1. Deploy a compose service
2. Setup custom domain for this service under a specific path, e.g. `/api`
3. Try to make a request for `/`, it will work

### Current vs. Expected behavior

Expected: requests outside of the set path `/api` should not be redirected to the container
Actual: every request for the domain is redirected to the container

### Provide environment information

```bash
Ubuntu 24.04 LTS x86_64
Version: v0.10.9
```

### Which area(s) are affected? (Select all that apply)

Docker Compose, Traefik

**Comment by visualies** [comment]
@Siumauricio @ignissak To my knowledge Traefik does not support multiple rule entries like that instead it should be using && to concat the Host() and Pathprefix() rule. Traefik will just take the last rule entry (in my case the path) and apply it (pic below). This will also not support the "match longest first" rule as traefik likes to do when multiple routes contain similar paths.
![image](https://github.com/user-attachments/assets/19a3d8dc-060a-4c2f-9997-40e18735aad0)
