### ISSUE TITLE
Add support for mongodb replicaSets

### ISSUE THREAD

**Issue by mezotv** [Dokploy/dokploy#654]
### What problem will this feature address?

Not being able to easily add replication to mongodb which is required for example by prisma to do transactions

### Describe the solution you'd like

Adding support for replication out of the box, perhaps configurable in the advanced settings. 

### Describe alternatives you've considered

Another way to add a replicaSet to the mongodb instance without much hastle im open for options!

### Additional context

Prismas docker compose for replicas can be found here: https://github.com/prisma/prisma/blob/main/docker/docker-compose.yml#L178
Mongodbs guide: https://www.mongodb.com/docs/manual/tutorial/convert-standalone-to-replica-set/

**Comment by youyou-sudo** [comment]
I urgently need a solution for this because my Next.js project uses Prisma + MongoDB, and I need to initialize it through the startup command and configuration.

```
conf = {
   _id : "rs0",
   members: [
      { _id: 0, host: "<Internal Host>:27017" },
   ]
}
rs.initiate(conf)
```
I have set up a single-node replica set, but when connecting, I encounter issues where it doesn't connect properly (testing shows MongoDB without replica sets enabled connects fine).

I can use it normally in a 1panel or pure Docker environment, but I’m unsure how to configure the host parameter in rs.initiate(conf) under 'Internal Host' in Dokploy.

**Comment by mezotv** [comment]
> I urgently need a solution for this because my Next.js project uses Prisma + MongoDB, and I need to initialize it through the startup command and configuration.

We all in the same boat 🙏. Gotta wait for @Siumauricio to cook!

**Comment by mezotv** [comment]
Any updates on this being a thing as said before I was willing to pay for the development of it @Siumauricio!

**Comment by 2shrestha22** [comment]
> Any updates on this being a thing as said before I was willing to pay for the development of it @Siumauricio!

Yeah go ahead. It is worth donating for this project.

**Comment by mezotv** [comment]
> Yeah go ahead. It is worth donating for this project.

Im already donating money to the project every month but I cant fund a feature if @Siumauricio doesnt wanna add it.

**Comment by mezotv** [comment]
@youyou-sudo there is a pending pr now #926

**Comment by hhunterx** [comment]
Hi. Can someone explains how to configure the replicasets within dokploy? I see there is a new option, but when checked it do not connect. How/where can I put the configuration to links the clusters? and the private key?

**Comment by youyou-sudo** [comment]
@hhunterx 
> Hi. Can someone explains how to configure the replicasets within dokploy? I see there is a new option, but when checked it do not connect. How/where can I put the configuration to links the clusters? and the private key?

If you want to configure a single-node replica set, you can enable "Use Replica Sets" during creation — this will initialize the node.

After starting the container, open the Terminal, connect to MongoDB using `mongosh`, and run `rs.status()` to view the current node information. You’ll see that the node’s HOST is set to `127.0.0.1`. Use the following command to update the HOST to the one provided by Deploy.


```
// Get the current replica set configuration
cfg = rs.conf()

// Update the host of the first (and only) member to the desired hostname
cfg.members[0].host = "airport-test-awybcq:27017"

// Apply the updated configuration forcefully
// 'force: true' is required because you're changing the host of the current (self) node
rs.reconfig(cfg, { force: true })
```

The above is a single-node configuration.
If you plan to deploy a multi-server MongoDB setup, it's recommended to refer to the official MongoDB documentation.
