### ISSUE TITLE
Gitlab Oauth Scope(s) URL incorrect

### ISSUE THREAD

**Issue by tvarwig** [Dokploy/dokploy#655]
### To Reproduce

When installing a new Git Provider for Gitlab after filling out the Client ID, Secret, Est the redirect url is `https://gitlab.com/oauth/authorize?client_id=MYCLIENTID&redirect_uri=MYCALLBAKCURL&response_type=code&scope=api%20read_user%20read_repository` the `scope` query only works if I change to `scopes` with an `s` then the oauth works fine and gitlab installs

### Current vs. Expected behavior

I'm not sure why this is the case. The GitLab docs say `scope` not `scopes` as the query param from what I am reading. 

### Provide environment information

```bash
Operating System: Ubuntu 24.04 amd64, Dokploy v0.10.10, Bare Metal
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
Is strange did you select the 3 permissions we suggest in dokploy ?

**Comment by Siumauricio** [comment]
![image](https://github.com/user-attachments/assets/ad9575db-d5d0-47b7-82ba-4f2620ee95ec)

I tested now and is working fine

**Comment by tvarwig** [comment]
@Siumauricio yes I selected 
`api (Access the API on your behalf)`
`read_user (Read your personal information)`
`read_repository (Allows read-only access to the repository)`

I find it strange too,

**Comment by Siumauricio** [comment]
https://github.com/user-attachments/assets/02236a75-8426-42bd-9a18-b5094be2dcfd

**Comment by tvarwig** [comment]
@Siumauricio  thank you for looking into this. I have multiple groups on gitlab. I tried a different group and everything worked as normal. I deleted the GitLab Provider for my first group and tried again and am getting invalid scope error again unless i change `scope` to `scopes`. It must be something with my GitLab group name. I will look into this further. Appreciate it
