### ISSUE TITLE
Getting 404 or Gateway Timeout when trying to access a server via a domain using compose

### ISSUE THREAD

**Issue by bcastillo-2022474** [Dokploy/dokploy#656]
### To Reproduce

create a compose server app
attempt to create a domain
choose your domain name or generate one
<img width="384" alt="Screenshot 2024-11-06 at 00-41-44 Dokploy" src="https://github.com/user-attachments/assets/99537239-7650-4347-b281-91fbb22b194c">

it doesnt matter if you enable `HTTPS` or not.
Deploy your application

### Current vs. Expected behavior

Sometimes it will work, sometimes it won't, when it works, usually after 10 min it stops working, it either gives 404 page not found error, or it gives gateway timeout 504 error, or 502 error. 
![Screenshot 2024-11-06 004611](https://github.com/user-attachments/assets/edda88c4-e790-420f-98b1-148ddccf59d4)

Im sure the application is being deployed as expected because if I use the IP directly it works
![Screenshot 2024-11-06 005255](https://github.com/user-attachments/assets/5dc25ef6-f265-4484-8123-cf55aa26cd24)

### Provide environment information

```bash
im using an Hetzner VPS with ubuntu


PRETTY_NAME="Ubuntu 24.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.1 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

Im deploying a simple api written in typescript, nothing fancy
```


### Which area(s) are affected? (Select all that apply)

Application, Traefik

### Additional context

Docker version 27.3.1, build ce12230
Ubuntu 24.04.1 LTS

**Comment by Siumauricio** [comment]
Can you create a minimal reproducible?

**Comment by bcastillo-2022474** [comment]
> Can you create a minimal reproducible?

I Tried this with 2 different projects, I was trying to upload a fairly little app

One of them is this:  https://github.com/bcastillo-2022474/todo-list-darapti-backend.git

You just have to set up the env variables and create compose deployment using docker-compose

But like I told you, sometimes works, but when you either update the domain and deploy again it throws error, and like I said, I know the deployment works because I used the IP directly with the PORT and it worked, but when using the domain it does not

**Comment by Siumauricio** [comment]
I don't see anything wrong, for me is working I think you are doing something wrong 

I recommend to read this https://docs.dokploy.com/en/docs/core/troubleshooting/overview#docker-compose-domain-not-working and https://docs.dokploy.com/en/docs/core/docker-compose/domains


I updated the compose file to this 


```yaml
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432 # default postgres port
      DB_NAME: ${DB_NAME}
      PORT: 4000
```

you can see the fork here https://github.com/Siumauricio/todo-list-darapti-backend/tree/master
![Screenshot 2024-11-06 at 10 41 32 PM](https://github.com/user-attachments/assets/0379975f-239a-40d1-8bd9-ba3f2397eb8a)

![Screenshot 2024-11-06 at 10 41 17 PM](https://github.com/user-attachments/assets/4d7a8627-6fa0-4a18-82ac-6193c72f9249)
![Screenshot 2024-11-06 at 10 41 24 PM](https://github.com/user-attachments/assets/dc7cf55c-4779-4f79-93d0-f2a40837a560)

The postgres database I've created
![Screenshot 2024-11-06 at 10 41 55 PM](https://github.com/user-attachments/assets/eb91f543-d7e8-4658-a7a9-f02bed7c4918)


![Screenshot 2024-11-06 at 10 42 10 PM](https://github.com/user-attachments/assets/cd3e2410-f5b2-43e1-9d63-60a7b15e93e1)
