### ISSUE TITLE
Properly parse environment variables

### ISSUE THREAD

**Issue by manjime83** [Dokploy/dokploy#66]
When setting up environment variables that contain special characters like the equals sign, the environment variable may not be parsed correctly. For instance, the environment variable `DATABASE_URL` with the following value:

```
DATABASE_URL="postgresql://user:password@host/db?sslmode=require"
```

may be truncated to:

```
DATABASE_URL="postgresql://user:password@host/db?sslmode
```

when accessed inside the container. This can cause issues in your application. To fix this problem, you need to update the `prepareEnvironmentVariables` function to properly parse the environment variables.

**Comment by manjime83** [comment]
I noticed that the project uses dotenv, so the function can easily be replaced by:

server/utils/docker/utils.ts
```
import { parse } from "dotenv";

const prepareEnvironmentVariables = (env: string | null) =>
  Object.entries(parse(env ?? "")).map(([key, value]) => `${key}=${value}`);
```

**Comment by Siumauricio** [comment]
@manjime83 thank you and yeah there's definitely a bug in the env parsing in some cases, would you mind sending a PR?

**Comment by manjime83** [comment]
Here is the PR: https://github.com/Dokploy/dokploy/pull/67
