### ISSUE TITLE
How to set restart policy to unless-stopped or no?

### ISSUE THREAD

**Issue by iamyegor** [Dokploy/dokploy#671]
### To Reproduce

My database migrator application keeps restarting after it finishes, which is, obviously, isn't the desired behavior. I need to somehow fix this behavior by, for example, setting restart policy to unless-stopped or no. 

### Current vs. Expected behavior

Currently, applications keeps restarting, but it needs to be stopped.

### Provide environment information

```bash
Operating System: Debian 12
Cloud Provider: Timeweb Cloud
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
Let's keep the conversation on #670
