### ISSUE TITLE
Github logo not available

### ISSUE THREAD

**Issue by jujur10** [Dokploy/dokploy#672]
### To Reproduce

1. Select White theme (Light theme).
2. Navigate into projects.
3. Navigate into project settings.
![image](https://github.com/user-attachments/assets/0fd5dd78-1f57-412a-af1e-0d5ce6b3c6ad)

### Current vs. Expected behavior

The github logo is not available, it should be visible.

### Provide environment information

```bash
No.
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by AprilNEA** [comment]
# Git Providers of Settings
<img width="762" alt="image" src="https://github.com/user-attachments/assets/c17659d7-362b-4847-ae8e-9b924a7ad6d1">
<img width="751" alt="image" src="https://github.com/user-attachments/assets/11c1698a-5555-4d3e-a738-05fdae67452d">
