### ISSUE TITLE
IP address doesn't update (it's showing an old external ip the server had during installation, is it hard coded?)

### ISSUE THREAD

**Issue by znowfox** [Dokploy/dokploy#692]
### To Reproduce

install dokploy
change external ip
witness the sacrilegial missinformation =)

### Current vs. Expected behavior

Needs to show current ip address, could be cached, parsed live, parsed on update, parsed periodically...

### Provide environment information

```bash
ubuntu server
dedicated server @ovh
```

### Which area(s) are affected? (Select all that apply)

Application

**Comment by Siumauricio** [comment]
What do you mean by change internal Ip? Please be more descriptive, give steps to reproduce

**Comment by znowfox** [comment]
Mate : 
![image](https://github.com/user-attachments/assets/d5546c67-67c5-42ef-8f0d-8b1795d1446b)
this doesn't reflect the ip address of the server where the ui is running.

**Comment by znowfox** [comment]
![image](https://github.com/user-attachments/assets/a58e3f87-42c8-4d18-bf12-c19e0164e9ef)

**Comment by znowfox** [comment]
That IP, is not the current ip of the host!

**Comment by Siumauricio** [comment]
if you changed the IP for any reason, the ip will not change because at the moment  of register it save your actual IP, this is not a bug, if you want to change the IP to a new one you can do entering to the database container and updating the value for now

**Comment by Siumauricio** [comment]
Yeah lets make as a feature request, if you want to solve your issue you can see this discussion is basically the same problem https://github.com/Dokploy/dokploy/discussions/369#discussioncomment-10422413

**Comment by znowfox** [comment]
> Yeah lets make as a feature request, if you want to solve your issue you can see this discussion is basically the same problem [#369 (comment)](https://github.com/Dokploy/dokploy/discussions/369#discussioncomment-10422413)

Yes that works, for the others, the psql user is "dokploy"

**Comment by kdurek** [comment]
Gonna take care of this :D

**Comment by kdurek** [comment]
https://github.com/Dokploy/dokploy/pull/714

**Comment by znowfox** [comment]
Hey, would like to re-open, you've added the swarm view and in there the ip is still wrong (well, it's the installation ip), happened on the same instance.

**Comment by designorant** [comment]
@znowfox I'm not sure what @Siumauricio meant by digging into database container, but the Swram IPs are here:

```
/var/lib/docker/swarm/docker-state.json
/var/lib/docker/swarm/state.json
```

**Comment by designorant** [comment]
```
/var/lib/docker/swarm/docker-state.json
/var/lib/docker/swarm/state.json
```

**Comment by vantezzen** [comment]
I tried to restore a backup on a different server but this still seems to cause issues.

For anybody coming here from Google, try:

```sql
docker ps | grep dokploy-postgres
# Note down the ID at the start of the line
docker exec -it (the docker container id) bash
psql --user dokploy
UPDATE "webServerSettings" SET "serverIp" = '123.123.123.123';
exit
exit
reboot
```

For me that fixed it, including the Docker Swarm stuff
