### ISSUE TITLE
Setting up Registry with ghcr.io

### ISSUE THREAD

**Issue by sebastianarena** [Dokploy/dokploy#699]
### To Reproduce

I'm having trouble setting up the registry to use ghcr.io using my username and a token (classic) that I created for this specific purpose

1. If I set it up like this:

![registry-1](https://github.com/user-attachments/assets/5fb2deb8-37e6-446f-a983-1a3843e85762)

I will get the following error

<img width="836" alt="registry-2" src="https://github.com/user-attachments/assets/c6a15e71-aa8e-4e02-8688-045d2e776611">

Is it trying to upload to docker.io even though I configured something else?

2. Also if I try to put my Github Org Name as an image prefix, it will try to use that as the actual registry URL (I blurred my org name in the pictures)

![registry-3](https://github.com/user-attachments/assets/b45e5731-c033-4bd0-8002-692202ae8c9a)

![registry-4](https://github.com/user-attachments/assets/d3d1efcf-4475-4eb9-ac34-c04f55de2132)

Thanks for this amazing product

### Current vs. Expected behavior

The image is uploaded to ghcr.io

### Provide environment information

```bash
Operating System: Ubuntu 24.04 LTS
Dokploy: 0.10.10
VPS: Hetzner
```

### Which area(s) are affected? (Select all that apply)

Installation, Docker

**Comment by Siumauricio** [comment]
It seems that the dns resolution was modified on the server for some reason. 

https://github.com/docker/for-mac/issues/1317

Recently I added steps for add ghcr account however I didn't have any issues, I will check but it seems like is more a dns error from the host

https://docs.dokploy.com/docs/core/registry/ghcr

**Comment by ouestlabs** [comment]
> @Siumauricio thanks for the reply
> 
> I can't seem to make it work no matter what I do.
> 
> Here's an abstract of what it says when trying to upload it
> 
> ```
> 📦 [Enabled Registry] Uploading image to cloud | <redacted>:latest | https://ghcr.io
> WARNING! Using --password via the CLI is insecure. Use --password-stdin.
> WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
> Configure a credential helper to remove this warning. See
> https://docs.docker.com/engine/reference/commandline/login/#credential-stores
> 
> Login Succeeded
> The push refers to repository [docker.io/library/<redacted>]
> a2058383e5e0: Preparing
> 2a28034070b4: Preparing
> d129a0daa9ce: Preparing
> 172e602b0dc5: Preparing
> 14c33253c409: Preparing
> 58b2036d19a8: Preparing
> e5174df11535: Preparing
> 75654b8eeebd: Preparing
> e5174df11535: Waiting
> 75654b8eeebd: Waiting
> 58b2036d19a8: Waiting
> denied: requested access to the resource is denied
> Error ❌
> denied: requested access to the resource is denied
> ```
> 
> As you can see, it says Login Successful, even testing like your docs says, shows a success, but later it fails.
> 
> I don't know why it says docker.io when it should be ghcr.io? or maybe that is correct because its just the name of the image?
> 
> Adding a prefix changes the path from `/library/` to `/prefix/` I don't think it's DNS otherwise it would fail login as well And the curious thing I noticed was that if I used my Github ORG name as a prefix (assuming it would upload the packages to my org not my username) shows the DNS error, like it's confusing which API to use if the Prefix = ORG name, which is weird.
> 
> Don't know what else to try. Let me know if this helps. Thanks.

try to remove the protocol  in the url, it should look like : `ghcr.io/your_image`

**Comment by Siumauricio** [comment]
@ouestlabs Good catch, very probably is because they are using https at the start of the registry url

**Comment by Polluxs** [comment]
> @ouestlabs Good catch, very probably is because they are using https at the start of the registry url

I had the same issue and it was indeed the protocol (which is also in the example of the docs): [docs](https://docs.dokploy.com/docs/core/registry/ghcr)

If I got some time I'll open a PR to fix (seems better than updating the docs?).

**Comment by Siumauricio** [comment]
Docs updated!
