### ISSUE TITLE
Redirect feature not working

### ISSUE THREAD

**Issue by calliduslabs** [Dokploy/dokploy#712]
### To Reproduce

I am trying to www to non-www but i received a "404 page not found" on the browser Same happens to non-www to www. 

As discussed on Discord I was able to get it working days ago without the double $ on regex but it's not working anymore.

### Current vs. Expected behavior

I expected to have a redirect working.

### Provide environment information

```bash
Using only one domain on the application.
```

### Which area(s) are affected? (Select all that apply)

Application

### Additional context

I tested with dedicated serveron the last dokploy version.

**Comment by Siumauricio** [comment]
I tested this now, on both sides and is working fine, just removing the $ sign on the replacement
