### ISSUE TITLE
Feature: Application Templates

### ISSUE THREAD

**Issue by DarkPhoenix2704** [Dokploy/dokploy#73]

**Comment by Siumauricio** [comment]
This will be easily to implement with #17

**Comment by Siumauricio** [comment]
> > This will be easily to implement with #17这可以通过 #17 轻松实现
> 
> Can you create a Discord channel? I find it very convenient for discussion!

Good idea!

I will create a channel for this specific feature

**Comment by Siumauricio** [comment]
@omakise I created a category `feature-request` and two text chat 1 for docker compose and the other for multi node support

**Comment by Siumauricio** [comment]
#111 Done
