### ISSUE TITLE
Project Env UX improvements

### ISSUE THREAD

**Issue by verekia** [Dokploy/dokploy#733]
### What problem will this feature address?

Currently, the shared project env is only accessible from a dropdown that says "Add Env" on the projects list page.

### Describe the solution you'd like

- Instead of "Add Env" in the dropdown, I think it should be "Project Environment"
- The project env modal should be accessible from the project page, not just the home dashboard page
- The phrasing in the modal could be simplified.

<img width="506" alt="Screenshot 2024-11-20 at 12 02 38" src="https://github.com/user-attachments/assets/72112fab-264a-4d51-b3d3-39a6b2702cdb">

<img width="1364" alt="Screenshot 2024-11-20 at 12 05 03" src="https://github.com/user-attachments/assets/4ac4f652-7e8f-4a97-a40c-05c293fe600d">

<img width="1247" alt="Screenshot 2024-11-20 at 11 59 38" src="https://github.com/user-attachments/assets/37c3159e-6fb0-4bae-a8ed-9d0d33cf70d3">

Environment variables that are accessible to all services of this project.
Use this syntax to reference project-level variables in your service environments: DATABASE_URL=${{project. DATABASE_URL}}

### Describe alternatives you've considered

See suggestions above.

**Comment by kerimovok** [comment]
I love this!
