### ISSUE TITLE
Code editor for file mounts

### ISSUE THREAD

**Issue by kerimovok** [Dokploy/dokploy#738]
### What problem will this feature address?

I want to be able to make changes easily to my file mounts without opening my local IDE

### Describe the solution you'd like

Implement the same thing as for the ENV variables editor

### Describe alternatives you've considered

Use local IDE

**Comment by Siumauricio** [comment]
I wonder what VS Code has to do with dokploy?

**Comment by kerimovok** [comment]
Not VSCODE itself, but code editor like in Environment variables editor. Because, when editing yaml configs in file mounts it is not comfortable
