### ISSUE TITLE
In the contribution documentation description, the reset password statement is incorrect.

### ISSUE THREAD

**Issue by hehehai** [Dokploy/dokploy#74]
![](https://github.com/Dokploy/dokploy/assets/12692552/09b567e3-5d63-41f6-abb7-2e4721b84bf2)

https://github.com/Dokploy/dokploy/blob/canary/CONTRIBUTING.md#password-reset

Should this be `reset-password`?

Can I submit a PR?

**Comment by hehehai** [comment]
I just saw the role of build-server, sorry

**Comment by Siumauricio** [comment]
Go ahead and thank you!
