### ISSUE TITLE
Missing Service в VDS Dokploy (Application)

### ISSUE THREAD

**Issue by ValyaBabenkov** [Dokploy/dokploy#745]
### To Reproduce

Relatively recently I deployed Dokploy service, two services (BD, Application) on a virtual machine.

After a few days of work, I discovered that Application was missing from the service.
But if you look in Project->Docker menu, two running containers (BD, Application) are displayed, attached screenshot.

I would be grateful if you could help me to solve this case

![test](https://github.com/user-attachments/assets/cb8b6c79-9ed1-4b64-98d2-8f225ac91ef0)

### Current vs. Expected behavior

Dokploy personal cabinet shows created services, from which you can manage

### Provide environment information

```bash
OS Ubuntu 24.04 LTS
Dockploy Version: v0.9.4
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

**Comment by Siumauricio** [comment]
Please add some steps to reproduce this, I have applications more than 6 months running and no problems, feel free to reopen when you add the necessary steps to reproduce the problem
