### ISSUE TITLE
Requests Distribution

### ISSUE THREAD

**Issue by rchaud** [Dokploy/dokploy#751]
### To Reproduce

Domain DNS at Cloudflare.
Created App(NextJs) or Template(Pocketbase)
Add subdomain.
Requests do not get updated.

### Current vs. Expected behavior

Expect to see a request come in for each site request.

### Provide environment information

```bash
Ubuntu 24.04
Dokploy v0.12.0
```

### Which area(s) are affected? (Select all that apply)

Traefik

### Additional context

No matter what I do I cannot get Requests logs or chart to get new requests. I have tried DNS Only or Procy i Cloudflare, HTTP or HTTPS in the domain. This seems to be a hit or miss, I get it to work for a minute but after it doesnt seems to continue to work. I have given up on logs at this point. Has anyone experience this same issue?

**Comment by Siumauricio** [comment]
All logs are trapped by traefik, if traefik decides not to save them it will be for some reason, dokploy simply reads the requests logs that traefik generates.

https://doc.traefik.io/traefik/observability/logs/

**Comment by Siumauricio** [comment]
This not a issue from dokploy itself, since we use directly what traefik offers, so in this case the issue should arise to traefik repo
