### ISSUE TITLE
Dokploy UI Duplicate Deployments

### ISSUE THREAD

**Issue by fishtn** [Dokploy/dokploy#754]
### To Reproduce

I have a Dokploy UI Server and a Remote Server.

On the Remote Server, I have three applications currently deployed:

1. Service A using Application  with docker provider
2. Service B using docker compose
3. Redis Database

![1732417477970](https://github.com/user-attachments/assets/be51f044-2b7b-401c-bf64-c0f9652c09e4)

### Current vs. Expected behavior

Service B and Redis have been deployed duplicately in Dokploy UI.

![1732417288629](https://github.com/user-attachments/assets/80fc63cf-7f56-42db-8f5a-d067c49874f4)

Remote Server Docker containers are displayed incompletely, Redis container is not showing up.

![1732417444621](https://github.com/user-attachments/assets/7be8d287-e8e6-4d92-b9e1-9e79f8b138a0)

### Provide environment information

```bash
os:Ubuntu 24.04.1
Dokploy version: v0.12.0
VPS Provider: Hetzner
What applications/services are you tying to deploy?
Redis,Nextjs App,Nodejs
```

### Which area(s) are affected? (Select all that apply)

Application, Databases, Docker

**Comment by Siumauricio** [comment]
the only way to deploy the application in the same dokploy server is you didn't choose any server when you created the redis database, can you enter to the redis instance and share screenshot?

**Comment by fishtn** [comment]
The Redis configuration is fine, I was mistaken about that. The worker project has a duplicate deployment situation - one deployment is on the remote server, while another copy is deployed again on the Dokploy UI.
![1732471807110](https://github.com/user-attachments/assets/a8fd9334-a151-4a91-99b1-b704f4acc250)

**Comment by Siumauricio** [comment]
I got confused, can you explain the problem again?

and if you have a way to reproduce it would be great.

**Comment by Siumauricio** [comment]
Thank you I was able to reproduce, in the next version will be fixed

**Comment by fcastrovilli** [comment]
Hey i'm still hitting this issue on latest dokploy version. I'm running an automated Dockerfile build that has a GitHub repo as source (using dokploy generated git app). All the builds remain freezed forever and some times with no git event at all a new running deployment is shown in the UI. The Dockerfile is trying to build a Nextjs 15 app. Would be nice to have at least something like a "Stop deployment" button. @Siumauricio

**Comment by zx88cvb** [comment]
> Hey i'm still hitting this issue on latest dokploy version. I'm running an automated Dockerfile build that has a GitHub repo as source (using dokploy generated git app). All the builds remain freezed forever and some times with no git event at all a new running deployment is shown in the UI. The Dockerfile is trying to build a Nextjs 15 app. Would be nice to have at least something like a "Stop deployment" button. [@Siumauricio](https://github.com/Siumauricio)
> 
> Looking at the logs, the dokploy app is actually crushing at some point and when it revives a new deployment is started.
> 
> ```
> Starting Deployment Worker
> Build dockerfile: ✅
>  ELIFECYCLE  Command failed.
> ```

I also encountered this problem
