### ISSUE TITLE
Traefik labels in UI

### ISSUE THREAD

**Issue by kerimovok** [Dokploy/dokploy#762]
### What problem will this feature address?

I don't want to put traefik labels in my project repos, because not everyone uses traefik/dokploy

### Describe the solution you'd like

It would be great to be able to add custom labels in the UI and apply them.
On tech sides, traefik API can be used to dynamically add labels

### Describe alternatives you've considered

Currently, I am creating 'dokploy' branch for this

**Comment by TheOnlyWayUp** [comment]
@kerimovok Under Advanced, there's a place for you to modify your traefik configuration for a particular service
![image](https://github.com/user-attachments/assets/df835ea0-c1da-4ee4-85c0-97b40562fea9)

Scroll to the bottom and give it a shot?

**Comment by kerimovok** [comment]
Yes, I just discovered it yesterday and wrote about it here https://github.com/Dokploy/dokploy/discussions/791#discussion-7584631.

It is only available in 'Application' types of services (which is logical, because it is designed for the single container).
The same thing for dokploy network, applications are automatically added to dokploy network here.

I would probably close these issues.

Thank you.
