### ISSUE TITLE
Registry with ghcr.io Failed (error 500)

### ISSUE THREAD

**Issue by juandl** [Dokploy/dokploy#766]
### To Reproduce

1. Add registry, as it mentioned here: https://docs.dokploy.com/docs/core/registry/ghcr
![image](https://github.com/user-attachments/assets/acaad4b6-000d-4914-a504-0253ab735353)

2. Add image details in Deployment.
![image](https://github.com/user-attachments/assets/e8ca3f31-d53f-470d-90f8-3cf58bc5fa6c)

### Current vs. Expected behavior

It shows this error 
![image](https://github.com/user-attachments/assets/729e1f04-d8f3-460f-9982-b267bb156cb9)

### Provide environment information

```bash
Operating System: Ubuntu 24.04 LTS
Dokploy: v0.12.0
VPS: Azure
```

### Which area(s) are affected? (Select all that apply)

Docker

**Comment by Siumauricio** [comment]
Can you try to remove the https:// in the registry url?

**Comment by juandl** [comment]
@Siumauricio I tried that and even a new VPS to see if that will help and same problem :/

**Comment by Siumauricio** [comment]
Did you remove the https:// and then click again on test connection?

**Comment by Siumauricio** [comment]
And can you follow this steps?

https://github.com/Dokploy/dokploy/issues/528#issuecomment-2398678926

**Comment by juandl** [comment]
![image](https://github.com/user-attachments/assets/ebb82b83-5f40-40a8-82c8-bb4dace04f59)
![image](https://github.com/user-attachments/assets/36380d98-b027-48f7-a6d4-cba9429280b8)
![image](https://github.com/user-attachments/assets/1fff591e-258a-4ea2-be0a-388c88f17fdf)


Same steps @Siumauricio

**Comment by juandl** [comment]
I create a new server and try again from clean setup and same issue

**Comment by juandl** [comment]
![image](https://github.com/user-attachments/assets/4117f20b-b9f5-498a-8465-c8ca1981ff07)
Here server logs

**Comment by Siumauricio** [comment]
Ok, so I figure out what was the issue, In the next version will be available this fix

**Comment by juandl** [comment]
Thank you!! @Siumauricio
