### ISSUE TITLE
Elasticsearch - New DB Template

### ISSUE THREAD

**Issue by RDN794312** [Dokploy/dokploy#769]
### What problem will this feature address?

Setting up `Elasticsearch` can be complex and time-consuming, especially for those unfamiliar with its configuration. This feature will make it easier to deploy `Elasticsearch` by providing a ready-to-use template.

### Describe the solution you'd like

I would like dokploy to include a pre-configured Elasticsearch template that can be easily deployed with minimal setup. The template should support common deployment scenarios, such as single-node setups for development and multi-node clusters for production. It should also allow basic customization, such as adjusting memory, storage, and shard settings, while following best practices for Elasticsearch configuration.

### Describe alternatives you've considered

Manual Setup: Manually configuring and deploying Elasticsearch using Docker Compose. However, this approach is time-consuming, prone to errors, and requires knowledge of Elasticsearch's configuration details.

**Comment by asanoviskhak** [comment]
I also would love to see the Elasticsearch template. Thanks!
