### ISSUE TITLE
Docker Compose project: Domain Changes Require Redeployment

### ISSUE THREAD

**Issue by fishtn** [Dokploy/dokploy#797]
### To Reproduce

1. Deploy a project using Docker Compose
2. Add a new domain or modify existing domain settings
3. Domain changes will not take effect until the project is redeployed

### Current vs. Expected behavior

When deploying a project using Docker Compose, adding new domains or modifying existing domain settings do not take effect immediately. A redeployment is required for any domain additions or modifications to be applied.

### Provide environment information

```bash
Operating System:
  OS:Ubuntu 24.04
Dokploy version: v0.13.1
VPS Provider: Hetzner/Netcup
What applications/services are you tying to deploy?
Nodejs api
```

### Which area(s) are affected? (Select all that apply)

Docker Compose, Remote server, Local Development

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
This is the expected behavior because is how docker compose works with traefik
