### ISSUE TITLE
Question:How do I expose Dokploy using Cloudflare Tunnel?

### ISSUE THREAD

**Issue by yoni13** [Dokploy/dokploy#80]
After setting up the Cloudflare tunnel and adding the domain in settings, visiting the URI proxies with Cloudflare tunnel will return an 'ERR_TOO_MANY_REDIRECTS' error.
Tunnel settings: http://localhost:3000
Dokploy Settings:dokploy.domain.tld, certificate:None

**Comment by Ghastly2001** [comment]
SSL/TLS Misconfiguration:
This is a common cause. Check your Cloudflare settings:

SSL/TLS Encryption Mode: Make sure it's set to "Full (Strict)" or higher. This ensures Cloudflare receives HTTPS requests and avoids conflicts with your origin server (Dokyploy) potentially redirecting to HTTPS.
Dokyploy Redirects:
Investigate Dokyploy's redirect configuration. If Dokyploy automatically redirects all HTTP traffic to HTTPS, it might cause a loop with Cloudflare's settings. Consider disabling redirects on Dokyploy or setting them to redirect only if the request isn't already HTTPS.
Cloudflare Firewall Rules:
Unintended firewall rules in Cloudflare might be causing redirects. Double-check your firewall rules for any entries that might be interfering with the traffic flow.
Here are some resources to help you further:

Cloudflare Docs on "ERR_TOO_MANY_REDIRECTS": https://developers.cloudflare.com/ssl/troubleshooting/too-many-redirects/
Troubleshooting SSL with Cloudflare Tunnels: https://community.cloudflare.com/t/how-to-configure-cloudflare-tunnel-for-https-traffic/391972
Additional Tips:

Clear Cache: Clear your browser cache and Cloudflare cache to ensure you're not seeing a cached version with redirect issues.
Temporarily Bypass Cloudflare: Try temporarily bypassing Cloudflare for your domain by pausing Cloudflare in the settings. If the error disappears, it confirms an issue with Cloudflare's configuration.

**Comment by yoni13** [comment]
Looks like I screwed some settings on both sides
And after tweaking some settings, everything started to work.
I have no idea how it works,but since it works now,I am closing the issue.

**Comment by Ghastly2001** [comment]
Glad to hear that it worked!
