### ISSUE TITLE
detect mounted volumes in filesystems

### ISSUE THREAD

**Issue by tiero** [Dokploy/dokploy#81]
I have a Hetzner VM to which I have attached and mounted a 512GB volume to `/dev/sda`        

ie. 
```
/dev/sda        503G   28K  478G   1% /mnt/HC_Volume_100724042
```

It would be super helpful to have DockPloy to recognize this extra space to be used for extra services storage.

Only 160GB base disk is seen

<img width="658" alt="image" src="https://github.com/Dokploy/dokploy/assets/3596602/6c2f7968-64c2-4da5-8b9b-b220a455533f">

**Comment by Siumauricio** [comment]
I will need to try this, we extract the size based on `/` path https://github.com/Dokploy/dokploy/blob/canary/server/monitoring/utilts.ts#L48

**Comment by tiero** [comment]
I see. It may be worth look for all mounted volumes and sum their free space? Not sure how easy is to list mounted volumes on the OS

**Comment by Siumauricio** [comment]
I can take a look to see if we can get all the volumes mounted and then add them all up, for now let's keep it open

**Comment by Siumauricio** [comment]
I think we can close this issue, this is not something that dokploy itself controls, dokploy only reads what docker gives it, if it does not detect it I guess it is some configuration outside of dokploy
