### ISSUE TITLE
Add Kimai time tracker template 

### ISSUE THREAD

**Issue by faeztgh** [Dokploy/dokploy#811]
### What problem will this feature address?

It's good to have open source time tracker like `Kimai` in templates.

### Describe the solution you'd like

[https://www.kimai.org/](https://www.kimai.org/)

### Describe alternatives you've considered

[https://www.kimai.org/](https://www.kimai.org/)

### Will you send a PR to implement it?

No

**Comment by drudge** [comment]
Submitted PR here https://github.com/Dokploy/dokploy/pull/838

**Comment by faeztgh** [comment]
> Submitted PR here #838.

Thanks man.
