### ISSUE TITLE
Environment improvements

### ISSUE THREAD

**Issue by Timtaran** [Dokploy/dokploy#813]
### What problem will this feature address?

You can't manage multiple .env files and it's paths

### Describe the solution you'd like

Add availability to create multiple .env files with custom path

UPD. also it will be cool if user can create not only .env files 

### Describe alternatives you've considered

commit .env to git repo (unsafe)

### Will you send a PR to implement it?

No

**Comment by kerimovok** [comment]
I guess, you can use file mounts as a workaround for now, without committing `.env` to git repo
https://docs.dokploy.com/docs/core/applications/advanced#volumesmounts

**Comment by Siumauricio** [comment]
I do not consider that we should have multiple .env files, since an application is basically an instance or a single entity, if for some reason you need different files envs, I think you can use the suggestion of @kerimovok which are basically using mounts which can serve for the same purpose
