### ISSUE TITLE
Prevent Docker terminal window from closing unwantedly when Esc key is pressed

### ISSUE THREAD

**Issue by pshemek** [Dokploy/dokploy#818]
### What problem will this feature address?

There are use cases when we need use Esc key within the terminal, however, currently the popup gets closed.

### Describe the solution you'd like

I am not sure. Maybe the UI should ask if I want to close the terminal or execute the “Esc” key event. Or better, when the focus is within the terminal window, Esc should act within it.

### Describe alternatives you've considered

Since I have this problem in the vim editor, I searched for an alternative to the Esc key to exit insert mode, but did not find one.

### Will you send a PR to implement it?

No

**Comment by 190km** [comment]
Hey, we can do that by showing a dialog that says "Are you sure you want to close the terminal ?". I will make a PR right now.

**Comment by 190km** [comment]
https://github.com/Dokploy/dokploy/pull/820

**Comment by Siumauricio** [comment]
Thanks @190km
