### ISSUE TITLE
Clarify dokploy is *not* open-source and *not* Apache licenses

### ISSUE THREAD

**Issue by anders-code** [Dokploy/dokploy#82]
Adding restrictions via "appendixes" to a recognized Open-Source license is not an appropriate way to create a non-free license. Please remove references to Open-Source or Apache from this repo. Or, even better, properly open-source it without restriction. For example you might want to move non-free parts to a different repo with a different, appropriate license.

The current situation is a violation of Apache copyright and trademark. Further it is certainly misleading and could be considered fraudulent if you appear to be claiming this is "Open-Source" when it is not and you are benefiting from this false association.

It is fine to have a commercial non-open-source license, but if that is so, you must make this clear. Restrictions on commercial use, changes, etc. are not compatible with open-source nor Apache. This would be an inappropriate license to use if that is what is intended.

See: https://www.apache.org/foundation/license-faq.html#mod-license

```diff
You may re-use our license unchanged, and also modify it.

If you modify it, you are on your own from a legal point of view, and the result is NOT the Apache License, just a new license inspired by ours.

-This means that the terms 'Apache License', 'Apache', and any similar references to the ASF cannot appear in your modified license, other than to state that it differs from the original.

-Also, you cannot use 'Apache' in the name of the modified license. Names like "Apache License with such-and-such clause", for example, are not acceptable, as they cause confusion.

Creating a new license is a non-trivial task. If you do that we recommend that you get your own legal advice.

**Comment by Siumauricio** [comment]
I answer you with what I answer to another person: with the license it is something that you cannot go against what I think, what I want to do or what I say.

It's as simple as that, I don't understand why you get mortified about something, people are happy with this software, they use it in their products and only people like you who don't even use it, come to cry just because they want to be right.

**Comment by anders-code** [comment]
you do not understand. it is perfectly fine to have whatever license you wish.

BUT you cannot call it open-source or Apache if it is like this.

**Comment by Siumauricio** [comment]
Ok but let me ask you something, how does that affect you?

**Comment by anders-code** [comment]
it affects me because:
- if i wanted to adopt this program, i could not because it is not a proper license (open-source or proprietary). legally murky or invalid licenses cannot be used in a professional context.
- i support the legitimate many, many, open source projects that use the Apache license and others like it. therefore it is an attack on them and us when it is misused.
- as it stands, you have violated  the Apache copyright and trademark. *i care about and respect both of those*. as you say: "with the license it is something that you cannot go against what I think, what I want to do or what I say". but in this case *they* did say. but Apache has a license and what *they* said is "you cannot do this." you cannot call this thing Apache or Open-Source when it is neither. You can call it "DokPloy Source mostly Available License" or something like that.
- i would love to use this product, but cannot. not because it isn't good. not because it is closed-source. because - it is licensed under a "bogus" license that is neither open source, nor closed. it is a giant legal liability.

you must understand: to be "Open Source" you must be, verbatim, in compliance with some OSI approved license. if you are not, or you add extra terms, that is fine, but you *cannot* claim open source at that point. if you still claim open-source when you are not, it is essentially fraud and will be *very* poorly received by the community.

the best course of action to achieve what appears you wish, is to make very, very clear, what parts of the project are under a true Open Source license such as Apache. and what parts are not. the parts that are not should be separated and be licenses accordingly (for example, "Modification of Paid Features", "Prohibition of Unauthorized Resale", "Commercial Distribution"). these terms all make the software NON-open-source. The best thing to do is to consult an attorney and draft a license that does what you wish. you should separate that code into a different repo and then you clearly apply that new license to that code.

**Comment by Siumauricio** [comment]
You gave me good reasons, I told you, under no circumstances will the project be possible for sale in a service like saas or something like that unless you ask me for a letter explaining your reason, at least until I decide to change the license which as I told you, you have a high chance that I will give you permission without costing you a cent. but I want people to do it, I'll give you a hypothetical case that obviously doesn't compare to me but elasticsearch did the same, they were open and people take advantage of people's nobility and time, this software is mostly for personal use , some project of one of your clients, agencies, everything that does not have to do with literally selling the product is valid, which is very strange that someone would try to sell a product like this, but I repeat, I would not mind letting someone resell my application as a service as long as you ask me for permission I give it to you without charging you anything, I understand, I will remove the Apache license, however I will make a customizable license, you or whoever you want can call it open source or not, at the end of the day the users are the ones who decide to use this, and I'm not restricting its use at all it's open to everyone, I just want to maintain the authority of this.

At least so far it won't be with a license that you or anyone else wants unless I decide.

But if will remove the term Apache from the license, thank you.

**Comment by anders-code** [comment]
that seems right. "I understand, I will remove the Apache license, however I will make a customizable license"

just please understand, we love that you put this out there for people to use. that is 100% not the problem. you should use a license of your choosing.

"it's open to everyone, I just want to maintain the authority of this."

just please also remember that it is not fair to call it "Open-Source" if it is not a license vetted by the OSI (https://opensource.org/licenses)  or supports the same freedoms.

I think that there *are* open-source/free and non-open-source/non-free licenses that do what you wish for releasing your product. If you notice, elastic has clearly deliniated that some of their code is under the "Apache 2.0" license while other parts are under "Elastic License and Server Side Public License (SSPL)" (https://www.elastic.co/pricing/faq/licensing). You may want to investigate AGPL and GPL licenses, or dual licensing with either or both, for example.

I think you may want to review https://www.gnu.org/philosophy/free-sw.en.html and https://opensource.org/osd to understand what we mean by "free" or "open source" software. It does *not* mean it cannot be commercialized, but it does mean that you cannot control or limit the core freedoms.
