### ISSUE TITLE
How can cancel stuck sever steup work

### ISSUE THREAD

**Issue by guotingchao** [Dokploy/dokploy#826]
### To Reproduce

# When i used Setup Server 
2. Add Ssh key
3. Deployments -> Setup Server

> 🤔 Then: 
> ![image](https://github.com/user-attachments/assets/9f147bc6-2498-475a-b7aa-9f0fefa1f059)

Even the previous Job is still running after I run it again 😂

![image](https://github.com/user-attachments/assets/2a281704-2ab3-4fa7-bc35-f1deb4d62f5b)

### Current vs. Expected behavior

I think maybe user can stop or clear the stuck job.

### Provide environment information

```bash
OS: Ubuntu 20.04
  Arch: arm64
Dokploy version: v0.13.1
VPS Provider: TencentCloud
```

### Which area(s) are affected? (Select all that apply)

Installation, Remote server

### Are you deploying the applications where Dokploy is installed or on a remote server?

Both

### Will you send a PR to fix it?

Maybe, need help

**Comment by Siumauricio** [comment]
If your server is down due to some external factor, then the log will remain in the running state, when you do more setups it will go away so don't worry
