### ISSUE TITLE
Ability to Revert to Older Versions of Deployed Apps in Dokploy

### ISSUE THREAD

**Issue by kurtiz** [Dokploy/dokploy#827]
### What problem will this feature address?

Currently, Dokploy allows users to view the last 10 deployments and their logs, but there is no option to revert to a specific older version of a deployed app. Sometimes, I need to revert to a version that was deployed well before the most recent deployments, but the platform only shows recent logs and versions, but doesn't offer the option to roll back to older deployments.

### Describe the solution you'd like

It would be incredibly useful if Dokploy added functionality to revert to a specific version of a deployed app from the deployment history. This would involve allowing users to not only view the list of past deployments and their associated logs but also to select and roll back to any version of a deployed app (similar to features offered by other platforms like Caprover). This could be done either by storing the commit hashes or the actual files for each deployment or the docker image data to be able to spawn them easily. options can be given to select maximum number of history to be kept for flexibility sake

### Describe alternatives you've considered

One alternative could be to manually track and store previous versions or use custom scripts to manage version control outside of Dokploy. However, this would be cumbersome and not as seamless as a built-in rollback feature.

### Additional context

Platforms like Caprover offer a similar feature where users can revert to specific versions of deployed apps, allowing greater flexibility in managing application rollbacks. Implementing this feature in Dokploy would significantly enhance its usability and user control over deployment versions.

### Will you send a PR to implement it?

No

**Comment by 190km** [comment]
Hey @kurtiz, someone already did a PR for that, and its in the project roadmap : https://github.com/orgs/Dokploy/projects/3?pane=issue&itemId=74565918&issue=Dokploy%7Cdokploy%7C319

I might start working on it when I've finished implementing the new logging system.

**Comment by kurtiz** [comment]
Wonderful thank you... I tried looking for a PR or an issue with a similar or the same feature. I guess I didn't look hard enough.

I'm looking forward to it. I have enjoyed my experience with Dokploy so far 😊

**Comment by Siumauricio** [comment]
Duplicate #319
