### ISSUE TITLE
Long Server Response Time Using Dokploy Service

### ISSUE THREAD

**Issue by cunpingtai** [Dokploy/dokploy#85]
I am experiencing prolonged server response times when accessing my application via the Dokploy service. Despite successful build and deployment, the server response time often exceeds 1200ms. However, when deploying the same application directly on the server, the response time is around 400ms.

## Observed Behavior:

When accessing the application via the Dokploy service, server response times frequently exceed 1200ms.
The application is successfully built and deployed, with HTTPS enabled and a domain bound to it.
The issue is consistent across various endpoints and user activities.
## Expected Behavior:

The server should respond promptly, ideally within 400ms, similar to the performance observed when the application is deployed directly on the server.

## Steps to Reproduce:

 Deploy the application using the Dokploy service.
 Bind a domain and enable HTTPS.
 Access the application via the domain.
 Measure the server response time for various actions (e.g., loading the homepage, navigating through the app).

**Comment by cunpingtai** [comment]
![image](https://github.com/Dokploy/dokploy/assets/65747333/37498f01-6782-46d8-a81d-a4ca0035f94e)
![image](https://github.com/Dokploy/dokploy/assets/65747333/1a24f2f9-a2c8-4c6c-9165-07b082e357b1)

The server response time has slowed down significantly, and I'm sure it's not an issue with my application service because my application queries only a few records, and I've debugged to confirm that the server response is not slow. Accessing the service without going through Dokploy is very fast. However, I'm not sure how to troubleshoot the issue through Dokploy.

**Comment by cunpingtai** [comment]
![image](https://github.com/Dokploy/dokploy/assets/65747333/70bf6fb1-5a59-4d27-92d1-d4cfa14cb4b3)
I created an empty project, used http-server to create a service, and used dokploy for build and deployment. I didn't bind a domain name, configured the port, and accessed it using the IP address. However, the server response time is quite long.

![image](https://github.com/Dokploy/dokploy/assets/65747333/d8a19f16-0fc9-498d-b643-777e98cce121)
Even a 668B static file takes 600ms to load.

Causing all application requests to take at least 400 to 500 ms to respond.

![image](https://github.com/Dokploy/dokploy/assets/65747333/d02564ce-784f-433a-9e84-c157f53eb07b)
This is accessed directly via IP and port, without going through domain name resolution.

**Comment by Mr1Blaze** [comment]
In my case is working faster than my local PC. I'm thinking that problem can't be with dokploy because all my team works with dokploy now in most of cases is fastest. Which VPS are you using ?

**Comment by Siumauricio** [comment]
It may be due to several reasons but one may be:

1. It depends on how far you are from the server, if you are very far away the response will take longer to arrive, if it is a server that is close to you it will go faster.
2. I don't know the specs of your vps, if you don't have enough resources or it is not optimized, the response could be slow.

In my case I have running multiple websites, databases, server side application and the response is almost identical to any cloud provider like netlify, heroku, digital ocean and so on.


Check the image (RUNNING WITHOUT CACHE), i have this application which is a landing page and a web app(dashboard) is a nextjs app which i have 3 for different enviroments and the time of response is almost identical + 3 databases + 3 nestjs(nodejs) applications in a single server

But surely this problem is caused by the reasons I mentioned above.

![image](https://github.com/Dokploy/dokploy/assets/47042324/92cf0068-308b-42b6-80aa-d81829e7b610)

**Comment by cunpingtai** [comment]
> It may be due to several reasons but one may be:
> 
> 1. It depends on how far you are from the server, if you are very far away the response will take longer to arrive, if it is a server that is close to you it will go faster.
> 2. I don't know the specs of your vps, if you don't have enough resources or it is not optimized, the response could be slow.
> 
> In my case I have running multiple websites, databases, server side application and the response is almost identical to any cloud provider like netlify, heroku, digital ocean and so on.
> 
> Check the image (RUNNING WITHOUT CACHE), i have this application which is a landing page and a web app(dashboard) is a nextjs app which i have 3 for different enviroments and the time of response is almost identical + 3 databases + 3 nestjs(nodejs) applications in a single server
> 
> But surely this problem is caused by the reasons I mentioned above.
> 
> ![image](https://private-user-images.githubusercontent.com/47042324/330572401-92cf0068-308b-42b6-80aa-d81829e7b610.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NDM2OTQsIm5iZiI6MTcxNTc0MzM5NCwicGF0aCI6Ii80NzA0MjMyNC8zMzA1NzI0MDEtOTJjZjAwNjgtMzA4Yi00MmI2LTgwYWEtZDgxODI5ZTdiNjEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAzMjMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MWY2ZDBhYmQxYjBhZGVmNWU5YThmYTM0N2ZiZjhjOGMzZTYyMDkzMWI3NzBmOWY0OGYxYzAwYzAwOTY5NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9lrIojq-K40rC_OZq7hKen3ZhO0Hyyhwewyij8r7xSg)


Okay, thanks for the reply.
I tried using two simple services, one is a proxy service through dokploy, and the other is a direct access service.

It is probably caused by unstable network conditions.

The VPS I am using is AWS's EC2.
