### ISSUE TITLE
Create a GitHub App again

### ISSUE THREAD

**Issue by TinsFox** [Dokploy/dokploy#858]
### What problem will this feature address?

I want to link to the GitHub Provider, but I've already created it before. To test something, I removed it. When I wanted to link again, there was only the Create button on the page, but I already had one. Is 
<img width="725" alt="image" src="https://github.com/user-attachments/assets/8c096cb0-b858-4fd4-afab-cbc431ba9a90">

### Describe the solution you'd like

it possible to add a button to "Link existing GitHub App" instead? always create
<img width="712" alt="Google Chrome 2024-12-11 17 29 14" src="https://github.com/user-attachments/assets/15a7993f-9ef7-4e76-ac3e-68b233ee4b5f">

### Describe alternatives you've considered

There is no better solution, otherwise new GitHub Apps will be created for users all the time. If the user forgets to delete it, this will leave a lot of useless apps

### Will you send a PR to implement it?

Maybe, need help

**Comment by kawws** [comment]
For security reasons I think the best way are to connect a new one when you want to sync it, you shouldnt have any unused apps on your GitHub from the start to prevent unauthorized use, but I understand what you come from! Maby a link to the apps place so you can easy se if you already have an app would help

**Comment by kawws** [comment]
[#](https://github.com/Dokploy/dokploy/pull/859)

**Comment by Siumauricio** [comment]
I'm agree there are no way to connect directly in one click with github, to connect to a existent github app I guess it will need some manual configuration like copying all credentials, which would be a very complicated process, I think as this works fine, the implementation of @kawws  is to see all github apps which can help you to delete or modify existing github app
