### ISSUE TITLE
Reload a docker image doesn't log take into account new env vars

### ISSUE THREAD

**Issue by ajubin** [Dokploy/dokploy#860]
### To Reproduce

1. Create a NodeJS application that simply log process.env
2. Deploy it with a docker image (from a github repo)
3. Add env var and reload app (no rebuild) 

### Current vs. Expected behavior

In step 3, I expect to see the newly env var.
I need to rebuild my image to see the new env

### Provide environment information

```bash
Operating System:

 # uname -a
    Linux ubuntu-4gb-fsn1-2 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Dokploy Version: v0.13.1

VPS Provider: Hetzner

Application: Dockerized nodejs
```


### Which area(s) are affected? (Select all that apply)

Application, Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

_No response_

### Will you send a PR to fix it?

Maybe, need help

**Comment by Siumauricio** [comment]
@2shrestha22 You are correct, this is not a bug you need to deploy or rebuild again.
