### ISSUE TITLE
Volumes Only show "File" as type

### ISSUE THREAD

**Issue by juandl** [Dokploy/dokploy#866]
### To Reproduce

I have a docker-compose (raw) and i tried to add a new Volume but is only show "File" as a type

![image](https://github.com/user-attachments/assets/ffbedf30-09c0-4356-baba-41a1e762a3b7)

### Current vs. Expected behavior

Allow to mount file/dir volumen

### Provide environment information

```bash
Dokploy: v0.14.1 (Self hosted)
Ubunutu 22
```

### Which area(s) are affected? (Select all that apply)

Application, Docker Compose

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by ohblue** [comment]
i have the same issue.

**Comment by Siumauricio** [comment]
Please add a minimal reproducible

**Comment by juandl** [comment]
@Siumauricio To be honest, i just installed dokploy using the script and creating an app, checked volumes, and shows the previous capture.

**Comment by LickABrick** [comment]
I have had the same thing from the start (always thought this was not implemented yet). Last week I noticed however that if I add a volume to a database instance I do have multiple options.

Compose (mine is from a git repo):
![image](https://github.com/user-attachments/assets/1575a1bd-cd6a-4893-841d-c10976354015)

Database: 
![image](https://github.com/user-attachments/assets/ba0916b6-8953-4fb0-84e5-fa72dd7e1479)

**Comment by FaintGhost** [comment]
i have the same issue.

**Comment by channchetra** [comment]
I have the same problem here.

**Comment by Siumauricio** [comment]
I still don't understand the problem, can anyone give a way to reproduce the problem? and to understand what is wrong?

**Comment by channchetra** [comment]
https://github.com/user-attachments/assets/3339cf43-4423-4dab-9373-b0d98199648b

the problem is when we creating service in Compose or Template mode we can't add any volume it's show only file mount not have Bind and Volume mount but for normal Application and Database is fine.

**Comment by channchetra** [comment]
https://github.com/user-attachments/assets/58113bed-4d77-478c-8969-60c402dc8252
There's a discrepancy in volume mounting options when creating services. In Compose and Template mode, only "File" mounts are available in the advanced settings. However, when creating applications or databases in standard mode, the expected "Bind" and "Volume" mount options are present.

**Comment by Siumauricio** [comment]
It is not a discrepancy, it is simply that it does not make sense to have bind mounts from the interface because in docker compose the volumes are handled through the compose file, we only offer the file mounts because it is the only thing that is needed to deploy any template and a proof of them is that we have complex templates like supabase https://github.com/Dokploy/dokploy/blob/canary/apps/dokploy/templates/supabase/index.ts

**Comment by channchetra** [comment]
Yes after I try to rearrange my compose it seems this is fine 🙏

**Comment by Siumauricio** [comment]
Since there is no response I will close this issue. Feel free to reopen with the exact steps and limitation you are having, but for now I don't consider there's a limitation

**Comment by juandl** [comment]
I understand you want to close this issue, but what about compose that contains "volumes"?  @Siumauricio 

![image](https://github.com/user-attachments/assets/7013eb21-039d-4a74-b8b9-f4865048b96f)


```
services:
  homarr:
    image: ghcr.io/homarr-labs/homarr:beta
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - homarr:/appdata
    ports:
      - '7575'
```

**Comment by paradoxmr24** [comment]
> I understand you want to close this issue, but what about compose that contains "volumes"? [@Siumauricio](https://github.com/Siumauricio)
> 
> ![image](https://github.com/user-attachments/assets/7013eb21-039d-4a74-b8b9-f4865048b96f)
> 
> ```
> services:
>   homarr:
>     image: ghcr.io/homarr-labs/homarr:beta
>     restart: unless-stopped
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - homarr:/appdata
>     ports:
>       - '7575'
> ```

Did you add volumes at the end that states all the named volumes used?

**Comment by merchizm** [comment]
<img width="1112" height="1046" alt="Image" src="https://github.com/user-attachments/assets/1f618696-b178-4a5d-838f-844b736c8372" />
The problem persists. I loaded and ran my own compose file, but I can't add volumes. What is the default directory for volumes? Do we have to add them from the interface?
