### ISSUE TITLE
feat: remove docker volumes on deletion of service

### ISSUE THREAD

**Issue by DJKnaeckebrot** [Dokploy/dokploy#876]
### What problem will this feature address?

After creating a lot of services my docker volume ls is pretty big with volumes that I do not need anymore. To keep the system clean I would like to have them removed when I delete an service

### Describe the solution you'd like

Add a toggle to the delete confirmation which allows for selecting to remove the associated volumes

### Describe alternatives you've considered

Writing my on bash script to rm all volumes that are not in use

### Will you send a PR to implement it?

Yes

**Comment by Siumauricio** [comment]
@DJKnaeckebrot Makes sense I think this is also the same as #513

**Comment by DJKnaeckebrot** [comment]
> @DJKnaeckebrot Makes sense I think this is also the same as #513 

Oh yeah sorry didn't found that one :D I already have it running for compose apps. Just need to make the UI a bit better and replicate to the other services.

I'll open a PR once it's done

**Comment by Siumauricio** [comment]
Thank you in the meantime, let's close this issue and move to #513
