### ISSUE TITLE
Compatibility with other templates.

### ISSUE THREAD

**Issue by Digital-Media-Group** [Dokploy/dokploy#883]
### What problem will this feature address?

Having few templates currently.

### Describe the solution you'd like

It would help to have more services available with one click of installation.

### Describe alternatives you've considered

Example:
https://caprover.com/docs/one-click-apps.html

### Will you send a PR to implement it?

No

**Comment by 190km** [comment]
hi @Digital-Media-Group, there are already 70 templates currently, and new ones are added with each new release, and if you want a specific template, you can open an issue, or ask to implement it on discord. Otherwise, if you don't see all the templates, you can update dokploy to access them.

**Comment by Siumauricio** [comment]
I agree @190km  I don't see much point in adding support for a structure that is not something standard like what we use which is docker compose.
