### ISSUE TITLE
validation of setup thorw error message

### ISSUE THREAD

**Issue by QThans** [Dokploy/dokploy#899]
### To Reproduce

1. Setup server Done
2. go to "Validate" tab, then click "Refresh".

### Current vs. Expected behavior

Validate prompt: Failed to parse output: Unexpected token } in JSON at position 199

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 22.04
  Arch: arm64
Dokploy version: newest
VPS Provider: Netcup
```

### Which area(s) are affected? (Select all that apply)

Remote server

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Additional context

<img width="836" alt="image" src="https://github.com/user-attachments/assets/c3a47735-d806-497b-a356-229b2e2181fd" />

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
Hey this was previously reported here (https://github.com/Dokploy/dokploy/pull/870)
