### ISSUE TITLE
"Invalid memory value" error preventing build

### ISSUE THREAD

**Issue by johngrimsey** [Dokploy/dokploy#903]
### To Reproduce

1. Apply memory reservation or limit values in the 'Resources' section for a Docker service.
2. Rebuild/deploy the service

## Current

Error in the logs:

```
(HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = invalid memory value 4096: Must be at least 4MiB
```

If I remove the Memory Limit value, then the error will occur and use '256' as the erroneous value reported.

If I remove all the values, everything works fine.

# Expected

No build/deploy error. Memory reservation/limit correctly applied to deployed container.

### Provide environment information

```bash
Dokploy v15.0

After upgrading from v13->v14, then v14->v15 - without testing in v14

Was working with v13
```

### Which area(s) are affected? (Select all that apply)

Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Additional context

Dokploy running on Debian 12, remote server Ubuntu 20.04

### Side note

When seeing if a build/deployment has worked ok the user journey is:
1. Click rebuild
2. Click confirm
4. Click deployments tab
5. Click View on latest deployment

If there can be a shortcut to show logs that appears whilst a build/deployment is in process that would be very useful 👍 

### Will you send a PR to fix it?

No but I would if I could!

**Comment by Siumauricio** [comment]
This is not a bug, it's what the docker api expects directly, I commented here https://github.com/Dokploy/dokploy/issues/510#issuecomment-2543420601
