### ISSUE TITLE
Enter Terminal option for Dokploy server itself

### ISSUE THREAD

**Issue by LickABrick** [Dokploy/dokploy#916]
### What problem will this feature address?

Currently you can open the terminal for added servers (via Settings --> Servers --> Actions --> Enter the Terminal) but you can't do this for the Dokploy server itself.

### Describe the solution you'd like

Add the 'Enter Terminal' action to Settings --> Server --> Server --> Actions

### Describe alternatives you've considered

-

### Will you send a PR to implement it?

No

**Comment by Siumauricio** [comment]
I think it is not necessary to add another separate interface to just access the dokploy ui server, you can perfectly create a server  in the servers section that points to your dokploy ui instance and manage everything from there.

**Comment by nktnet1** [comment]
Hey @Siumauricio - as of v0.17.0, I now see the following:

![enter-dokploy-server-terminal](https://github.com/user-attachments/assets/14575a49-cd9b-435d-ab04-4cfb04959e31)

Although it doesn't seem to connect, for both my VPS (Hetzner) and Home lab (cloudflare tunnel):

![enotfound](https://github.com/user-attachments/assets/e0936daf-a6e0-4fc7-9ccf-53c61986bbc3)
