### ISSUE TITLE
499 client closed request error on uploading large files

### ISSUE THREAD

**Issue by qasimali09** [Dokploy/dokploy#923]
### To Reproduce

499 client closed request error when upload large files in any nodejs application currently i am testing in ghost cms

### Current vs. Expected behavior

Not uploading large files

### Provide environment information

```bash
Version: v0.15.0
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

Yes

**Comment by drudge** [comment]
Sounds like it may be related to Traefik read timeouts... https://doc.traefik.io/traefik/migration/v2/#entrypointtransportrespondingtimeoutsreadtimeout

**Comment by qasimali09** [comment]
`entryPoints:
  web:
    address: ':80'
    transport:
      respondingTimeouts:
        readTimeout: 0s
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt
    transport:
      respondingTimeouts:
        readTimeout: 0s`

Thanks! This configuration update in traefik.yml fixed the issue.
