### ISSUE TITLE
Docker CPU Resource Parameters - Invalid CPU value error when deploying container

### ISSUE THREAD

**Issue by QuinnGT** [Dokploy/dokploy#927]
### To Reproduce

1. Set up a Docker container with any image
2. Configure container resources in Dokploy UI:
    - CPU Limit: 2
    - CPU Reservation: 2
    - Memory Reservation: 1024
    - Memory Limit: 4096 
3. Click Save and attempt to deploy
4. Container fails to deploy with CPU value error

### Current vs. Expected behavior

Following resource configuration through the Dokploy UI, the deployment fails with error:` "(HTTP code 400) unexpected - rpc error: code = InvalidArgument desc = invalid cpu value 2e-09: Must be at least 0.001"`

Expected behavior: Container should deploy successfully with the specified CPU and memory resource limits.

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 20.04
  Arch: arm64
Dokploy version: 0.15.0
VPS Provider: AWS
What applications/services are you trying to deploy?
  - Python application with Playwright and LibreOffice dependencies
```

### Which area(s) are affected? (Select all that apply)

Application, Docker

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Additional context

The error persists even after trying different CPU configurations. The issue appears to be related to how the CPU values are being interpreted or converted when applying the container resource limits. The deployment process successfully downloads and installs dependencies (including Playwright webkit) but fails at the final resource allocation stage.

### Will you send a PR to fix it?

No

**Comment by parkerjj** [comment]
Same here, only buggy on Dockerfile, not docker-compose.

But for a simple solution is that you can set the CPU and CPU limitation to 100000000 (It's 1.0). 
It will work for me.
<img width="1311" alt="Screenshot 2024-12-17 at 11 58 50 pm" src="https://github.com/user-attachments/assets/117ea177-8703-48c3-a10d-c037e5fbfd55" />

**Comment by Siumauricio** [comment]
Duplicate #903

**Comment by QuinnGT** [comment]
No, this is a different issue. I've always used those cpu values for docker type builds and hasn't been a problem till v15 of dokploy. Reopening. Please review the issue this time.

**Comment by Siumauricio** [comment]
It's the same error only in a different property read this please https://github.com/Dokploy/dokploy/issues/510#issuecomment-2543420601

**Comment by Siumauricio** [comment]
The change was made in version 15, and it was something to prevent the conversion that we probably did incorrectly, for that we simply pass the value directly to what the docker api expects.

you can see the PR https://github.com/Dokploy/dokploy/pull/893/files
