### ISSUE TITLE
Escape sequences are not properly displayed in a monitoring tab (regression)

### ISSUE THREAD

**Issue by daniel-abramov** [Dokploy/dokploy#932]
### To Reproduce

Just open a monitoring app for the service that logs with colors.

<img width="1209" alt="Screenshot 2024-12-18 at 13 32 09" src="https://github.com/user-attachments/assets/5d8a2c89-3ce6-4681-8ffb-debc007e7989" />

### Current vs. Expected behavior

Instead of the proper colors, escape codes are just printed as a plain string, which makes logs unreadable:

This seems to be a regression because the version I used about 1-1.5 months ago displayed it correctly, i.e., all log entries' colors were adequately interpreted, and it displayed correctly.

The monitoring tab has recently been redesigned, and its new design looks nice overall. Unfortunately, this bug makes the log records unreadable.

### Provide environment information

```bash
OS: Ubuntu 24.04.1 LTS
Dokploy: v0.15.0
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by drudge** [comment]
ANSI color code support was added to the new logging interface in #912 and will be included in the next release.

**Comment by Siumauricio** [comment]
This bug has been fixed by @drudge so we can close this for now
