### ISSUE TITLE
Make it possible to change database credentials in the UI

### ISSUE THREAD

**Issue by daniel-abramov** [Dokploy/dokploy#933]
### What problem will this feature address?

Once the database is created, there is no way to change the credentials in the UI. The UI fields are read-only and can only be copied but not changed, so the username and password cannot be changed in the UI.

### Describe the solution you'd like

It would be nice if it was possible to change such basic things in the UI (otherwise, there is not much difference between deploying the database manually via, e.g., docker-compose).

### Describe alternatives you've considered

The alternative solution is to change it manually via e.g. `psql`, but this means that the UI in dokploy will display invalid (obsolete) information about the username and password that does not reflect the reality.

### Will you send a PR to implement it?

Maybe, need help

**Comment by Siumauricio** [comment]
No, it is not possible to change the credentials once the database has been deployed it mounts a volume that contains all the necessary information and even if you change the information it will not be updated, the only way is the one you mention which is using the terminal and changing the password.

So I don't think we will be able to proceed with this issue for now.

**Comment by benosman** [comment]
Most database docker images do have the provision to update the root and user passwords through their default entrypoints and use of env variables.

I haven't checked all the ones dokploy is using, but other systems like coolify manage to do this without custom code as far as I can see.

Even if it wasn't possible for some, it would still be handy to be able to update the the credentials, as when connecting to a DB from an app, the first point of call when preparing the credentials is the dokploy database config, which if changed would be stale.

**Comment by melkishengue** [comment]
@Siumauricio while changing credentials via the cli works, postgres continues to produce a lot of logs because it tries to connect with the old credentials entered in the frontend, and it fails.

<img width="1298" height="565" alt="Image" src="https://github.com/user-attachments/assets/cd223f4f-12fe-43ce-b7dd-653bb2437588" />

**Comment by JuansesDev** [comment]
Im working on this feature for Postgress

<img width="1909" height="956" alt="Image" src="https://github.com/user-attachments/assets/bbe7b330-3af5-4d9b-80ee-72173d6e8bd2" />

<img width="1920" height="959" alt="Image" src="https://github.com/user-attachments/assets/38c28bee-974e-42d1-b323-6a4f20c75d2c" />

<img width="1920" height="959" alt="Image" src="https://github.com/user-attachments/assets/17a812b0-ab15-47d6-b64f-a46a03c70622" />

**Comment by bschmalb** [comment]
Nice @JuansesDev ! im waiting for this

**Comment by ebroelevado-beep** [comment]
I hope you implement it in the next version!

**Comment by joaopedrofrech** [comment]
Change passwords, users, create and manage databases. This is necessary, otherwise what's the difference from deploying direcly if we have to use the CLI anyway? Hope to see this implemented, really nice!

**Comment by laakal** [comment]
@Siumauricio Dokploy’s change database password feature does not work as expected.
Even though the PostgreSQL container is clearly running, Dokploy shows the following error:

`The database container is not running. Please start the service before changing the password.`

**Comment by sdrubish** [comment]
I would love some guidance on how to safely change the password of a production DB in a multi-node dockploy setup, where DB container and dokploy container live on different physical nodes

Which does trigger the `The database container is not running. Please start the service before changing the password.`
