### ISSUE TITLE
Modify the Traefik port, the added server Traefik has not been changed

### ISSUE THREAD

**Issue by aliuq** [Dokploy/dokploy#950]
### To Reproduce

1. Modify traefik port using `TRAEFIK_SSL_PORT` and `TRAEFIK_PORT`

```bash
sudo docker service create \
    --name dokploy \
    --replicas 1 \
    --network dokploy-network \
    --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
    --mount type=bind,source=/etc/dokploy,target=/etc/dokploy \
    --mount type=volume,source=dokploy-docker-config,target=/root/.docker \
    --publish published=3000,target=3000,mode=host \
    --update-parallelism 1 \
    --update-order stop-first \
    -e PORT=3000 \
    -e TRAEFIK_SSL_PORT=8443 \
    -e TRAEFIK_PORT=8000 \
    --constraint 'node.role == manager' \
    dokploy/dokploy:latest
```

2. Add server xxx.xxx.xxx.xxx, execute `setup server`, see the port in the script as follows

![image](https://github.com/user-attachments/assets/0488457f-0d3b-43f7-a7a8-b1b6036dfc74)

3. View the ports exported by the traefik container on the server xxx.xxx.xxx.xxx

![image](https://github.com/user-attachments/assets/735f1289-8c99-4484-aa2d-d1098bf9442a)

### Current vs. Expected behavior

Hope it is consistent with the port used in the script

### Provide environment information

```bash
OS: Ubuntu 24
Arch: amd64
Dokploy version: `v0.15.0`
```

### Which area(s) are affected? (Select all that apply)

Installation

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Will you send a PR to fix it?

No

**Comment by Siumauricio** [comment]
This is not an error, it is necessary to add manually in the configuration

**Comment by aliuq** [comment]
> This is not an error, it is necessary to add manually in the configuration

I think this is a problem, the ports of these two positions are not consistent, this is the script after the reset operation. Maybe it is possible to make them consistent in the initial state
Another problem, modifying the external traefik configuration will affect the traefik configuration of server xxx.xxx.xxx.xxx

![image](https://github.com/user-attachments/assets/0ef3d803-a40d-48ed-8a95-5cb580ae5055)

**Comment by Siumauricio** [comment]
What happens is that if you already had dokploy installed with all its settings, and you re-run that command dokploy will not update those settings for you, you have 1 option and that is to completely remove dokploy or delete the /etc/dokploy/traefik folder and then re-run the command you put above.

**Comment by aliuq** [comment]
> What happens is that if you already had dokploy installed with all its settings, and you re-run that command dokploy will not update those settings for you, you have 1 option and that is to completely remove dokploy or delete the /etc/dokploy/traefik folder and then re-run the command you put above.

If you are adding the server for the first time, you do not know that you need to modify the script content to make the server work properly.

**Comment by Siumauricio** [comment]
This is precisely why we exposed the script so that you have full control over the script, 

another thing in reproduce you are using the manual installation command which is totally different and has nothing to do with what is executed in the remote servers.

**Comment by aliuq** [comment]
> This is precisely why we exposed the script so that you have full control over the script,
> 
> another thing in reproduce you are using the manual installation command which is totally different and has nothing to do with what is executed in the remote servers.

Can you introduce the things to pay attention to when modifying the Traefik port in the document?

**Comment by Siumauricio** [comment]
I could accept a PR, but I don't think it would be that simple to implement.

**Comment by aliuq** [comment]
@Siumauricio There is another problem. When I modify the traefik configuration of server A through the UI, it will also change the traefik configuration on the Dokploy instance. So if I modify the traefik port on the Dokploy instance, when I update the traefik port of server A, traefik configuration will cause traefik on the Dokploy instance to fail.
