### ISSUE TITLE
Projects monitoring page does not show accurate resource usage

### ISSUE THREAD

**Issue by Flqsh** [Dokploy/dokploy#976]
### To Reproduce

1. Create a service that uses resources
2. Note the resource usage shown on the service's monitoring page
3. Note the resource usage on the server's main monitoring page (/dashboard/monitoring)
4. Notice that service usage is higher than server's usage

### Current vs. Expected behavior

Expected to see the main monitoring page report the server's overall resource usage, including the combined usage of all services. Instead, main monitoring page shows minimal resource usage.
![image](https://github.com/user-attachments/assets/aac35fc6-399b-4686-b6ae-eee86449e5a6)
![image](https://github.com/user-attachments/assets/3ca2e650-e3b7-4b9b-9816-89dfaf4fb095)

### Provide environment information

```bash
Operating System:
  OS: Ubuntu 20.04
  Arch: x86
Dokploy version: 0.15.1
VPS Provider: Hostinger
Applications: Database, node application
```

### Which area(s) are affected? (Select all that apply)

Application, Databases, Remote server

### Are you deploying the applications where Dokploy is installed or on a remote server?

Same server where Dokploy is installed

### Will you send a PR to fix it?

No

**Comment by DJKnaeckebrot** [comment]
Hey @Flqsh,

I guess this is not a bug. The project shows the usage of the assigned CPU/RAM for the application while the main page shows the whole server.

**Comment by Flqsh** [comment]
Thanks for the reply. I would think whole server usage should include everything running on the server. If I run htop on the server, it shows a total ram usage usage of 9GB+, not 0.41GB.

**Comment by DJKnaeckebrot** [comment]
oh my bad, I just saw that it seems they are switched somehow. I'll take a look :)

**Comment by Siumauricio** [comment]
I guess is the same as #673, so we can close for now
