### ISSUE TITLE
Connect multiple Github organizations

### ISSUE THREAD

**Issue by tiero** [Dokploy/dokploy#98]
Currently, I can only use one GH org at the time for each instance. Would be super helpful to whom has repo across dozen of organizations :)

<img width="487" alt="image" src="https://github.com/Dokploy/dokploy/assets/3596602/3f11f2a0-b5fe-4d39-bd1c-9829bc11b427">

**Comment by Siumauricio** [comment]
It would be great to have multiple github providers, for now let's keep it open, it will be low priority for now.

**Comment by iamsid** [comment]
We use Caprover right now. Which is based on similar concepts.
There we have the option to set Git credentials per app. Its very helpful.
Could be something to look into among other things.

**Comment by jeremybosma** [comment]
I agree on this, first thing that was a deal breaker for me instantly on the first day of use.

**Comment by tiero** [comment]
fyi we are hosting one separated instance for each GitHub organization. It works for now, agreed centralization in a single dashboard would be best!
