### ISSUE TITLE
Error to save the deployment

### ISSUE THREAD

**Issue by ravinataraju** [Dokploy/dokploy#986]
### To Reproduce

Create Project
Create Application on a Remote Server
Select Drop
Drag and Drop application zip file
Hit Deploy
Error to save the deployment

### Current vs. Expected behavior

Instead of getting Error to save the deployment, it should be deploying the application on the remote server for which it has access to.

### Provide environment information

```bash
OS: UBUNTU 24.04
Dokploy: Version: v0.15.1
user connecting to remote server : root
```

### Which area(s) are affected? (Select all that apply)

Application

### Are you deploying the applications where Dokploy is installed or on a remote server?

Remote server

### Will you send a PR to fix it?

No

**Comment by sancho1952007** [comment]
This bug is happening again but for a different reason now.
Logs:
```
Error processing ZIP file: TypeError: isDate is not a function
```

**Comment by PwccaCode** [comment]
Bug was reintroduced latest update but for unrelated reason isDate is not a function bug
